### PR TITLE
[12.0] [MIG] Account Invoice Constraint Chronology

### PR DESCRIPTION
**Pull request by ThomasBinsfeld**
+ a small refactoring: prepare methods for the domains

### CODE REVIEW

**Review by sbidoul — APPROVED** [review]

**Comment by chrisdec** [comment]
Functional test 👍

**Comment by pedrobaeza** [comment]
Can you squash a bit the commit history from Adrien and add some test coverage to this module?

**Review by chrisdec — APPROVED** [review]
Functional test 👍

**Comment by ThomasBinsfeld** [comment]
@pedrobaeza Done

**Pull request merged**
