### PR TITLE
[IMP][account_asset_management] - use model_create_multi for account move line creation

### PR DESCRIPTION
**Pull request by sbejaoui**
The usage of model_create_multi improve the performance for big account move creation.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
What about minimizing the diff letting a method for the single vals adjust and calling it from the multiple one?

**Comment by sbejaoui** [comment]
> What about minimizing the diff letting a method for the single vals adjust and calling it from the multiple one?

like [this](https://github.com/OCA/account-financial-tools/pull/938/files#diff-8e960ef118249d0f50c60aa4924b2629R66) ?

**Review by pedrobaeza — APPROVED** [review]
Yes, thanks!

**Review by luc-demeyer — APPROVED** [review]

**Pull request merged**
