### PR TITLE
[15.0][FIX] account_fiscal_year: avoid trigger of uninstall 'fiscalyear' date range type

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Due to https://github.com/OCA/account-financial-tools/commit/070595a19bfe2d7bfbcc35e9c6ac91ae7bfd19ed.

### CODE REVIEW

**Comment by adrienpeiffer** [comment]
As this change was done in the 14.0 branch, I'm not sure this is the right place to add this script. I would like to avoid "pollution" with script related to changes for the previous version.

**Comment by MiquelRForgeFlow** [comment]
> As this change was done in the 14.0 branch

Wrong, it was done in v15. In v14 exists the record (https://github.com/OCA/account-financial-tools/blob/14.0/account_fiscal_year/data/date_range_type.xml#L3), and is in v15 that the record is deleted and gives migration problem.

**Comment by adrienpeiffer** [comment]
Oh. It was removed and added again https://github.com/OCA/account-financial-tools/commit/5812d6fe9c64b5cf3558b7a33d7f8c0545e8ae4f
Thanks for clarification.

**Review by adrienpeiffer — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]

**Pull request merged**
