### PR TITLE
fix typo in previous commit

### PR DESCRIPTION
**Pull request by gurneyalex**
wrong safe_eval import
+fix some pylint errors on the way

### CODE REVIEW

**Comment by gurneyalex** [comment]
@pedrobaeza ping!

**Comment by pedrobaeza** [comment]
hehe, :+1: 

I don't have now moral strength to fast-track this also...

**Comment by tafaRU** [comment]
:wink: :+1:

**Comment by gurneyalex** [comment]
my apologies for the copy-paste error in the previous PR

**Comment by pedrobaeza** [comment]
My apologies also for fast-tracking it. This will serve me as a lesson.

**Comment by gurneyalex** [comment]
I'll merge this, since the remaining failures are not related to the fix.

**Pull request merged**
