### PR TITLE
[FIX] account_check_deposit: fix value passed for currency in monetar…

### PR DESCRIPTION
**Pull request by patrickt-oforce**

### CODE REVIEW

**Comment by patrickt-oforce** [comment]
@etobella this PR fix error in #1758, can you approve and if ok merge?

**Review by matteoopenf — APPROVED** [review]

**Comment by patrickt-oforce** [comment]
@etobella thankyou

**Comment by pedrobaeza** [comment]
Merged into `15.0-ocabot-update-dotfiles`?

**Comment by pedrobaeza** [comment]
Ah, I see. To be integrated into the other PR.

**Pull request merged**
