### PR TITLE
[15.0][MIG]account_asset_management

### PR DESCRIPTION
**Pull request by xavigutipujol**
This module depends on: report_xlsx_helper

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
I think you should update the commit history and add all the recent commits in 14.0 branch. This module in 14.0 branch is in 14.0.2.7.0 version now, far from the 14.0.2.4.4 you migrated 😉

**Comment by rafaelbn** [comment]
Dear @xavigutipujol , please could you review this comment https://github.com/OCA/account-financial-tools/pull/1339#issuecomment-1040227408 ? Thank you!

**Comment by HaraldPanten** [comment]
Closed. Superseded by https://github.com/OCA/account-financial-tools/pull/1377

**Pull request closed without merging**
