### PR TITLE
[12.0][MIG] account_move_template

### PR DESCRIPTION
**Pull request by alexis-via**
This is not really a migration from v11 to v12, but a full re-write of this module, following an exchange on the mig to v11 PR https://github.com/OCA/account-financial-tools/pull/728

Improvements:
- good domain on partner
- proper handling of date and ref in the wizard
- ability to check the journal in the wizard
- use float_round to avoid floats such as 3.666666666 in credit or debit (easy to achieve with type = compute), which can lead to big problems in Odoo's accounting (for example : in a balance with all accounts, total of credit may be different from total of debit !)
- cleaner, simpler and easier code

### CODE REVIEW

**Comment by alexis-via** [comment]
I forgot to say that there is one drawback with this PR: I removed the objects "account.document.template" and "account.document.template.line" which were used by account_invoice_template from OCA/account-invoicing (because I discovered that this other module was using it after the re-write).

**Comment by alexis-via** [comment]
And another thing I forgot to say: in the compute formula, L(0) should be replaced by L0 (no more parenthesis).

**Review by CasVissers-360ERP — APPROVED** [review]
Functionally working fine!

**Review by scigghia — APPROVED** [review]
it works
thank you

**Review by mourad-ehm — APPROVED** [review]
Code review

**Comment by andreampiovesana** [comment]
go

**Comment by OpenCode** [comment]
@alexis-via Can you merge?

**Pull request merged**
