### PR TITLE
[16.0][MIG] account_move_fiscal_year: Migration to 16.0

### PR DESCRIPTION
**Pull request by BT-anieto**

### CODE REVIEW

**Review by BT-mrobles — APPROVED** [review]
Thanks for your amazing work! Looks good to me

**Review by BT-nfrancisco — APPROVED** [review]

**Comment by BT-anieto** [comment]
@OCA/accounting-maintainers Could it be merged?

**Review by etobella — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
