### PR TITLE
[MIG] account_journal_general_sequence: account move entry sequence

### PR DESCRIPTION
**Pull request by yajo**
Under some legislations, account moves must follow a single sequence. Since Odoo removed this sequence number in recent versions, this information was lost.

With this module, you can force your account moves to follow a separate sequence. The sequence is automatic when a move is posted. Includes a wizard to reorder those numbers in the sequence.

@moduon MT-676 fw-port-of https://github.com/OCA/account-financial-tools/pull/1406

### CODE REVIEW

**Comment by yajo** [comment]
Can somebody with permissions retry the pre-commit CI job that's failing please?

**Review by ghost — APPROVED** [review]
Functional Review. LGTM

**Review by rafaelbn — APPROVED** [review]
This is a migration from v14 from v15.

Tested and running in production

**Pull request merged**
