### PR TITLE
[12.0][ADD] account_move_chatter: Chatter on journal entries

### PR DESCRIPTION
**Pull request by pedrobaeza**
This module adds the chatter on the journal entries for managing attachments and communications in this document.

This has been added on version 13, so this module won't be needed there.

Configuration
=============

For seeing journal entries, you need to have the permission "Show Full Accounting Features" in your user (being in developer mode).

Usage
=====

* Go to *Invocing > Accounting > Accounting Entries > Journal Entries*.
* Select one journal entry.
* You will see there the chatter.

cc @Tecnativa TT22686

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Travis is failing due to other module and it's unrelated to this PR.

**Review by carlosdauden — APPROVED** [review]

**Comment by carlosdauden** [comment]
Travis green

**Review by rafaelbn — APPROVED** [review]
Thanks :+1:

**Review by sergio-teruel — APPROVED** [review]

**Pull request merged**
