### PR TITLE
[13.0][IMP]account_move_template: Archive account move templates

### PR DESCRIPTION
**Pull request by manuelregidor**
Archive account move templates

### CODE REVIEW

**Comment by manuelregidor** [comment]
@HaraldPanten @ValentinVinagre

**Review by HaraldPanten — APPROVED** [review]
LGTM

**Review by ValentinVinagre — APPROVED** [review]
👍🏻 LGTM

**Comment by HaraldPanten** [comment]
@pedrobaeza do you mind fast-tracking this one? 🙏 THX!

**Pull request merged**
