### PR TITLE
[FIX] add flake8 directive to ignore scenario files

### PR DESCRIPTION
**Pull request by nbessi**

### CODE REVIEW

**Comment by bwrsandman** [comment]
I am usually very opposed to using `#noqa`

Can you explain what these files are and what is ignored.

Can we just modify the quality tools to encompass these cases instead of adding `noqa` to every similar occurrence in the future.

**Comment by gurneyalex** [comment]
@bwrsandman the affected files are test scenarios which are meant to be used with OERPScenario (Behavior Driven Development for Odoo with behave). They feature some Python code, which cannot be run outside the behave framework because it provides lots of symbol definitions which cannot be imported from within the code, so they will trigger lots of Errors in flake8. 

This is not a standard way of writing tests as of now, and there is no standardized test layout for modules using OERPScenario (although we would love to have one, and to get this tool more widely accepted in the community). 

Possible solutions:
1. live with the #noqa comment at module level for these files
2. change a bit the layout of the files (to avoid possible collisions) and adapt the QA tools to not run flake8 on e.g. **oerpscenario**
3. same as 2. but run flake8 with some specific errors disabled on **oerpscenario**

I'd also love to have OERPScenario tests run by the QA tools in the future -> https://github.com/OCA/maintainer-quality-tools/issues/66

**Comment by nbessi** [comment]
Maybe we should extract credit control addons into a spearate project. They are quite mature and represent a important code base that may justify a separated projetc.

As those addons uses Scenario to do the setup of vertical testing it may also be more easy to integrate with travis.

**Comment by yvaucher** [comment]
:-1: 
scenarios directory should be always ignored by flake8

I'm for adding scenario or scenario/features directory in https://github.com/OCA/maintainer-quality-tools/blob/master/travis/travis_run_flake8

**Comment by nbessi** [comment]
Deprecated by: https://github.com/OCA/account-financial-tools/pull/24

**Pull request closed without merging**
