### PR TITLE
[10.0][MIG] account_chart_update

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

It's tentative, let's prove on runbot.

May the WIP tag be added.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This is not needed. You already have https://github.com/OCA/account-financial-tools/pull/460 that I have amended.

**Comment by MiquelRForgeFlow** [comment]
Oups, I didn't see it.

@aheficent, you fool! 😂

**Comment by AaronHForgeFlow** [comment]
:stuck_out_tongue_closed_eyes:

**Comment by pedrobaeza** [comment]
As Odoo makes:

shame

**Pull request closed without merging**
