### PR TITLE
[14.0][MIG] account_partner_required

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Comment by hildickethan** [comment]
@alexis-via DId you do the pre-commit step of the https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0#technical-method-to-migrate-a-module-from-130-to-140-branch migration process? The black/prettier changes should be in their own commit and I believe that the tests failed because there aren't any setup files for this module, which are generated when you run the pre-commit

**Review by hildickethan — APPROVED** [review]
Functional review

**Comment by alexis-via** [comment]
Travis is now green. Yes, I made a mistake when porting this module and the black/isort is not in a separate commit :-(

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
You should split the black/isort commit. You can do it now with a bit of git fu:

- Copy current contents
- Rebase interactively
- Edit the commit before the migration
- Run pre-commit.
- Run `git commit -m "[IMP] $MODULE: black, isort, prettier"  --no-verify`
- `git rebase --continue`
- It will stop with conflicts on the migration commit
- Replace module with the backed contents.
- Add changes and continue the rebasing.

**Comment by klodr** [comment]
Can we merge this one ?
Judging by the commit list doing again the thing is time over consuming.

**Pull request closed without merging**
