### PR TITLE
[13.0][MIG] base_vat_optional_vies

### PR DESCRIPTION
**Pull request by HaraldPanten**
MIG to V13

### CODE REVIEW

**Comment by HaraldPanten** [comment]
Ready to review

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍

**Review by juliap98 — APPROVED** [review]
Funcional review ok

**Comment by HaraldPanten** [comment]
@OCA/accounting-maintainers could you merge, please?

**Review by etobella — APPROVED** [review]
LGTM No major changes on the migration

**Comment by HaraldPanten** [comment]
@pedrobaeza my last request for today: Could merge this one?

THX!

**Pull request merged**
