### PR TITLE
[8.0] add asset management modules

### PR DESCRIPTION
**Pull request by luc-demeyer**

### CODE REVIEW

**Comment by eLBati** [comment]
Hello @luc-demeyer 
some flake8 remarks

```
./account_asset_management_xls/wizard/account_asset_report_wizard.py:24:1: F401 'translate' imported but unused

./account_asset_management_xls/report/account_asset_report_xls.py:24:1: F401 'time' imported but unused

./account_asset_management_xls/report/account_asset_report_xls.py:489:13: F841 local variable 'account_pos' is assigned to but never used

./account_asset_management_xls/report/account_asset_report_xls.py:525:17: F841 local variable 'asset_formula' is assigned to but never used

./account_asset_management_xls/report/account_asset_report_xls.py:529:17: F841 local variable 'salvage_formula' is assigned to but never used

./account_asset_management_xls/report/account_asset_report_xls.py:548:9: F841 local variable 'asset_total_formula' is assigned to but never used

./account_asset_management_xls/report/account_asset_report_xls.py:549:9: F841 local variable 'salvage_total_formula' is assigned to but never used

./account_asset_management_xls/report/account_asset_report_xls.py:611:13: F841 local variable 'account_pos' is assigned to but never used

./account_asset_management_xls/report/account_asset_report_xls.py:700:17: F841 local variable 'asset_formula' is assigned to but never used

./account_asset_management_xls/report/account_asset_report_xls.py:705:17: F841 local variable 'salvage_formula' is assigned to but never used

./account_asset_management_xls/report/account_asset_report_xls.py:710:17: F841 local variable 'fy_start_formula' is assigned to but never used

./account_asset_management_xls/report/account_asset_report_xls.py:715:17: F841 local variable 'fy_end_formula' is assigned to but never used

./account_asset_management_xls/report/account_asset_report_xls.py:736:9: F841 local variable 'asset_total_formula' is assigned to but never used

./account_asset_management_xls/report/account_asset_report_xls.py:737:9: F841 local variable 'salvage_total_formula' is assigned to but never used

./account_asset_management_xls/report/account_asset_report_xls.py:739:9: F841 local variable 'fy_start_total_formula' is assigned to but never used

./account_asset_management_xls/report/account_asset_report_xls.py:741:9: F841 local variable 'fy_end_total_formula' is assigned to but never used

./account_asset_management_xls/report/account_asset_report_xls.py:746:9: F841 local variable 'fy_diff_formula' is assigned to but never used

./account_asset_management_xls/report/account_asset_report_xls.py:747:9: F841 local variable 'total_depr_formula' is assigned to but never used

./account_asset_management_xls/report/account_asset_report_xls.py:805:13: F841 local variable 'account_pos' is assigned to but never used

./account_asset_management_xls/report/account_asset_report_xls.py:841:17: F841 local variable 'asset_formula' is assigned to but never used

./account_asset_management_xls/report/account_asset_report_xls.py:845:17: F841 local variable 'salvage_formula' is assigned to but never used

./account_asset_management_xls/report/account_asset_report_xls.py:864:9: F841 local variable 'asset_total_formula' is assigned to but never used

./account_asset_management_xls/report/account_asset_report_xls.py:865:9: F841 local variable 'salvage_total_formula' is assigned to but never used

./account_asset_management_xls/report/account_asset_report_xls.py:879:9: F841 local variable 'wl_act' is assigned to but never used

./account_asset_management_xls/report/account_asset_report_xls.py:880:9: F841 local variable 'wl_rem' is assigned to but never used

./account_asset_management_xls/report/account_asset_report_xls.py:884:9: F841 local variable '_' is assigned to but never used
```

And
`You try to install module 'account_asset_management_xls' that depends on module 'report_xls'.\nBut the latter module is not available in your system`

**Comment by luc-demeyer** [comment]
Lorenzo,

I have submitted a while ago several PR’s at the same time in order to get three modules in two different github repos for three Odoo versions (6.1, 7.0, 8.0). 

In order to have a consistent set of working modules, I needed ‘report_xls’ into the reporting engines repo and the ‘account_asset_management’ and ‘account_asset_management_xls’ modules in the account financial tools repo. 

After travis issues on all PR’s, I decided to go a bit slower and focus first on the v7.0 PR’s (Frederic from C2C needs those modules for a customer project). 

I made some progress (the V7.0 ‘report_xls’ got merged in the meanwhile into the V7 reporting engines branch).

I also fixed the flake8 issues for V7 and made a new commit (# 51) for this about two weeks ago now. 

There is still a Travis error, but this one seems more like an issue with the tooling used to run the Travis test hence I need some help to get this module pass the test.

Can you have a look at travis buld #51 (cf. https://travis-ci.org/OCA/account-financial-tools/jobs/37104681).

As soon as the V7 PR passes the tests, I’ll redo the PR’s for the 8.0 and 6.1 branches and hence the  #52 issues reported in your e-mail below will be solved.

Regards,

Luc

 http://www.noviat.com/ www.noviat.com

Rusatiralaan 1, 1083 Brussel

+32 2 808 86 38

**Comment by sbidoul** [comment]
@luc-demeyer can you add [8.0] in the pull request title?

**Comment by luc-demeyer** [comment]
@pedrobaeza 
Can you help me to solve the merge conflict ? I have added the reporting engine to travis but I don't know how I can force the travis tests to run again.

**Comment by pedrobaeza** [comment]
Hi, @luc-demeyer. First, you need to rebase you PR, because there has been some changes on the repo that avoids to make the merge. Then, Travis will test it automatically.

**Comment by luc-demeyer** [comment]
@pedrobaeza Thanks for the help. The Travis build now did run correctly.

**Comment by sbidoul** [comment]
Writing a :-1: as this PR must not be merged as is. First #51 must be merged, then 7.0 must be merged in 8.0 and the 8.0 migration commit has to be applied. This is important to preserve a clean merge behaviour between 7.0 and 8.0.

**Comment by rdeheele** [comment]
@luc-demeyer we're currently checking the mysterious error with pytz, this error only occurs with odoo repo. The OCB repo doesn't fail on this problem, it shows tests errors that we could review now.

**Comment by pedrobaeza** [comment]
All repos has been experimenting the same problem, but it seems that now is fixed. It has been a glitch from Odoo that was propagated then to OCB, and remove in the same order.

**Comment by rdeheele** [comment]
hi @luc-demeyer , I've just submitted a PR on your branch to successfully pass the tests.

**Comment by rdeheele** [comment]
:+1: 
we can ignore travis about lint check, it concerns other addons following the new 1.6 pep8 releas, see https://github.com/OCA/maintainer-quality-tools/issues/164

**Comment by lepistone** [comment]
I restarted the lint build, it should be green now.

**Comment by lepistone** [comment]
:triangular_flag_on_post: the code should be OK now, but probably what @sbidoul said on 13 December has not been addressed. This branch is still not started from the 7.0 version of the module that has now been forward-ported to 8.0. The commits are different, and there is a big one: 8be154ba that copies everything on 7.0 but it is not a merge.

I think @sbidoul is right, and this situation will give many conflicts the next time we merge 7.0 to 8.0.

Can anyone try to to this rebase somewhat, and fix the situation?

**Comment by sbidoul** [comment]
@lepistone If you want I can do the merge of 7.0 into 8.0 tonight (I'm used to it) and set asset_management to uninstallable.

Then someone else can apply to change to bring asset management to 8.0.

**Comment by lepistone** [comment]
@sbidoul I just made #144 :smile_cat: 

Once that is merged, we can `git rebase -X ours` this branch against 8.0 and it should work (I tried locally).

**Comment by lepistone** [comment]
Superseded by #145.

**Pull request closed without merging**
