### PR TITLE
[12.0][IMP] account_move_budget: Add analytic tags

### PR DESCRIPTION
**Pull request by grindtildeath**

### CODE REVIEW

**Comment by grindtildeath** [comment]
ping @HviorForgeFlow @JordiBForgeFlow :wink:

**Review by vrenaville — APPROVED** [review]

**Review by Tonow-c2c — APPROVED** [review]

**Comment by HviorForgeFlow** [comment]
Nice feature, I opened a PR to fix linting here: https://github.com/OCA/account-financial-tools/pull/930
I hope we can get rid of conflicts an merge it soon.
Thanks,

**Comment by MiquelRForgeFlow** [comment]
https://github.com/OCA/account-financial-tools/pull/930 is merged. @grindtildeath could you rebase?

**Comment by grindtildeath** [comment]
@MiquelRForgeFlow Done ;)

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
@grindtildeath please, could you forward port this PR to v13?

**Comment by cvinh** [comment]
Hello
analytic_tags are added in v13 here https://github.com/OCA/account-financial-tools/pull/1102
Best Regards

**Pull request merged**
