### PR TITLE
[11.0] [MIG] Migrate account_fiscal_month  to 11.0

### PR DESCRIPTION
**Pull request by feketemihai**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please check Travis

**Comment by feketemihai** [comment]
It's from v11 error about demo tax names.

**Comment by pedrobaeza** [comment]
Yeah, I have seen... You can rebase now.

**Comment by feketemihai** [comment]
Depends on https://github.com/OCA/server-ux/pull/9 for full coverage, unlink is not threated on date_range module.

**Comment by kittiu** [comment]
@feketemihai anything need to make this merged? Seem, if this one merged, the account_move_fiscal_month will pass too.

**Comment by quentingigon** [comment]
Will this be eventually merged or ?

**Comment by AaronHForgeFlow** [comment]
Closed as superseded. Thanks to all.

**Pull request closed without merging**
