### PR TITLE
[11.0] [MIG] Migrate module account_lock_date_update to 11.0

### PR DESCRIPTION
**Pull request by feketemihai**

### CODE REVIEW

**Comment by feketemihai** [comment]
@astirpe First PR to lockings...

**Comment by feketemihai** [comment]
account_lock_date_update #551

**Comment by jholze** [comment]
@pedrobaeza Possible that you check ? We want to use it but better when the ticket is merged.

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please squash your 3 commits

**Review by rafaelbn — APPROVED** [review]
:+1:  Thanks!

**Review by carlosdauden — APPROVED** [review]

**Pull request merged**
