### PR TITLE
[13.0][fix][account_asset_management] support multi-company + navigation improvement

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
This PR also adds a button to allow the navigation from the vendor bill to the associated assets.
image

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Shouldn't that be done at field level instead of view level? Isn't there a facility from Odoo to do it automatically?

**Comment by JordiBForgeFlow** [comment]
@pedrobaeza agreed, and fixed.

**Comment by JordiBForgeFlow** [comment]
@MateuGForgeFlow @DavidBForgeFlow can you review?

**Comment by pedrobaeza** [comment]
Travis is red. Can you check?

**Comment by DavidBForgeFlow** [comment]
@JordiBForgeFlow @pedrobaeza @MateuGForgeFlow I can check it.

**Comment by MiquelRForgeFlow** [comment]
You have to run pre-commit

**Comment by MiquelRForgeFlow** [comment]
@pedrobaeza travis is green

**Review by pedrobaeza — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Review by etobella — APPROVED** [review]
LGTM :+1: Pre-commit is complaining, can you review?

**Pull request merged**
