### PR TITLE
[11.0][add][account_tax_note]

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
This module adds a note to taxes, that is then displayed in the footer
of invoices. This kind of note is frequenly a requirements to appear in
invoices.

For example, in the EU exempt transactions require to add to the invoice
a reference to the appropiate (EU or national) legislation exempting it.
See https://ec.europa.eu/taxation_customs/business/vat/eu-vat-rules-topic/vat-invoicing-rules_en

If you maintain taxes using tax templates, you can update the note in the tax
template. Otherwise you can update it directly in the tax.

Use the OCA module `account_chart_update <https://github.com/OCA/account-financial-tools/blob/11.0/account_chart_update/README.rst>`_
if you want to update the taxes based on the changes made to the templates.

image

image

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I remember a similar module from Acsone. @sbidoul can you tell us?

**Comment by sbidoul** [comment]
Yes, here it is: https://github.com/OCA/account-invoicing/pull/411

**Comment by JordiBForgeFlow** [comment]
@sbidoul thanks. Will review

**Comment by JordiBForgeFlow** [comment]
Thanks @sbidoul! Reviewed your module and LGTM!

**Comment by fclementic2c** [comment]
Anyway... we can handle this kind of notes with the fiscal position, can't you ?

**Comment by JordiBForgeFlow** [comment]
@fclementic2c There are notes that are very specific to the tax being used. Therefore the fiscal position is not always suitable.

**Pull request closed without merging**
