### PR TITLE
[ADD] account_asset_depr_line_cancel

### PR DESCRIPTION
**Pull request by pedrobaeza**
# 
# Cancel button on account asset depreciation line

This module adds an icon to allow to remove the depreciation journal entry
created by each asset depreciation line.
# Usage

On each depreciation line that has created a journal entry, you have a new
button with a white cross in a red circle that allows to remove that entry.

### CODE REVIEW

**Comment by luc-demeyer** [comment]
why trying to fix the standard 'account_asset' module when this is already done in the OCA 'account_asset_management module ?

**Comment by pedrobaeza** [comment]
I'm not fixing it. I'm extending it. And I already said the why: I don't like _account_asset_management_ module, and I'm not going to compromise the migration path for my customers installing that module. Another PR that I'm going to make is for making the disposal of assets based on your code (and crediting you of course), but extending the standard one.

**Comment by pedrobaeza** [comment]
Can anyone review this PR?

**Comment by antespi** [comment]
:+1: Works fine in my local instance

**Comment by pedrobaeza** [comment]
cc @Tecnativa

**Comment by rafaelbn** [comment]
Runbot says:

```
2016-07-21 23:48:31     CRITICAL    server  openerp.service.server:949 preload_registries

Failed to initialize database `3150924-324-f959cd-all`.
Traceback (most recent call last):
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150924-324-f959cd/openerp/service/server.py", line 936, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150924-324-f959cd/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150924-324-f959cd/openerp/modules/loading.py", line 354, in load_modules
    loaded_modules, update_module)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150924-324-f959cd/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150924-324-f959cd/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150924-324-f959cd/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150924-324-f959cd/openerp/tools/convert.py", line 900, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150924-324-f959cd/openerp/tools/convert.py", line 986, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150924-324-f959cd/openerp/tools/convert.py", line 852, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150924-324-f959cd/openerp/tools/convert.py", line 762, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150924-324-f959cd/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150924-324-f959cd/openerp/addons/base/ir/ir_model.py", line 1066, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150924-324-f959cd/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150924-324-f959cd/openerp/addons/base/ir/ir_ui_view.py", line 257, in create
    context=context)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150924-324-f959cd/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150924-324-f959cd/openerp/api.py", line 372, in old_api
    result = method(recs, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150924-324-f959cd/openerp/addons/connector/producer.py", line 48, in create
    record_id = create_original(self, vals)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150924-324-f959cd/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150924-324-f959cd/openerp/models.py", line 4122, in create
    record = self.browse(self._create(old_vals))
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150924-324-f959cd/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150924-324-f959cd/openerp/api.py", line 508, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150924-324-f959cd/openerp/models.py", line 4319, in _create
    recs._validate_fields(vals)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150924-324-f959cd/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150924-324-f959cd/openerp/models.py", line 1271, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "ValidateError
Field(s) `arch` failed against a constraint: Invalid view definition

Error details:
Field `sequence` does not exist

Error context:
View `Account Asset Form (cancel button)`
[view_id: 664, xml_id: n/a, model: account.asset.asset, parent_id: 551]" while parsing /srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3150924-324-f959cd/openerp/addons/account_asset_depr_line_cancel/views/account_asset_asset_view.xml:3, near
<record model="ir.ui.view" id="view_account_asset_asset_form">
            <field name="name">Account Asset Form (cancel button)</field>
            <field name="model">account.asset.asset</field>
            <field name="inherit_id" ref="account_asset.view_account_asset_asset_form"/>
            <field name="arch" type="xml">
                <button name="create_move" position="after">
                    <field name="move_id" invisible="1"/>
                    <button name="unlink_move" icon="gtk-cancel" string="Delete Move" type="object" confirm="Are you sure?" groups="account.group_account_manager" attrs="{'invisible': [('move_check', '=', False)]}"/>
                </button>
            </field>
        </record>
```

**Comment by carlosdauden** [comment]
@pedrobaeza, can you review runbot error?
I don't understand `sequence` field problem

**Comment by rafaelbn** [comment]
Please change label needs review by needs fixing

**Comment by pedrobaeza** [comment]
This module doesn't have any problem.

**Comment by rafaelbn** [comment]
Runbot said https://github.com/OCA/account-financial-tools/pull/324#issuecomment-234420537

**Comment by pedrobaeza** [comment]
OK, I'll check, but Travis would complain also.

**Review by luismontalba — APPROVED** [review]
Tested on runbot

**Comment by luismontalba** [comment]
After creating move:
seleccion_001

After deleting move:
seleccion_002

**Review by rafaelbn — APPROVED** [review]

**Pull request merged**
