### PR TITLE
[8.0] ADD module change_period_onchange_date_move

### PR DESCRIPTION
**Pull request by drl9319**
This module change the period when a date is change in account move.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Several things:

- Call this module account_invoice_date_period_sync that follows conventions and reflect the purpose of it.
- Propose it on account-invoicing, not here.

**Comment by drl9319** [comment]
I take note of that. I Close this PR.
Tranks.

**Comment by sbidoul** [comment]
@pedrobaeza this module works on account move, not invoice. Why account-invoicing?

**Comment by pedrobaeza** [comment]
Ouch, my bad. I saw this for account invoice. Really sorry

**Comment by drl9319** [comment]
So I merge again the module from account-invoicing to account-financial_tools ?

**Comment by pedrobaeza** [comment]
You can reopen the PR. Sorry again. About the name, I still suggest to change it (in this case) to account_move_date_period_sync.

**Pull request closed without merging**
