### PR TITLE
[FIX][account_credit_control] Use HTML field instead of use a replace in the mail template - fix transiflex

### PR DESCRIPTION
**Pull request by adrienpeiffer**

### CODE REVIEW

**Comment by adrienpeiffer** [comment]
Fix #254

**Comment by pedrobaeza** [comment]
Thanks :+1:

**Comment by pedrobaeza** [comment]
cc @guewen

**Comment by gurneyalex** [comment]
do we need a migration script?

**Comment by guewen** [comment]
@gurneyalex is right, we need a migration script, and the base data (example below) should be changed for it is displayed on one line now.

``` xml
       <field name="custom_mail_text">Our records indicate that we have not received the payment of the invoices mentioned in the attached document.

 If it has already been sent, please disregard this notice. If not, please proceed with payment within 10 days.

 Thank you in advance for your anticipated cooperation in this matter.

 Best regards
       </field>
```

**Comment by adrienpeiffer** [comment]
@guewen @gurneyalex I added the migration script and modified credit control policy level data. Thanks !

**Comment by guewen** [comment]
Very nice, thanks! :+1:

**Comment by sbidoul** [comment]
:+1: (code review only)

**Pull request merged**
