### PR TITLE
[13.0][ADD]:  account_move_line_purchase_info: script post_install for update references on new column purchase_line_id from stock.move

### PR DESCRIPTION
**Pull request by celm1990**
When install module on database with data, new column is NULL, purpose is FILL column with data

Inspired by https://github.com/OCA/account-financial-tools/blob/13.0/account_move_line_sale_info/hooks.py

### CODE REVIEW

**Comment by celm1990** [comment]
ping @OCA/accounting-maintainers  @AaronHForgeFlow

**Comment by celm1990** [comment]
ping https://github.com/orgs/OCA/teams/accounting-maintainers

**Review by AaronHForgeFlow — APPROVED** [review]
Code review LGTM

**Review by JordiBForgeFlow — APPROVED** [review]

**Pull request merged**
