### PR TITLE
[FIX] account_credit_control: too many attachements in sent emails. closes #559.

### LINKED ISSUE #559: [10.0] account_credit_control too much attachments in emails
I've tested it on the runbot.

1. Create few invoices with different customers
2. Run credit control
3. Select all credit control lines for sending out by email
4. Select all credit control lines and send them by email

**Result excepted**: To get credit control summary attachment per email
**Result observed**: Second email gets attachment from previous credit control lines based on a sequence of emails creation. E.g. if there is 5 credit control lines, 5 line will get totally 5 attachments.

Any ideas?

more_attachments

### PR DESCRIPTION
**Pull request by adrienpeiffer**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please change module version.

**Comment by adrienpeiffer** [comment]
@pedrobaeza My bad ... it's done :smile: (and squashed)

**Review by pedrobaeza — APPROVED** [review]

**Comment by paulius-sladkevicius** [comment]
Tested on the [runbot](http://3307484-560-8d2988.runbot1.odoo-community.org/), works fine. Thanks for a quick fix. :+1:

**Review by pedrobaeza — APPROVED** [review]
Fast-tracking this as it's a tested bug and cherry-picking to v9 as well

**Comment by pedrobaeza** [comment]
Cherry-pick for v9 in https://github.com/OCA/account-financial-tools/commit/1b7f033bca819d9310cc4015e9baa9773e0cc61b

**Pull request merged**
