### PR TITLE
[12.0][IMP] account_asset_management: Add reporting

### PR DESCRIPTION
**Pull request by StefanRijnhart**
Continued from https://github.com/OCA/account-financial-tools/pull/980, originally by @luc-demeyer. Opting to proceed to include the reporting in the asset management module itself which requires adding a new dependency on report_xlsx_helper from OCA/reporting_engine. Compared to the previous PR I have only added some test code to get a green mark from Codecov.

### CODE REVIEW

**Review by luc-demeyer — APPROVED** [review]
Improved unit test, highly appreciated.
Tx,

**Comment by StefanRijnhart** [comment]
Thanks for the swift action! Will port to 14 within the next couple of days.

**Review by marcelsavegnago — APPROVED** [review]

**Comment by luc-demeyer** [comment]
@stefan 
Thanks a lot.
Can you also cherry-pick your unit test improvement into the 13.0 PR for the asset management reporting (https://github.com/OCA/account-financial-tools/pull/982) in order to move the code to 14.0 starting from 13.0 ?

**Comment by StefanRijnhart** [comment]
13.0 is here https://github.com/OCA/account-financial-tools/pull/1123 and 14.0 is here https://github.com/OCA/account-financial-tools/pull/1124.

**Pull request merged**
