### PR TITLE
[MIG][14.0] account_lock_to_date

### PR DESCRIPTION
**Pull request by AntoniRomera**

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
/ocabot migration account_lock_to_date

The pre-commit command does not have its own commit.

**Comment by AntoniRomera** [comment]
> /ocabot migration account_lock_to_date
> 
> The pre-commit command does not have its own commit.

Is it still necessary? The pre-commit is mandatory to pass a PR validation and as it was already integrated in the 13.0 branch, all files will come well formatted.

**Comment by AaronHForgeFlow** [comment]
If the pre-commit command did not change any file then it is ok

**Review by FernandoRomera — APPROVED** [review]
LGTM

**Review by AaronHForgeFlow — APPROVED** [review]
Functional test

**Comment by AntoniRomera** [comment]
@OCA/accounting-maintainers Anyone can merge?

**Pull request merged**
