### PR TITLE
[16.0][MIG] account_spread_cost_revenue

### PR DESCRIPTION
**Pull request by astirpe**
Work in progress...
Depends on https://github.com/OCA/account-financial-tools/pull/1646

@luc-demeyer

### CODE REVIEW

**Review by yung-wang — APPROVED** [review]
Tested, OK

**Review by yung-wang — APPROVED** [review]
Ok, works fine

**Review by Saran440 — APPROVED** [review]
Functional Test :+1:

**Review by bosd — APPROVED** [review]

**Pull request merged**
