### PR TITLE
[10.0][FIX] Fix tests

### PR DESCRIPTION
**Pull request by rousseldenis**
* [x] account_permanent_lock_move_update
* [x] currency_rate_update: Remove Vietnam => move to l10n-vietnam
* [x] account_asset_management: Tests are run in 2020 (leap/bissextile year), so deprecation computation result would be different

### CODE REVIEW

**Comment by rousseldenis** [comment]
@sbidoul @alexis-via @benwillig

**Comment by rousseldenis** [comment]
@luc-demeyer The tests for account_asset_management are run with current year. So, each four years, results would be different. IMHO, tests should use a fix year at each time (with maybe a mock of fields.Datetime.now() for move creation or...). This is a fix for this year, waiting a more permanent one, but fixes 10.0 branch

**Review by astirpe — APPROVED** [review]
Thanks for this.
At this moment branch 10.0 is broken (see travis failure in https://github.com/OCA/account-financial-tools/pull/714 for example), so I hope this PR would be merged soon.

**Review by luc-demeyer — CHANGES_REQUESTED** [review]
changes the computed values looks unacceptable to me.
I propose you change the asset create date from 2020 to 2019.
This is a quick fix that will still work in 2021.

**Comment by AaronHForgeFlow** [comment]
Hi @rousseldenis . Thanks for the fix. Do you plan to attend the comments here?

**Comment by rousseldenis** [comment]
> changes the computed values looks unacceptable to me.
> I propose you change the asset create date from 2020 to 2019.
> This is a quick fix that will still work in 2021.

@luc-demeyer Yes indeed, this was done to show the problem. Could you suggest me the change exactly as I'm not familiar to these domain?

**Comment by AaronHForgeFlow** [comment]
Is am also not familiar with that module. The proposal is to create a date_range in a past year and create the depreciation in that year?

**Comment by MiquelRForgeFlow** [comment]
@luc-demeyer could put your insight here and proceed? For the love in OCA, we should greenify the repo.

**Pull request closed without merging**
