### PR TITLE
[15.0][MIG] account_asset_transfer

### PR DESCRIPTION
**Pull request by TheerayutEncoder**
Standard Migration 15.0 👍

### CODE REVIEW

**Comment by TheerayutEncoder** [comment]
@Saran440 @newtratip 
Could you help review this PR?

**Comment by Saran440** [comment]
@TheerayutEncoder please add test script to cover case.

**Comment by ps-tubtim** [comment]
@TheerayutEncoder Please separate the commits following https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0 and add you to CONTRIBUTORS.rst.

**Review by Saran440 — APPROVED** [review]
LGTM :+1:

**Review by ps-tubtim — APPROVED** [review]

**Comment by Saran440** [comment]
- Add source/dest in asset transfer
Selection_012

**Comment by MiquelRForgeFlow** [comment]
Please cherry-pick https://github.com/OCA/account-financial-tools/commit/dd17cd45735ba6befdc2c06c3cb57743f36ca9e4 (comes from https://github.com/OCA/account-financial-tools/pull/1322)

**Comment by Saran440** [comment]
@MiquelRForgeFlow Hi,
we add it already 8c5195d13e23ffb1f8e993dc5ae182d38a9ff4af

Thank you for your review.

**Review by MiquelRForgeFlow — APPROVED** [review]

**Pull request merged**
