### PR TITLE
[FIX] address layout + remove unuseful term in report

### PR DESCRIPTION
**Pull request by vrenaville**
I have remove term in the report
 that is more efficient to store it in the data in Odoo .

Add the city to the date and rebuilt the address format.

### CODE REVIEW

**Comment by guewen** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by mdietrichc2c** [comment]
:+1:

**Comment by vrenaville** [comment]
Travis failed is not related to my PR

**Pull request merged**
