### PR TITLE
[14.0] [mig] account_reset_chart

### PR DESCRIPTION
**Pull request by dsolanki-initos**

### CODE REVIEW

**Review by fshah-initos — APPROVED** [review]
Code review and functional tests.
Looks good to me.

**Comment by OSevangelist** [comment]
@dsolanki-initos as this module has successfully been tested on v14, would you mind to change the 'installable' flag to True to be able to install that module and reissue this PR ?

**Comment by dsolanki-initos** [comment]
@damdam-s  It would be nice if you can review this PR.

**Comment by dsolanki-initos** [comment]
@yajo Can you please review this PR?

**Comment by dsolanki-initos** [comment]
@HaraldPanten Can you please review this PR?

**Pull request closed without merging**
