### PR TITLE
[15.0][MIG]account_move_line_tax_editable

### PR DESCRIPTION
**Pull request by manuelregidor**
Standard migration.

### CODE REVIEW

**Comment by manuelregidor** [comment]
@HaraldPanten @ValentinVinagre

**Comment by HaraldPanten** [comment]
@manuelregidor could you rebase, please?

**Comment by manuelregidor** [comment]
> @manuelregidor could you rebase, please?

Done!

**Review by HaraldPanten — APPROVED** [review]

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
