### PR TITLE
[16.0][MIG] account_lock_to_date

### PR DESCRIPTION
**Pull request by SirAionTech**
Standard migration.

### CODE REVIEW

**Comment by sbidoul** [comment]
Looks like this is a duplicate of #1655

**Comment by SirAionTech** [comment]
> Looks like this is a duplicate of #1655

Right, I'm sorry I probably didn't find that when I opened this one because it wasn't mentioning the migrated module before https://github.com/OCA/account-financial-tools/pull/1655#event-11459293165, and it is not mentioned in https://github.com/OCA/account-financial-tools/issues/1472.
I have reviewed it and proposed to continue the migration in here.

**Comment by SirAionTech** [comment]
Rebased.

@JordiBForgeFlow @michotm @aaronhforgeflow @NL66278 @MiquelRForgeFlow you worked on this, would you like to have a look?

**Review by AaronHForgeFlow — APPROVED** [review]
Code review :+1:

**Review by PauMAVA — APPROVED** [review]
👍

**Comment by SirAionTech** [comment]
@OCA/accounting-maintainers this has enough reviews, can someone please merge?

**Review by AaronHForgeFlow — APPROVED** [review]
Also functional test

**Comment by SirAionTech** [comment]
> /ocabot merge nobump

Thanks!
After 12 hours still nothing.. Should we try again?

**Pull request merged**
