### PR TITLE
[12.0][IMP] account_asset_management: Add BI report

### PR DESCRIPTION
**Pull request by pedrobaeza**
Following existing Odoo core BI report in v11, for giving such functionality, very interesting for example for knowing future depreciations in an aggregated way.

@Tecnativa TT25451

### CODE REVIEW

**Review by HaraldPanten — APPROVED** [review]
Functional review. LGTM

**Review by victoralmau — APPROVED** [review]
It's fine although in this case some demo data can help to test it faster.

**Comment by pedrobaeza** [comment]
Yes, indeed. I opened #878 for highlighting that.

/ocabot merge minor

**Comment by Honeyxilia** [comment]
Hello! This BI view is quite useful, but is not present in other Odoo versions, from 13.0 to 16.0 - is there any reason or alternative to get a similar BI report ?

**Comment by pedrobaeza** [comment]
@Honeyxilia it was not migrated as now there's the XLS report, but if you consider it useful, you can cherry-pick it to upper versions.

**Pull request merged**
