### PR TITLE
[14.0][ADD] account_asset_compute_batch

### PR DESCRIPTION
**Pull request by kittiu**
This module extend existing "Compute Asset" feature by allowing to create an Compute Asset Batch (record) to track the computation.

Selection_136

Selection_137

### CODE REVIEW

**Review by Saran440 — APPROVED** [review]
Functional Test :+1:

**Review by ps-tubtim — APPROVED** [review]

**Comment by Saran440** [comment]
@kittiu please you check name this PR like a https://github.com/OCA/account-financial-tools/tree/14.0/account_asset_batch_compute

I consider that it will confuse module. What do you think?

**Comment by kittiu** [comment]
> account_asset_batch_compute

For me it is clear.

**Comment by rafaelbn** [comment]
Hello @kittiu this fails due

```
2022-09-30 19:22:04,954 258 ERROR odoo unittest.suite: ERROR: setUpClass (odoo.addons.account_asset_compute_batch.tests.test_account_asset_compute_batch.TestAssetComputeBatch)
Traceback (most recent call last):
  File "/opt/odoo/odoo/tests/common.py", line 173, in _handleClassSetUp
    setUpClass()
  File "/opt/odoo-venv/lib/python3.6/site-packages/freezegun/api.py", line 658, in wrapper
    result = func(*args, **kwargs)
  File "/__w/account-financial-tools/account-financial-tools/account_asset_compute_batch/tests/test_account_asset_compute_batch.py", line 19, in setUpClass
    super().setUpClass()
  File "/__w/account-financial-tools/account-financial-tools/account_asset_management/tests/test_account_asset_management.py", line 21, in setUpClass
    super().setUpClass()
  File "/opt/odoo/addons/account/tests/common.py", line 27, in setUpClass
    assert 'post_install' in cls.test_tags, 'This test requires a CoA to be installed, it should be tagged "post_install"'
AssertionError: This test requires a CoA to be installed, it should be tagged "post_install"
```

**Comment by Saran440** [comment]
@rafaelbn Fixed it. thank you.

**Comment by Saran440** [comment]
@OCA/accounting-maintainers Hi, This pr ready to merge, someone can help merge, please?

**Pull request merged**
