### PR TITLE
[12.0][MIG] account_invoice_currency

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Superseed #800 

CC @Eficent @yweng8111

### CODE REVIEW

**Review by tbaden — CHANGES_REQUESTED** [review]
could you please fix the travis warnings:
************* Module account_invoice_currency
account_invoice_currency/readme/DESCRIPTION.rst:1: [W7908(missing-newline-extrafiles), ]  Missing newline
account_invoice_currency/readme/CONTRIBUTORS.rst:1: [W7908(missing-newline-extrafiles), ]  Missing newline

everything else lgtm

**Review by AdriaGForgeFlow — APPROVED** [review]
LGTM :+1:

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM code review

**Review by TheCloneMaster — APPROVED** [review]
Tested and working perfect !

**Pull request merged**
