### PR TITLE
[12.0][MIG] account_move_fiscal_month

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration of https://github.com/OCA/account-financial-tools/pull/895.

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
:+1:  works as expected.

**Comment by MiquelRForgeFlow** [comment]
Please review @benwillig @feketemihai

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Pull request merged**
