### PR TITLE
[MIG] migration currency_rate_update to 8.0

### PR DESCRIPTION
**Pull request by adrienpeiffer**
There is a problem with onchange in this addons but in my mind, this problem is due to Odoo onchange modificatiton.

### CODE REVIEW

**Comment by adrienpeiffer** [comment]
More precision about onchange problem:
For instance, go to company form view, take currency auto update page and change value of currency update frequence. An exception is directly raised : ValueError: "name 'fax' is not defined" while evaluating
'[custom_footer, phone, fax, email, website, vat, company_registry, bank_ids]'
There is the same problem with other fields that have onchange attribute in this page.

**Comment by nbessi** [comment]
Hello, 
Thanks for the work.
Sadly this addons does not match OCA requirements, and can probably not be migrated as is.
There are some point that need to be fixed when ported to 8:
- [ ] All the cron stuff is deprecated get_cron_id, save_cron this historical code that should be declared in XML
- [ ] There is not a test. Luckily it is an addon really easy to test.
- [ ] The multi company must be treated in a standard way by defining some ir.rules
- [ ] The currency getter should be separated in python module

**Comment by feketemihai** [comment]
@nbessi , @adrienpeiffer I need this module for V8, and i want to help porting it...can you give me more specs about how the multicompany should be done (taking in consideration that when creating the database the currencies doesn't have associated a company..so if we add a new company, a new currency with the same symbol, how we will know which one is applied...) and for separation of the services should we create currency_rate_update_XXX with the name of the service???

**Comment by nbessi** [comment]
@feketemihai thanks for proposing yourself.
For the modules your guesses are correct we want to provide one module per services based on the 
convention of upate_service_xxx.py 

for the multi company, I'm mostly speaking about the updater. We may have an updater per company with different settings. It is correct that from some versions currences are not spearated anymore. 
Each implementation should do the required setup to add missing rules and fields.

Regards

Nicolas

**Comment by feketemihai** [comment]
Hi Nicolas, thanks for spending time replying to me...i made a commit to my fork, available here, 
https://github.com/feketemihai/account-financial-tools
I've update most of the code to new api, the method (BNR_getter for Romania Update is working, i only tested this one, and it's working also the resticted currencies available on the webservice...created new fields to restrict currencies based on the list - now mannualy imputted, but we can do a fecth of all data available on the website and to modify the list). I still need to split it by webservice, and to deal with a better multicompany enviroment. Can i have your opinion: should we create a cron for every company or to have only one cron and to adjust depending on the settings (i prefer this one even that we will have to add some fields for timing computation of days, weeks, months...).

Regards,

Mihai

**Comment by feketemihai** [comment]
@nbessi

**Comment by nbessi** [comment]
@feketemihai I would be nice to make a new PR I will put this one as deprecated.

Regards

Nicolas

**Comment by feketemihai** [comment]
@nbessi I've created a new PR, https://github.com/OCA/account-financial-tools/pull/70

**Comment by nbessi** [comment]
deprecate in favor of  #70

**Pull request closed without merging**
