### PR TITLE
[FIX][account_asset_management] Remove an asset without depreciation line

### PR DESCRIPTION
**Pull request by adrienpeiffer**
Currently, it's not possible to remove an asset without depreciation line.

### CODE REVIEW

**Comment by luc-demeyer** [comment]
when there is no depreciation line, than there shouldn't be an asset either, hence the customer should delete the asset in stead of using the asset removal wizard since in this case the asset will still be visible in the legal reporting (both the acquisition & disposal tabs whereas this case looks rather like a classical purchase and sale operation).

**Comment by sbidoul** [comment]
@luc-demeyer I agree there should not be an asset at all in such case, but...

...with the current code, you cannot delete a draft asset when the corresponding invoice has been validated. Sometimes, people notice too late that there should not have been an asset and they cannot cancel the invoice. So they try to remove the asset, and they get a stack trace.

So this PR provides a workaround to this scenario. 

What alternative approach would you suggest?

**Comment by adrienpeiffer** [comment]
@luc-demeyer What do you think about explanation from @sbidoul

**Comment by luc-demeyer** [comment]
@adrienpeiffer 
cf. https://github.com/OCA/account-financial-tools/pull/306 with an alternative solution for this issue.

**Pull request closed without merging**
