### PR TITLE
9.0 account check deposit

### PR DESCRIPTION
**Pull request by mourad-ehm**
Port module account_check_deposit to 9.0

### CODE REVIEW

**Comment by mslokhat** [comment]
Hi,
tested it on v9. 
the Add button under check payment grid does not appear and therefore i cannot add any check
is it normal?

**Comment by florian-dacosta** [comment]
@mslokhat No it is not normal, I just fixed it.

**Comment by alexis-via** [comment]
The version number has not been updated neither in __openerp__.py nor in README.rst.

**Comment by legalsylvain** [comment]
Hi, 
thanks for porting this module. 
Could you squach your commit from https://github.com/OCA/account-financial-tools/pull/383/commits/180327c679a0f2b6dee03fbd561309a314d86ec1 to https://github.com/OCA/account-financial-tools/pull/383/commits/92218be39441b166aa63cde8685e7a8a64aef25f into a single one ? 
It will be more easy to review.
thanks.

**Comment by mourad-ehm** [comment]
OK. I squash commits.

**Comment by mourad-ehm** [comment]
ping @legalsylvain

**Pull request merged**
