### PR TITLE
[7.0][FIX][account_move_template] fix the default value for the company

### PR DESCRIPTION
**Pull request by giacomos**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please sign the CLA.

About the PR, :+1:

**Comment by tafaRU** [comment]
Thanks :+1:

**Comment by laetitia-gangloff** [comment]
:+1:

**Comment by giacomos** [comment]
@pedrobaeza I did sign the CLA not much time ago and sent it to the provided mailbox, but no response yet.

**Comment by pedrobaeza** [comment]
OK, merging

**Pull request merged**
