### PR TITLE
[14.0][ADD] account_asset_transfer, AUC -> Asset

### PR DESCRIPTION
**Pull request by kittiu**
This module allow transferring assets under construction (AUC) to normal assets.

AUC is Asset under construction where some assets are in construction phase and
cost needs to be captured for the time being. Once asset is fully completed then
cost would be transferred to final asset

Sample workflow can be as following,

1. Assets of class "AUC" (asset with no depre) was created, with analytic "Wood Corner"

Selection_122

2. Confirm assets, now Running.
3. Then at time, we want to transfer them to normal asset. Filter for asset "AUC" for "Wood Corner"

Selection_123

4. Transfer it to new asset profile.
Selection_124
Selection_125

5. This will create Asset Transfer Journal Entry, remove old assets, and create new asset(s)
Selection_126

Selection_127

### CODE REVIEW

**Comment by kittiu** [comment]
cc @hitrosol really love to hear your feedback. Will it works for you?

**Comment by hitrosol** [comment]
Hi @kittiu, I just have chance to try the module in runbot, thanks for this effort.
One of the reason I use AA before this module was to track several Vendor Bills / Expenses / JEs that mould the AUC. 
Since we are going to have the specific module to track the AUC, I think we don't need to use the AA anymore, but we should have the AUC lines to records the Vendor Bills / Expenses / JEs related to that specific AUC. There is possibility also that one AUC will be splited to more than one New Fixed Asset. I'm not sure how this will works, but it's easy to do it manually as I do right now.

**Comment by kittiu** [comment]
@hitrosol yes you can transfer 1 AUC to multiple assets using the transfer wizard.

**Comment by hitrosol** [comment]
LGTM

**Comment by kittiu** [comment]
> LGTM

@hitrosol can you help final review / approve this. Thanks!

**Comment by hitrosol** [comment]
Sorry for late response. Functional review --> Okay.

**Review by hitrosol — APPROVED** [review]

**Review by Saran440 — APPROVED** [review]
Functional Test :+1:

**Comment by Saran440** [comment]
@kittiu I split new function for create move. it's not affect to process.
if it okay please rebase and merge again.

**Comment by ps-tubtim** [comment]
@kittiu I edit the asset profile domain of **To New Asset** tab in commit https://github.com/OCA/account-financial-tools/pull/1232/commits/a3588f4798a2cae511d6713f37cfbfc30a32fbde because there may be a case of transfers to assets that are not depreciated.

**Review by ps-tubtim — APPROVED** [review]

**Pull request merged**
