### PR TITLE
[IMP][account_constraints] Add a method that returns a list of fields  that can be written directly on journal items

### PR DESCRIPTION
**Pull request by adrienpeiffer**
instead of have a static list in _authorized_reconcile method

### CODE REVIEW

**Comment by laetitia-gangloff** [comment]
:+1:

**Comment by sbidoul** [comment]
:+1:

**Comment by moylop260** [comment]
Fix typo `jounral` in commit messsage.
Besides this :+1:

**Comment by adrienpeiffer** [comment]
@moylop260 Done ! Thanks !

**Comment by adrienpeiffer** [comment]
I think this one is ready to merge.

**Pull request merged**
