### PR TITLE
[13.0][IMP] account_chart_update: refactor update taxes

### PR DESCRIPTION
**Pull request by gaikaz**
Superseding: #1056 (Just rebased. Author didn't respond)
Closes: #1202

This adds a way to update tax tags from chart templates.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I'm missing here some tests coverage.

**Comment by pedrobaeza** [comment]
I think the second commit can be put in a separate pull request and be fast-tracked, but the first one, as said, require to add tests to support such changes, as it's a heavy refactoring.

**Comment by gaikaz** [comment]
Ok. Though, @luc-demeyer is the author of both commits.
- I could take the little fix out to separate PR without re-wording, re-authoring or anything.
- In this PR, I would just add another commit for tests and wouldn't want to squash it with luc-demeyer's work.

Would that be ok?

**Comment by pedrobaeza** [comment]
Yes, the plan is OK for me.

**Comment by gaikaz** [comment]
@pedrobaeza 
My colleague @DonatasV was kind enough to help me out with the tests.
Tho, we didn't cover tests for the @luc-demeyer 's `cash basis accounts not handled in 'deferred' mode` changes as we don't seem to use those here in Lithuania.

Would you agree with splitting that part out to another PR as well, so we are only left with the features of tax tag and tax account updating?

**Comment by pedrobaeza** [comment]
Yeah, perfect. The more atomic the changes, the better they can be reviewed.

**Comment by pedrobaeza** [comment]
I'm not able to push to the branch, for moving the new check to the "More options" page, but let's merge it as this has been so long opened and I adjust it later via direct commit:

/ocabot merge major

**Comment by gaikaz** [comment]
Sorry, yes. I got a little busy lately and this got postponed.

**Pull request merged**
