### PR TITLE
[13.0] [IMP] `product_category_tax`: copy taxes when creating products programatically

### PR DESCRIPTION
**Pull request by ivantodorovich**
and some other small improvements: each on its own commit

### CODE REVIEW

**Review by jcoux — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]
Code review LGTM

**Comment by AaronHForgeFlow** [comment]
@ivantodorovich can you check if this needs forwardport?

**Comment by ivantodorovich** [comment]
@AaronHForgeFlow Indeed, I'll take care of forward porting if after it's merged.

@dreispt your ocabot command had a typo. Could you retry please 🙏🏻 ?

**Comment by ivantodorovich** [comment]
Forward ports:
- https://github.com/OCA/account-financial-tools/pull/1457
- https://github.com/OCA/account-financial-tools/pull/1458

**Pull request merged**
