### PR TITLE
[15.0][MIG] account_invoice_constraint_chronology

### PR DESCRIPTION
**Pull request by Shide**
Straight forward migration.

- [x] Added return on the `@api.onchange` method to pass pre-commit
- [x] Changed `SavepointCase` to `TransactionCase` on tests

Please review @Yajo @rafaelbn @HaraldPanten 😄 

MT-455 @moduon

### CODE REVIEW

**Comment by Shide** [comment]
Seems like installing `vatnumber` is failing (for version 1.2 and 1.1) due to [base_vat_optional_vies dependency](https://github.com/OCA/account-financial-tools/blob/2963185516d9b1a6265880989993f95a436bae45/base_vat_optional_vies/__manifest__.py#L11)

Installing `vatnumber` with pip on my machine discards `v1.2` and `v1.1`, falling onto `v1.0`
```
pip install vatnumber
Collecting vatnumber
  Downloading vatnumber-1.2.tar.gz (19 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/eduardo/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vrk6z_42/vatnumber_dfc1096ac71340a296dbdd18671ee685/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vrk6z_42/vatnumber_dfc1096ac71340a296dbdd18671ee685/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-b3bnk0xg
         cwd: /tmp/pip-install-vrk6z_42/vatnumber_dfc1096ac71340a296dbdd18671ee685/
    Complete output (1 lines):
    error in vatnumber setup command: use_2to3 is invalid.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/d7/7c/869b59cd9cb6ed1057372cb704a3b86688ae8c12cfc7fcaedbc1424f5e7f/vatnumber-1.2.tar.gz#sha256=4e9e9cabcff6076d8deb8a347edfd5d0ab8cab1ed344fdbe5dd4a6110a2f2c7b (from https://pypi.org/simple/vatnumber/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading vatnumber-1.1.tar.gz (22 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/eduardo/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vrk6z_42/vatnumber_a71c44053b364b6da662b29160aa60a4/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vrk6z_42/vatnumber_a71c44053b364b6da662b29160aa60a4/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-vdrrcew8
         cwd: /tmp/pip-install-vrk6z_42/vatnumber_a71c44053b364b6da662b29160aa60a4/
    Complete output (1 lines):
    error in vatnumber setup command: use_2to3 is invalid.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/1f/77/18485f3f4bdcec93004a3eac639565eb21e4a556b9d16a5687b735a02498/vatnumber-1.1.tar.gz#sha256=ff7017420e137609a74ce0dbe6ba16c86ea5317d50ca398f8f423141c07fae18 (from https://pypi.org/simple/vatnumber/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading vatnumber-1.0.tar.gz (21 kB)
Building wheels for collected packages: vatnumber
  Building wheel for vatnumber (setup.py) ... done
  Created wheel for vatnumber: filename=vatnumber-1.0-py3-none-any.whl size=20265 sha256=8e8684a96810443f653c00a2ba21aa8b9ac624548e682c859d0ee83c21802669
  Stored in directory: /home/eduardo/.cache/pip/wheels/4d/27/32/6d4e8da4f5a851bf0486a9dcc4ea3dc11fee12f9502eaba950
Successfully built vatnumber
Installing collected packages: vatnumber
Successfully installed vatnumber-1.0

```
Same error than runboat trying to install `vatnumber` from pip, but in my case, pip fallbacks well.

**Comment by rafaelbn** [comment]
@sbidoul please could you take a quick look on https://github.com/OCA/account-financial-tools/pull/1360#issuecomment-1075340836 about PIP and `vatnumber`

Thank you!

**Comment by sbidoul** [comment]
vatnumber is unmaintained and does not install with the last setuptools. Odoo does not use it anymore, we must find a replacement too.

**Comment by Shide** [comment]
@sbidoul Any chances to allow pip to fallaback to older versions on Runboat?
This will unlock migrations not related directly or indirectly to modules that has external dependencies such vatnumber.

**Comment by sbidoul** [comment]
@Shide actually setuptools is [already](https://github.com/OCA/oca-ci/blob/95eced5b7669eaadc2477f509fea54e5d8087f23/.github/workflows/ci.yaml#L38) [constrained](https://github.com/OCA/oca-ci/blob/95eced5b7669eaadc2477f509fea54e5d8087f23/.github/workflows/ci.yaml#L43) for older Odoo branches for that same reason. Since for these, it is an Odoo dependency which we can't change, there is no other solution.

Here, 
1/ we have control on the use of that unmaintained dependency, so we can replace it
2/ actually I don't even see where it is imported in this repo: base_vat_optional_vies declares the dependency but does not seem to use it, so maybe it's simply a migration oversight
3/ I'm not keen to pin setuptools for more recent Odoo versions because it will certainly create problems down the line if there are dependencies that themselves require a recent setuptools

**Review by yajo — APPROVED** [review]

**Comment by yajo** [comment]
I pushed the fix for the vatnumber problem. Let's see now. Regarding the PR itself, it looks good to me.

**Review by rafaelbn — APPROVED** [review]
Functional 👍

**Comment by yajo** [comment]
Rebased, to see if that fixes the build.

**Comment by yajo** [comment]
Please @Shide review test failures.

**Comment by Shide** [comment]
> Please @Shide review test failures.

Done, thanks! :)

**Pull request merged**
