### PR TITLE
[IMP][account_credit_control] Minimal Danish translation

### PR DESCRIPTION
**Pull request by andrius-preimantas**
Basically initial translation for Danish language

### CODE REVIEW

**Comment by pedrobaeza** [comment]
There's no translation...

**Comment by andrius-preimantas** [comment]
https://github.com/andrius-preimantas/account-financial-tools/commit/9d3d9abbe9f60118c36f5407355e6643e640790d#diff-0063e1c4717d5018e958af0467f6865cR527

Only the printed report was translated. It's better than nothing. Hopefully I'll be able to manage full translation soon.

Cheers

**Comment by pedrobaeza** [comment]
I ask you then to wait, because we are going to integrate on-line translations via Transifex very soon.

**Comment by dreispt** [comment]
@pedrobaeza Is there any downside of merging this now?

**Comment by pedrobaeza** [comment]
Well, I don't think so.

**Comment by andrius-preimantas** [comment]
@pedrobaeza , I understand that's way too little, but my client asked for that much so I've thought to share it with the community. If there's not a big problem then It'd be very helpful if it was merged to upstream OCA code...

Cheers

**Comment by pedrobaeza** [comment]
OK then :+1:

**Comment by dreispt** [comment]
Even if small, every step in the right direction is valueable  :+1:

**Comment by yvaucher** [comment]
Ok let's merge it as a first step.
Thanks @andrius-preimantas

**Pull request merged**
