### PR TITLE
[12.0][IMP]account_move_template: Archive templates

### PR DESCRIPTION
**Pull request by manuelregidor**
Account move templates can be archived.

### CODE REVIEW

**Review by HaraldPanten — APPROVED** [review]
LGTM.

@pedrobaeza could we fast-tracking this one, plz?

**Comment by HaraldPanten** [comment]
@pedrobaeza do you know why this PR was merged and closed instead of merged? 🤔

**Comment by pedrobaeza** [comment]
OCABot mysteries...

**Pull request closed without merging**
