### PR TITLE
add .mailmap to fix authors for git-shortlog

### PR DESCRIPTION
**Pull request by yvaucher**

### CODE REVIEW

**Comment by gurneyalex** [comment]
:+1;

**Comment by lepistone** [comment]
Thanks @yvaucher. Why my email `leonardo.pistoner@camptocamp.com`? Was it used somewhere by mistake?

**Comment by omar7r** [comment]
:+1:

**Comment by yvaucher** [comment]
@lepistone this was certainly a typo from a commiter setting bzr --author parameter
I only saw this in this repo yet

**Comment by lepistone** [comment]
thanks! :+1:

**Pull request merged**
