### PR TITLE
[13.0][FIX] stock_account_prepare_anglo_saxon_out_lines_hook: update hook

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Include https://github.com/odoo/odoo/pull/81348.

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
Fast tracking as merged in Odoo core

/ocabot merge patch

**Comment by AaronHForgeFlow** [comment]
Sorry, I was wrong. This is not merged in the core yet. Let's wait until that.

**Comment by AaronHForgeFlow** [comment]
finally, merged in core, so merging here:

/ocabot merge patch

**Comment by AaronHForgeFlow** [comment]
@MiquelRForgeFlow Could you forwardport this to 14.0?

**Comment by MiquelRForgeFlow** [comment]
Of course, when odoo merges the FWport haha

**Comment by MiquelRForgeFlow** [comment]
Done in https://github.com/OCA/account-financial-tools/pull/1296.

**Comment by AaronHForgeFlow** [comment]
please /ocabot merge patch

**Pull request merged**
