### PR TITLE
[15.0][MIG] account_lock_date_update

### PR DESCRIPTION
**Pull request by Shide**
Standard migration

@rafaelbn @Yajo 

MT-515 @moduon

### CODE REVIEW

**Comment by rafaelbn** [comment]
I cannot test it in runboat , could you please check? Thanks

**Comment by yajo** [comment]
Please rebase to get https://github.com/OCA/account-financial-tools/commit/7a467d7cbeb09567a8e0f22b787281d5dfb4b3e5 and fix the build.

**Review by yajo — APPROVED** [review]

**Comment by Shide** [comment]
@rafaelbn done

**Review by rafaelbn — APPROVED** [review]
Tested in runboat 👍

**Pull request merged**
