### PR TITLE
8.0 account_credit_control: small code cleanup in views

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Comment by sebnege** [comment]
:+1: using this patch in production, works fine

**Comment by jbaudoux** [comment]
:+1: Here is an additional improvement to merge in your PR:
https://github.com/akretion/account-financial-tools/pull/3

**Comment by alexis-via** [comment]
Travis error is completely unrelated (it breaks in account_asset_management). So this can be merged.

**Comment by alexis-via** [comment]
rebased

**Comment by sbidoul** [comment]
:+1:

**Pull request merged**
