### PR TITLE
[FIX] migration of a table already renamed

### PR DESCRIPTION
**Pull request by sergiocorato**
I'm testing it in a migration.

### CODE REVIEW

**Comment by sergiocorato** [comment]
I confirm it works, errors in Travis seems unrelated.

**Comment by StefanRijnhart** [comment]
Can you point out where the table was migrated earlier?

**Comment by sergiocorato** [comment]
> Can you point out where the table was migrated earlier?

Sorry @StefanRijnhart I missed your comment. In v. 10 [here](https://github.com/OCA/account-financial-tools/blob/03138c4f05cf6c3c4355b0c0d2834d1c4bccca78/account_credit_control/models/credit_control_run.py#L30..L31) the table is already named with the new name, same for the columns.

**Comment by StefanRijnhart** [comment]
I see. Looks like one of @pedrobaeza's unreviewed, direct commits (https://github.com/OCA/account-financial-tools/commit/4c0f16ee6206a537f2bb430266f77f4a4297caa1#diff-1633f3dbad039ab002790f591fd7df512b84a9234d912830f39babc49e4de85e).

**Review by StefanRijnhart — APPROVED** [review]
Travis error is unrelated indeed.

**Comment by pedrobaeza** [comment]
Migration script is correct. The real renaming happens from 10.0 to 11.0. The problem is that `rel` is not the proper attribute for new ORM field declaration:

https://github.com/odoo/odoo/blob/10.0/odoo/fields.py#L2313

It's `relation`, and so, that attributes in v10 does mean nothing, but on v11, the attributes were properly renamed, and then it's when this is acting and makes sense. Please review why you have your table already renamed in previous versions (maybe a fork of the OCA module with that attributes names fixed).

**Comment by StefanRijnhart** [comment]
Ah good one @pedrobaeza. Sorry I missed that.

**Comment by pedrobaeza** [comment]
I have unveiled the problem behind this, and it's when you are migrating from < 10.0 (8.0, 9.0...) with this module installed. Up to v10, old and new API were co-living, and `rel`, `col1` and `col2` were accepted through old API although the field definition was in new API, so the table name was actually `credit_run_policy_rel`. But on v10, with the removal of the old API, standard m2m table names were applied. Thus, I have pushed 1c64e6d8470aa4fdf57fed6a04fb344f8aa67374 and aa5ef85f04f6256309066e0392370d953355ff9d for fixing the migration chain and avoid confusions.

**Comment by sergiocorato** [comment]
@pedrobaeza thanks very much for going deeper

**Pull request closed without merging**
