### PR TITLE
[10.0][CHG] account_credit_control:  invoices numbers helper field

### PR DESCRIPTION
**Pull request by RobinetDenisAcsone**
This pr add a helper field `invoices_numbers`, which is the list of the invoice number separated by commas.
This field can be used in the reminder mail with `${object.invoices_numbers}`

### CODE REVIEW

**Review by sbidoul — APPROVED** [review]
LGTM

**Review by nishaodedra — APPROVED** [review]

**Review by Olivier-LAURENT — APPROVED** [review]
Thx !

**Pull request closed without merging**
