### PR TITLE
[13.0][IMP] product_category_tax: prevent write when onchange is triggered

### PR DESCRIPTION
**Pull request by JordiMForgeFlow**

### CODE REVIEW

**Comment by JordiMForgeFlow** [comment]
Hi @ivantodorovich 

We had a small issue due to the write being triggered before the record of the product is actually created, as we are doing some validations in the write method. Do you see a problem preventing the write in the onchange?

**Review by GuillemCForgeFlow — APPROVED** [review]
LGTM! :+1:

**Review by ivantodorovich — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]
LGTM

**Pull request merged**
