### PR TITLE
[12.0][FIX] account_asset_management: Don't depend on account.fiscal.year created records

### PR DESCRIPTION
**Pull request by pedrobaeza**
* There's no need of forcing to create such records if your fiscal years are regular ones.
* FY date range computation duplicates code that is already on core.
* DummyFY is a good idea, but was not used at all. Now it is.

cc @Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Tests have passed, so this proves the change is transparent and pretty good :wink:

**Comment by pedrobaeza** [comment]
I have needed to directly push a hook for being able to continue adapting `l10n_es_account_asset` in 85a305dfe0e3893bb9db25289e2209431dc3d5c3, or I will be totally blocked due to incorrect non inheritable code. I hope you don't mind. Rebasing this one over new main branch.

**Review by grindtildeath — COMMENTED** [review]
LGTM :+1: 
@luc-demeyer Can you give this a look ?

**Review by grindtildeath — APPROVED** [review]

**Comment by luc-demeyer** [comment]
@pedrobaeza @grindtildeath 
Code review & testing ok.
Less code, better readability: a nice job, please merge this one asap.

While reviewing this PR I also reviewed a previous one:
[FIX] account_asset_management: Provide hook _compute_depreciation_amount_per_fiscal_year
commit 85a305dfe0e3893bb9db25289e2209431dc3d5c3
and remarked the comments in the PR about the undefined 'number' method.
The methods 'number' and 'end' are coming with the 'account_asset_management_number_end' module (cf. PR https://github.com/OCA/account-financial-tools/pull/704).
@grindtildeath : I think we should greenify this one and merge it so that we can forward port this module to 12.0 (and also backport commit 85a305dfe0e3893bb9db25289e2209431dc3d5c3). A cherry-pick of this commit for 11.0 should do the job.

**Review by luc-demeyer — APPROVED** [review]

**Comment by pedrobaeza** [comment]
While analyzing the code for migrating `l10n_es_account_asset`, I see some inconsistencies in the module for the multiple `method_time` values:

* Main module is supposed to only support computation by years, but at the end, there's lot of code here mentioning the other methods.
* Why doing different depreciation computations depending on `method_time`. For me, important things are depreciation starting date, and depreciation stop date. The rest of the computations must be the same depending on these 2 data. In fact, in `l10n_es_account_asset`, I have needed to compute properly stop date:

  https://github.com/OCA/l10n-spain/pull/1166/files#diff-b2f263a1a1799d31829a83fea1626d32R59

  and then simulate that this is depreciation by years:

  https://github.com/OCA/l10n-spain/pull/1166/files#diff-b2f263a1a1799d31829a83fea1626d32R111

* For `method_time` = 'end' or 'number', only linear depreciation is allowed. Why? You can have a regressive computation while specifying a number of depreciations. Doing what I say on second point you will have it properly.
* If so, there's not too much sense on splitting the module in 2, but well, if so, the second one will be very light (the same as `l10n_es_account_asset` if we do it).

I can work on this if you think it's interesting. I can also extract this on an issue if you prefer.

For now, merging this!

/ocabot merge patch

**Comment by luc-demeyer** [comment]
@pedrobaeza 
concerning method number & end: 
I prefer that you open an issue so that we first discuss the functional aspect in the community before starting implementation.

**Pull request closed without merging**
