### PR TITLE
[14.0][ADD] account_reconcile_show_boolean

### PR DESCRIPTION
**Pull request by remi-filament**
Today, it is not possible to create reconciliable payable/receivable from partner.
The issue was raised here : https://github.com/odoo/odoo/issues/80775 and a proposal was made to update Odoo here : https://github.com/odoo/odoo/pull/80778

The answer from Odoo was:  
Hi, we close this PR since Reconciliation is an Accounting feature, not an Invoicing one.
(https://github.com/odoo/odoo/pull/80778#issuecomment-985637427)

Therefore I create a PR because we really need this feature in community version.
I was not sure whether it should go here, or to account-reconcile or partner-contact repo, let me know if you think it should go somewhere else !

### CODE REVIEW

**Review by rafaelbn — APPROVED** [review]
Thanks @remi-filament . Please could you rebase to check all is Ok after all this time? 👍

**Comment by rafaelbn** [comment]
Dear @legalsylvain do you have a little time for this one? 😄

**Comment by remi-filament** [comment]
@rafaelbn done, thanks for looking into it !

**Comment by legalsylvain** [comment]
hi. 
1) LGTM.
2) a pity to have this code out of odoo core ...
3) not very confortable with the name of the module. I'd like to see ``partner_form`` or something like that in the name of the module, because it is the only purpose of this module (but I have no clear alternative to propose). not a blocking point though.

**Comment by AaronHForgeFlow** [comment]
LGTM! Decide the name is not easy here, could be like "res_partner_form_account_reconcilable" but I don't like that one either

**Review by jordancoest — APPROVED** [review]

**Review by JulianaPoudou — APPROVED** [review]

**Comment by dreispt** [comment]
I may be late to the party here, but module names should start with the main app they relate to.
So I think the name should be something like `account_reconcile_partner`.

**Comment by remi-filament** [comment]
Hi @dreispt, Fine with me but then we may not even name it after partner since it modifies account.account form view to display.
Would account_reconcile_boolean be OK with you, since we only display the "Allow Reconciliation" boolean in for view ?

**Comment by dreispt** [comment]
Hi @remi-filament, I used “partner” because that is the name proposed by the PR author.
My big concern is that the module name should start with the main app dependency “account”.

**Comment by remi-filament** [comment]
Hi @dreispt , since I am the author of the PR, I would then go with `account_reconcile_show_boolean`

**Review by JulianaPoudou — APPROVED** [review]

**Comment by rafaelbn** [comment]
@dreispt please i think this could be merged 😄

**Pull request merged**
