### PR TITLE
[14.0][ENH] account_asset_transfer: add feature expand asset line

### PR DESCRIPTION
**Pull request by ps-tubtim**
This module adds a feature to expand the asset line on the transfer wizard.

**Note:** The system just helps to expand the line that selects the asset profile set to be "Create an asset by product item".

**Wizard**
Selection_124

**Example**
expand_asset

### CODE REVIEW

**Comment by kittiu** [comment]
Since this is a small enhance. Should this be included in account_asset_transfer

**Comment by ps-tubtim** [comment]
@kittiu I already updated this pull request.

**Review by Saran440 — APPROVED** [review]
Functional Test :+1:  and add test script

**Review by kittiu — APPROVED** [review]

**Pull request merged**
