### PR TITLE
8.0 workaround bug #151 and fixes the cron

### PR DESCRIPTION
**Pull request by alexis-via**
This PR provides a workaround on bug #151 
The advantage of this solution is that it also gives a menu entry to the accountant, so that he can see and change the configuration.
This PR also fixes a crash in the method called by the cron
It also provides additionnal log message, to have a better view on what happens.

### CODE REVIEW

**Comment by alexis-via** [comment]
and it also adds a record rule for the currency rate update service object

**Comment by guewen** [comment]
:+1:

**Comment by brother-bernard** [comment]
:+1:

**Comment by bguillot** [comment]
:+1:

**Comment by sbidoul** [comment]
2 technical and one functional approval so I merge.

**Pull request merged**
