### PR TITLE
[IMP] account_loan: Add fixed-annuity-begin

### PR DESCRIPTION
**Pull request by etobella**
with this PR, the computation of a fixed annuity computed at the begining of the period is added.

@jbeficent

### CODE REVIEW

**Comment by jarroyomorales** [comment]
@etobella I just re ran the runbot and its green now. It would also be great to increase coverage if possible :wink:

**Review by JordiBForgeFlow — APPROVED** [review]

**Review by amcor — APPROVED** [review]

**Review by rafaelbn — APPROVED** [review]
:+1:

**Comment by etobella** [comment]
@OCA/accounting-maintainers This is ready to merge

**Comment by AaronHForgeFlow** [comment]
better leave the bot to do the bump version

**Comment by etobella** [comment]
@AaronHForgeFlow Sure!!!

**Pull request closed without merging**
