### PR TITLE
[18.0][MIG] account_usability: Migration to 18.0

### PR DESCRIPTION
**Pull request by legalsylvain**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Check #1963 (and please name the PR properly).

**Comment by pedrobaeza** [comment]
OK, now I see your comment in that PR.

**Comment by legalsylvain** [comment]
hi @pedrobaeza. this PR was to test the solution proposed here https://github.com/OCA/account-financial-tools/pull/1963#issuecomment-2503249457 and it looks to work.

Note : I made a PR on the main repo template, to fix the problem for all the repo. Feel free to review.
 
https://github.com/OCA/oca-addons-repo-template/pull/287

@OCA/accounting-maintainers : could you merge the current PR ? (the previous PR was approved by 6 reviewers : https://github.com/OCA/account-financial-tools/pull/1963))

**Comment by pedrobaeza** [comment]
Approved in the superseded PR, so

/ocabot merge nobump
/ocabot migration account_usability

**Pull request merged**
