### PR TITLE
[14.0][ENH] account_spread_cost_revenue: add calculate by days feature

### PR DESCRIPTION
**Pull request by ps-tubtim**

### CODE REVIEW

**Comment by astirpe** [comment]
Is it possible to add tests for this feature and also clarify (in the readme and in the help of `days_calc`) what is the difference between calculate by days and previous behavior?

**Comment by Saran440** [comment]
@astirpe Hi, It's different, like calculating asset depreciation.

Each month has a different number of days.
This PR will calculating by day and has cost is not same each month

Standard
Selection_005

After check calculate by days
Selection_004

**Review by Saran440 — APPROVED** [review]
Add test script and Functional Test :+1:

**Review by Nantikan23 — APPROVED** [review]
Functional Tested

**Pull request closed without merging**
