### PR TITLE
[13.0][ADD] account_asset_management_transfer

### PR DESCRIPTION
**Pull request by Saran440**
This Module manages transfer the assets include depreciation's occurred on those assets.

image

This will cover following cases, which is meant to be the case discussed in OCA mailing list (asset under construction, etc...)

* Transfer: 1 source asset -> 1 target asset
* Merge: many source asset -> 1 target asset (Merge)
* Split: 1 source asset -> many asset :: I call it asset split
* many source asset -> many target asset

The Concept
* A new asset will be created
* All source asset will be removed
* Support transfering the asset with depre.

Example :
    Buy Mobile 10000.0 THB. and run depreciation 1 month.
    Next, We need split to Battery 1000.0 THB. and Case 9000.0 THB.
    It will reconciled asset and create new move for new asset.

Account Moves :
```
            Dr Accumulated depreciation of transfer assets (for each asset, if any)
                Cr Asset Value of trasferring assets (for each asset)
            Dr Asset Value to the new asset
                Cr Accumulated Depreciation of to the new asset (if any)

        =====================================================
        | Description                   |   Debit |   Credit|
        =====================================================
        | Vendor Bills                  |         | 10000.0 |
        | Mobile                        | 10000.0 |         |
        -------Run Depreciation 1 times----------------------
        | Accumulated Depre.            |         |    50.0 |
        | Depre. Expense                |    50.0 |         |
        -------Run Depreciation before remove----------------
        | Accumulated Depre.            |         |   150.0 |
        | Depre. Expense                |   150.0 |         |
        -------Remove Asset----------------------------------
        | Mobile                        |         | 10000.0 |
        | Accumulated Depre.            |   200.0 |         |
        | Loss Account                  |  9800.0 |         |
        -------New Asset-------------------------------------
        | Battery                       |  1000.0 |         |
        | Battery (Ratio Depreciation)  |         |    20.0 |
        | Case                          |  9000.0 |         |
        | Case (Ratio Depreciation)     |         |   180.0 |
```

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Shouldn't be `account_asset_management_transfer` for avoiding future collapses and for indicating which is the base dependency?

**Comment by Saran440** [comment]
@pedrobaeza Sorry, I'm not sure that you're talking about
`account_asset_management_transfer` and `account_asset_transfer` (this is mine)?

**Comment by pedrobaeza** [comment]
No, it's only a general thinking. No specific conflict case right now.

**Comment by kittiu** [comment]
Closed as we have account_asset_transfer in v14.

**Pull request closed without merging**
