### PR TITLE
[14.0][MIG] account_partner_required: Migration to 14.0

### PR DESCRIPTION
**Pull request by WesleyOliveira98**
cc: @marcelsavegnago @kaynnan

### CODE REVIEW

**Review by kaynnan — APPROVED** [review]
LGTM

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Comment by kaynnan** [comment]
ping @OCA/accounting-maintainers

**Comment by marcelsavegnago** [comment]
ping @OCA/accounting-maintainers

**Review by grindtildeath — APPROVED** [review]
LGTM :+1:

**Pull request merged**
