### PR TITLE
[8.0] account_chart_update: several improvements and fixes

### PR DESCRIPTION
**Pull request by sbidoul**
These changes help handling a massive restructuring of the chart of taxes such as the one occuring right now in Luxemburg.

I tried to preserve a clean history, so each commit should be self-explanatory.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Hi, Stéphane,

Thanks for your PR. The changes you proposed are very interesting. I only see one problem with one of the changes you are proposing: the deletion of tax codes. If you have these codes linked in any account.move.line, the wizard will fail, or even worse (I don't know cascade option), they will be set to null. Can we just simply deactivated adding an active field on account.tax.code?

Another improvement that can be made now that you are touching the module is to have a list with the fields to compare, so that we don't have to write so much lines to add a new field. Thanks to recordset comparison operators, we can use `==` also in many2one and many2many fields, and thus reduce a lot of code and make it more maintainable.

**Comment by sbidoul** [comment]
@pedrobaeza regarding the deletion of tax codes, Indeed there is a cascade set null on these fields (which IMO is dangerous and could be reported upstream). That's why I implemented a check to verify they are not in use (around line 527).

**Comment by pedrobaeza** [comment]
Don't you think then that it's better to enable active field mechanism? This way, we hide from user all not used tax codes, regardless they are being used or not.

**Comment by sbidoul** [comment]
Unfortunately there is no active field on account.tax.code. 

What we really would need is a kind of versioning mechanism on chart of taxes... but that's a huge effort which I'm not willing to make right now (and the situation will probably improve in 9.0 when the tax declarations are built using a report mechanism).

**Comment by pedrobaeza** [comment]
Yeah, the versioning is out of this scope, but you can add without no effort the active field on _account.tax.code_ in this module.

**Comment by sbidoul** [comment]
Ok, I will add the active field.

**Comment by adrienpeiffer** [comment]
:+1:   Code review and functional tests

**Comment by sbidoul** [comment]
@pedrobaeza here is a version that deactivates instead of deleting.

**Comment by pedrobaeza** [comment]
Thank you very much for the change.

:+1:

**Comment by sbidoul** [comment]
@pedrobaeza my pleasure. It's simpler this way.

While I was at it I added the deactivation of taxes that are not in the template.

**Comment by sbidoul** [comment]
I fixed an important bug wrt multi-company. I also improved the matching to take into account inactive taxes and tax codes. This branch worked well on several production databases.

**Comment by sbidoul** [comment]
rebased

**Comment by pedrobaeza** [comment]
Thanks again. I proceed with the merge.

**Pull request merged**
