### PR TITLE
[16.0][MIG] account_move_name_sequence: Migration to 16.0

### PR DESCRIPTION
**Pull request by RodrigoBM**
#1472 

Add fix return sequence names do not add a space between name and returns

And add fix comment in issue #1465 

And add fix comment in issue #1501 and comment https://github.com/OCA/account-financial-tools/pull/1510#issuecomment-1334580749

### CODE REVIEW

**Comment by moylop260** [comment]
For v16.0 the new PR is fixing almost concurrency issues:
 - https://github.com/odoo/odoo/pull/104606

The README of `account_move_name_sequence`  module for v16.0 could be deprecated

I mean, [`account_move_name_sequence` could be good for v16.0 only if you like to allow gaps](https://twitter.com/moylop260/status/1595220051661099008?s=20&t=ykO5e-J5tpljncTgBFb83g)

It was asked (without answer) in the original PR:
 - https://github.com/odoo/odoo/pull/104606#issuecomment-1302452744


e.g. we have v11.0 instances with custom modules migrated to v14.0 failing with the following case of use:

Subscriptions
1) Create invoice and post
2) Create payment and post
3) Reconcile

Shop
1) Create Sale Order
2) Create payment and post
3) Create invoice and post
4) Reconcile

(This case was considered in `test_sequence_concurrency_95_pay2inv_inv2pay` from https://github.com/odoo/odoo/pull/104647)

It could be fixed if you allow gaps for the journal of these kinds of payments

Even if the bottleneck was already fixed in v16.0

you don't have the allow-gaps option anymore, so, the module `account_move_name_sequence` could be helpful for these cases

So, the README of `account_move_name_sequence` needs to be rewrite

**Comment by alexis-via** [comment]
Thanks for this migration to v16. I'm testing your PR and it fails in the following scenario:
1) create a supplier invoice and confirm it. Keep it as unpaid.
2) click on "Add credit note". Keep default params of the wizard and click on "Reverse"
=> you get a draft supplier refund
3) Click on "Confirm". Get you this error:
```
The operation cannot be completed: A move can not be posted with name "/" or empty value
Check the journal sequence, please
```

The bug doesn't happen when the supplier refund is created manually from scratch.

**Comment by RodrigoBM** [comment]
Hi @alexis-via 

Yea, its error its same this issue https://github.com/OCA/account-financial-tools/issues/1501 for v14 and v15.

I put de fix https://github.com/OCA/account-financial-tools/pull/1514 but this not working in v16.

I have added another fix that does solve this case and I have added a test.

**Comment by alexis-via** [comment]
The problem is fixed, thank you!
I noticed this warning when you start odoo:
```
odoo.api.create: The model odoo.addons.account_move_name_sequence.models.account_journal is not overriding the create method in batch
```

**Review by andreampiovesana — APPROVED** [review]
LGTM 
functional test ok

**Comment by RodrigoBM** [comment]
Hi @alexis-via,

I have checked the warning, the problem is that account.journal in V16 uses @api.model_create_multi for the create method.

I have added the changes to work with this @api.model_create_multi for the create method.

Regards

**Review by marcelofrare — APPROVED** [review]
runboat is ok

**Comment by moylop260** [comment]
I think we could make the changes in the readme post-migration PR

/ocabot merge nobump

**Pull request merged**
