### PR TITLE
[12.0][account_invoice_constraint_chronology] Add invoice state 'in-payment' to conditions

### PR DESCRIPTION
**Pull request by Lopsanz**
Hi,

Chronology constraint raised when I didn't any draft invoice. So I've encountered this mistake.

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by JGarcia-Panach — APPROVED** [review]

**Review by rlizana — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
Could you squash commits?

**Comment by Lopsanz** [comment]
Sorry, @AaronHForgeFlow, I'm a newbie about git. I don't know how to do that. I'm following https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests steps but no results!

**Comment by Lopsanz** [comment]
@AaronHForgeFlow , It's just squashed!

**Comment by AaronHForgeFlow** [comment]
Thank you. Just another question. Are the changes in PO file are intentional? Not sure what they do.

**Comment by Lopsanz** [comment]
This is a PR that is already working for me. As you can see in .py file, message sent to user when a constraint is detected has changed and needs to be translated. I don't know if this is the right way, sorry again for my ignorance.

**Comment by CiroBoxHub** [comment]
:+1:

**Comment by CiroBoxHub** [comment]
@pedrobaeza Hello Pedro! this pull request is approved? This is a your pending review for that.

**Comment by CiroBoxHub** [comment]
Hi, can this PR be merged?

**Comment by Lopsanz** [comment]
Hi, can this PR be merged?

**Review by marcelsavegnago — APPROVED** [review]

**Pull request merged**
