### PR TITLE
[FIX] No such field(s) in model ir.values: object

### PR DESCRIPTION
**Pull request by max3903**
Fixes Runbot warning

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you check errors in CIs?

**Comment by max3903** [comment]
@pedrobaeza They are not related to this PR and more importantly, I don't know how to solve them.

**Comment by pedrobaeza** [comment]
OK, I haven't checked in deep

:+1:

**Comment by pedrobaeza** [comment]
Superseeded by https://github.com/OCA/account-financial-tools/pull/287

**Pull request closed without merging**
