### PR TITLE
[MIG] [11.0] account netting

### PR DESCRIPTION
**Pull request by feketemihai**
Migrate account_netting to 11.0.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you improve coverage testing corner cases like raising the exceptions?

**Comment by feketemihai** [comment]
@pedrobaeza In a few minutes...

**Comment by feketemihai** [comment]
@pedrobaeza Ready.

**Review by pedrobaeza — APPROVED** [review]
Thank you very much!

**Comment by ovnicraft** [comment]
Is ready to merge ?

**Comment by feketemihai** [comment]
@ovnicraft it needs more aprovals.

**Review by RoelAdriaans — APPROVED** [review]
:+1: 
Code and functinal tested okay

**Pull request merged**
