### PR TITLE
[ADD] [17.0] mail_template_substitute_account_move

### PR DESCRIPTION
**Pull request by sakthi-shan**
https://github.com/OCA/social/pull/1314#issuecomment-2106747932
cc: @SodexisTeam

### CODE REVIEW

**Review by atchuthan — APPROVED** [review]
code review :+1:

**Review by amkarthik — APPROVED** [review]
Functional and Code review 👍🏾

**Comment by sakthi-shan** [comment]
@OCA/accounting-maintainers Could you please merge this?

**Comment by sakthi-shan** [comment]
@OCA/core-maintainers

**Pull request merged**
