### PR TITLE
[15.0][FIX] account_asset_management: KeyError

### PR DESCRIPTION
**Pull request by P4R**
This PR solves a KeyError.
Captura de pantalla 2023-09-18 a las 12 46 53

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by P4R** [comment]
@pedrobaeza Could you merge this?

**Comment by pedrobaeza** [comment]
A second reviewer is needed:

https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#review

**Review by bosd — APPROVED** [review]
LGTM

**Comment by pedrobaeza** [comment]
/ocabot merge patch

Please forward-port it to v16

**Pull request merged**
