### PR TITLE
Forward port '7.0' into 8.0 until 7333aa8

### PR DESCRIPTION
**Pull request by sbidoul**
Merge 7.0 in 8.0 and move account_check_deposit to unported on the 8.0 branch.

### CODE REVIEW

**Comment by sbidoul** [comment]
WIP, waiting for #122

**Comment by yvaucher** [comment]
#122 is merged

**Comment by sbidoul** [comment]
I will update this PR soon.

**Comment by sbidoul** [comment]
Updated to latest 7.0. Green.

**Comment by yvaucher** [comment]
Thanks :+1:

**Comment by pedrobaeza** [comment]
:+1:

**Pull request merged**
