### PR TITLE
[ADD] account_payment_multicurrency module

### PR DESCRIPTION
**Pull request by vrenaville**
This module add the possibility to see the amount in currency and to be able to select partial paid invoice

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Maybe this module fits now better on bank-payment repo.

**Comment by sbidoul** [comment]
@vrenaville I also believe this is more suited for OCA/bank-payment.

Is this a 7.0-only module?

Have you looked into account_banking_payment_export which perhaps provides the hooks you need?

**Comment by fclementic2c** [comment]
Hi,

I agree that we should move this to the new bank-payment repo.

This module is essentially a backport from v8 in order to be able to handle partial payment and/or multicurrency residual amount. So it is different from account_banking_payment_export.

**Comment by vrenaville** [comment]
Hello,
thanks for your reviews,
I will change branch so I close this PR

Vincent

**Comment by vrenaville** [comment]
This PR has moved  : https://github.com/OCA/bank-payment/pull/69

**Pull request closed without merging**
