### PR TITLE
[FIX] account_credit_control_dunning_fees: Change currency by SQL

### LINKED ISSUE #654: 11.0 branch build failing
After the merge of https://github.com/OCA/account-financial-tools/pull/607 the build on 11.0 is failing.
The PR was green, but meanwhile a commit in odoo / OCB introduced a change incompatible with the tests: https://github.com/OCA/OCB/commit/0e881fcd3a5671c4fe84b2a47c9d3611e4b823a1 (found by @grindtildeath)

Travis logs: https://travis-ci.org/OCA/account-financial-tools/jobs/380154983

### PR DESCRIPTION
**Pull request by guewen**
To avoid constraint.

Fix incompatibility introduced in https://github.com/OCA/OCB/commit/0e881fcd3a5671c4fe84b2a47c9d3611e4b823a1

Port of https://github.com/OCA/account-financial-tools/commit/ae3143b6ae18c49145b5cec5569382986b8a6590

Closes #654

### CODE REVIEW

**Comment by guewen** [comment]
Oops my git remote url was wrong, pushed on the OCA repo. I'll clean my mess once merged.
The build is gonna be green anyway :)

**Comment by pedrobaeza** [comment]
OK, no problem, fast-tracking this and removing the branch.

**Comment by guewen** [comment]
Thanks @pedrobaeza for the correction, pointing me the correction, fast-tracking and cleaning my mess. You left me almost no work :rofl: :heart_eyes:

**Comment by pedrobaeza** [comment]
Hehe, then help me in this issue that I still have :wink: 
https://github.com/OCA/queue/issues/64

**Comment by guewen** [comment]
I know! I'm ashamed not to have checked yet

**Pull request merged**
