### PR TITLE
[16.0][MIG] account_chart_update: Migration to 16.0

### PR DESCRIPTION
**Pull request by ljsalvatierra-factorlibre**
https://github.com/OCA/account-financial-tools/issues/1472

### CODE REVIEW

**Comment by rafaelbn** [comment]
Thank you @ljsalvatierra-factorlibre ! 😄 We can review in @moduon MT-2085

**Comment by ljsalvatierra-factorlibre** [comment]
> Thank you @ljsalvatierra-factorlibre ! smile We can review in @moduon MT-2085

Thank you! I've updated the wizard view

image

imagen

**Review by yajo — APPROVED** [review]
Code review looks good.

Functional review: it seems there are a few glitches:

imagen
imagen

Regarding horizontal scroll, it was fixed for v15 in https://github.com/OCA/account-financial-tools/pull/1552, so it's better to keep it working fine!

The other details are not blocking, but it would be nice if you can fix them.

**Comment by ljsalvatierra-factorlibre** [comment]
> Code review looks good.
> 
> Functional review: it seems there are a few glitches:
> 
> imagen imagen
> 
> Regarding horizontal scroll, it was fixed for v15 in #1552, so it's better to keep it working fine!
> 
> The other details are not blocking, but it would be nice if you can fix them.

Fixed button design, but can't fix the horizontal scroll

imagen

imagen

imagen

**Comment by yajo** [comment]
OK! Not an extremely big problem anyway. @rafaelbn this is ready to merge IMHO.

**Review by rafaelbn — APPROVED** [review]
Thank you! 👍 

/ocabot merge patch

**Pull request merged**
