### PR TITLE
13.0 fix revert to 7apr20

### PR DESCRIPTION
**Pull request by kittiu**
https://github.com/OCA/account-financial-tools/issues/963

cc @AaronHForgeFlow

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
Thank you @kittiu Yes I meant this.  But I am not sure now because there are many commits reverted.

The ideal solution would be to revert only 0c049293dfe74978114f87325a4a79b6ca2ea34d  Otherwise we will lost the other commits related to other modules. The thing is you may have conflicts if you just try to revert 0c049293dfe74978114f87325a4a79b6ca2ea34d

So I am wondering if it's best to just include the module account_move_line_purchase_info back and that's it. What do you think @HviorForgeFlow ?

**Comment by HviorForgeFlow** [comment]
Yes @AaronHForgeFlow, I think that create a PR readding the module is more simple. I would wait to account_document_reversal to be merged, because travis CI is now broken.

**Comment by pedrobaeza** [comment]
Isn't better to just go on and make a PR if the module needs to be fixed somehow instead of reverting everything?

**Comment by AaronHForgeFlow** [comment]
> Isn't better to just go on and make a PR if the module needs to be fixed somehow instead of reverting everything?

If we do a wrong merge, reverting is the same as leaving the branch as in its previous status. I think that is correct.

The problem here is we realized of the problem too late and now there are many commits after, that is why reverting is not good idea.

**Comment by pedrobaeza** [comment]
Yeah, and also if the merge was premature (but not wrong), or only needs additional fixes, better to go with additional fixes.

**Comment by AaronHForgeFlow** [comment]
The problem here is that one existing module was deleted by mistake. Then recovering the entire history will be like migrate that module again :(

**Comment by AaronHForgeFlow** [comment]
@kittiu sorry for the confusion. Better to close this, and then wait for the merge in the account_document_reversal module

**Comment by kittiu** [comment]
But for the good account_document_reversal in https://github.com/OCA/account-financial-tools/pull/959 to get merged, the bad account_document_reversal to be removed first.
Should I make a quick fix PR, just to delete the module first, OK?

**Comment by pedrobaeza** [comment]
OK for me

**Comment by kittiu** [comment]
@AaronHForgeFlow please can you help merge? https://github.com/OCA/account-financial-tools/pull/966
Then, I will do rebase on the PR account_document_reversal again.
Then, someone will do the PR for account_move_line_purchase_info, right?
**Note:** my apology for causing trouble, will be more careful.

**Comment by AaronHForgeFlow** [comment]
Thank you! @kittiu 
Yes,  @HviorForgeFlow or myself will create the PR fo raccount_move_line_purchase_info

**Comment by kittiu** [comment]
> Thank you! @kittiu
> Yes, @HviorForgeFlow or myself will create the PR fo raccount_move_line_purchase_info

Hi, Just found that, the account_move_line_purchase_info was in account_netting. In the above PR, I just move it outside.

**Comment by AaronHForgeFlow** [comment]
Opss I noticed something different now. account_move_line_purchase_info was not actually deleted. It is inside another module account_netting:
image

So I would do and the PR you just created:
- Remove account_document_reversal (already done)
- Move account_move_line_purchase_info from inside account_netting to the root directory

@pedrobaeza  will you agree with this?

**Comment by AaronHForgeFlow** [comment]
@kittiu we wrote the same thing :smile:

**Pull request closed without merging**
