### PR TITLE
[13.0][MIG] account_move_fiscal_month: Migration to 13.0

### PR DESCRIPTION
**Pull request by remihb**
- [ ] waiting for #1089

### CODE REVIEW

**Comment by remihb** [comment]
How to resolve failure which is relative to module dependences ?
`odoo.exceptions.UserError: ("You try to install module 'account_move_fiscal_month' that depends on module 'account_fiscal_month'.\nBut the latter module is not available in your system.", '') `

**Comment by AaronHForgeFlow** [comment]
@remihb  you could add the link to the dependency module in the oca_dependencies.txt  in a new commit: https://github.com/OCA/maintainer-quality-tools/blob/master/sample_files/oca_dependencies.txt#L19

The inconvenience is that that commit must be dropped befor ethe merge. 

The other option is to wait until the other is merged.

If you choose option1 just please udpdate the main commnet saying that this PR is watinging dependencies.

Like:
- [ ] waiting for https://github.com/OCA/account-financial-tools/pull/1089

**Comment by remihb** [comment]
I'm not sure if I well understand, but it seems to me that the _oca_dependencies.txt_ is for dependencies that are outside the oca repo, isn't it ?

**Comment by AaronHForgeFlow** [comment]
Is mainly userd for dependencies to other OCA repos. But it could use for this too, temporarily, just before getting the merge.

**Comment by remihb** [comment]
Ok done so.

**Comment by AaronHForgeFlow** [comment]
The line format should be in this case in the oca_dependencies.txt:

account_fiscal_month https://github.com/osiell/sale-workflow 13.0-mig-account_fiscal_month

**Comment by remihb** [comment]
ah ok, I just understood what is the point. Should had read doc more carefully ^^'

**Comment by AaronHForgeFlow** [comment]
@remihb The dependency is merged! you can drop the last commit here :)

**Pull request closed without merging**
