### PR TITLE
13.0_account-financial-tools_fix: add acl for group billing

### PR DESCRIPTION
**Pull request by vanderperre**
More ACL(s) needed for salesman(billing group) because before it they aren't able to post invoice .....

### CODE REVIEW

**Comment by vanderperre** [comment]
About the module account_spread_cost_revenue:
It is necessary to backport and/or report this fix on other versions 

PS. sorry for the commit name ....

**Review by luc-demeyer — APPROVED** [review]

**Comment by luc-demeyer** [comment]
@kittiu 
can you cherry-pick this PR into https://github.com/OCA/account-financial-tools/pull/1244 ?

**Comment by TheerayutEncoder** [comment]
Hi @vanderperre 
I cannot cherry-pick your pr because it will conflict.
**note:** we should not edit `.pre-commit-config.yaml` file by manually

So, I had update copier template v13 in this PR: https://github.com/OCA/account-financial-tools/pull/1500
That mean you dont need to edit `.pre-commit-config.yaml` and wait this pr is merged.

After merge, you can pull account-financial-tools v13.0 and push again.
Thanks.

**Review by astirpe — APPROVED** [review]
@vanderperre there are now conflicts to be resolved

**Review by BenjaHe — APPROVED** [review]
Thank you @vanderperre.

**Pull request closed without merging**
