### PR TITLE
MIG - Account cost center

### PR DESCRIPTION
**Pull request by patrickt-oforce**
Backport of module account_cost_center to v 14.0

### CODE REVIEW

**Comment by patrickt-oforce** [comment]
@OCA/accounting-maintainers need to squash commit history?

**Review by matteoopenf — APPROVED** [review]
technical review ok

**Comment by elvise** [comment]
@matteoopenf @patrickt-oforce
Login > Invoice > Error:

Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 361, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 908, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 533, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 1372, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 1364, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 395, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 368, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/models.py", line 1530, in load_views
    for [v_id, v_type] in views
  File "/opt/odoo/odoo/models.py", line 1530, in <dictcomp>
    for [v_id, v_type] in views
  File "/opt/odoo/addons/web/models/models.py", line 246, in fields_view_get
    r = super().fields_view_get(view_id, view_type, toolbar, submenu)
  File "/opt/odoo/odoo/models.py", line 1625, in fields_view_get
    bindings = self.env['ir.actions.actions'].get_bindings(self._name)
  File "<decorator-gen-47>", line 2, in get_bindings
  File "/opt/odoo/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/odoo/addons/base/models/ir_actions.py", line 117, in get_bindings
    result[binding_type].append(action.read()[0])
  File "/opt/odoo/odoo/addons/base/models/ir_actions.py", line 240, in read
    result = super(IrActionsActWindow, self).read(fields, load=load)
  File "/opt/odoo/odoo/models.py", line 3022, in read
    return self._read_format(fnames=fields, load=load)
  File "/opt/odoo/odoo/models.py", line 3042, in _read_format
    vals[name] = convert(record[name], record, use_name_get)
  File "/opt/odoo/odoo/models.py", line 5703, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo/odoo/fields.py", line 1021, in __get__
    self.compute_value(recs)
  File "/opt/odoo/odoo/fields.py", line 1177, in compute_value
    records._compute_field_value(self)
  File "/opt/odoo/odoo/models.py", line 4078, in _compute_field_value
    getattr(self, field.compute)()
  File "/opt/odoo/odoo/addons/base/models/ir_actions.py", line 207, in _compute_search_view
    fvg = self.env[act.res_model].fields_view_get(act.search_view_id.id, 'search')
  File "/opt/odoo/odoo/api.py", line 476, in __getitem__
    return self.registry[model_name]._browse(self, (), ())
  File "/opt/odoo/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
KeyError: 'update.journal.lock.dates.wizard'

**Comment by patrickt-oforce** [comment]
> @matteoopenf @patrickt-oforce Login > Invoice > Error:
> 
> Odoo Server Error
> 
> Traceback (most recent call last): File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch result = request.dispatch() File "/opt/odoo/odoo/http.py", line 685, in dispatch result = self._call_function(**self.params) File "/opt/odoo/odoo/http.py", line 361, in _call_function return checked_call(self.db, *args, **kwargs) File "/opt/odoo/odoo/service/model.py", line 94, in wrapper return f(dbname, *args, **kwargs) File "/opt/odoo/odoo/http.py", line 349, in checked_call result = self.endpoint(*a, **kw) File "/opt/odoo/odoo/http.py", line 908, in **call** return self.method(*args, **kw) File "/opt/odoo/odoo/http.py", line 533, in response_wrap response = f(*args, **kw) File "/opt/odoo/addons/web/controllers/main.py", line 1372, in call_kw return self._call_kw(model, method, args, kwargs) File "/opt/odoo/addons/web/controllers/main.py", line 1364, in _call_kw return call_kw(request.env[model], method, args, kwargs) File "/opt/odoo/odoo/api.py", line 395, in call_kw result = _call_kw_model(method, model, args, kwargs) File "/opt/odoo/odoo/api.py", line 368, in _call_kw_model result = method(recs, *args, **kwargs) File "/opt/odoo/odoo/models.py", line 1530, in load_views for [v_id, v_type] in views File "/opt/odoo/odoo/models.py", line 1530, in for [v_id, v_type] in views File "/opt/odoo/addons/web/models/models.py", line 246, in fields_view_get r = super().fields_view_get(view_id, view_type, toolbar, submenu) File "/opt/odoo/odoo/models.py", line 1625, in fields_view_get bindings = self.env['ir.actions.actions'].get_bindings(self._name) File "", line 2, in get_bindings File "/opt/odoo/odoo/tools/cache.py", line 90, in lookup value = d[key] = self.method(*args, **kwargs) File "/opt/odoo/odoo/addons/base/models/ir_actions.py", line 117, in get_bindings result[binding_type].append(action.read()[0]) File "/opt/odoo/odoo/addons/base/models/ir_actions.py", line 240, in read result = super(IrActionsActWindow, self).read(fields, load=load) File "/opt/odoo/odoo/models.py", line 3022, in read return self._read_format(fnames=fields, load=load) File "/opt/odoo/odoo/models.py", line 3042, in _read_format vals[name] = convert(record[name], record, use_name_get) File "/opt/odoo/odoo/models.py", line 5703, in **getitem** return self._fields[key].**get**(self, type(self)) File "/opt/odoo/odoo/fields.py", line 1021, in **get** self.compute_value(recs) File "/opt/odoo/odoo/fields.py", line 1177, in compute_value records._compute_field_value(self) File "/opt/odoo/odoo/models.py", line 4078, in _compute_field_value getattr(self, field.compute)() File "/opt/odoo/odoo/addons/base/models/ir_actions.py", line 207, in _compute_search_view fvg = self.env[act.res_model].fields_view_get(act.search_view_id.id, 'search') File "/opt/odoo/odoo/api.py", line 476, in **getitem** return self.registry[model_name]._browse(self, (), ()) File "/opt/odoo/odoo/modules/registry.py", line 177, in **getitem** return self.models[model_name] Exception
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/opt/odoo/odoo/http.py", line 641, in _handle_exception return super(JsonRequest, self)._handle_exception(exception) File "/opt/odoo/odoo/http.py", line 317, in _handle_exception raise exception.with_traceback(None) from new_cause KeyError: 'update.journal.lock.dates.wizard'

@elvise can you explain where the error originated; i've tested in locale and i've not encountered error; the model that error indicate is related to `account_journal_lock_date` module in account_cost_center there is no model as indicated on the error.
I don't think this module is incompatible with the one that originate error

**Comment by elvise** [comment]
@patrickt-oforce 
Runboat > Login > Invoice > Error

**Comment by patrickt-oforce** [comment]
> @patrickt-oforce Runboat > Login > Invoice > Error

Tested now on runbot, and seem that account_journal_lock_date is a mandatory dependency. I update depends list

**Comment by elvise** [comment]
> > @patrickt-oforce Runboat > Login > Invoice > Error
> 
> Tested now on runbot, and seem that account_journal_lock_date is a mandatory dependency. I update depends list

Great! 💣

**Comment by matteoopenf** [comment]
@elvise  puoi aggiornare la review?

**Comment by patrickt-oforce** [comment]
@elvise Module dependecies updated

**Comment by elvise** [comment]
@patrickt-oforce @matteoopenf if you enable “show full accounting feature”, you get an error when click on invoice dashboard

**Comment by patrickt-oforce** [comment]
@elvise hi, can you explain which path follow that lead to the error. I can see the "show full accounting feature" flag

**Comment by patrickt-oforce** [comment]
@elvise about the first error indicated, i've checked on our customer environment and the module of this PR is not related to `account_journal_lock_date`; and i think the last error you have indicated is not related with this module

**Comment by elvise** [comment]
@patrickt-oforce thanks for comment! 
Right now looks good also in the runboat

**Comment by matteoopenf** [comment]
@OCA/accounting-maintainers  review and merge?

**Comment by matteoopenf** [comment]
@elvise  can you approve?

**Comment by matteoopenf** [comment]
@elvise  remind

**Review by elvise — APPROVED** [review]
LGTM!

**Comment by matteoopenf** [comment]
@pedrobaeza  is it possibile merge?
thank you

**Comment by pedrobaeza** [comment]
Merging based on the reviews.

/ocabot merge nobump

**Pull request merged**
