### PR TITLE
[ADD] locking move module

### PR DESCRIPTION
**Pull request by vrenaville**
This module add ability to lock a move from modification

### CODE REVIEW

**Comment by fclementic2c** [comment]
This module aim to replace account_default_draft_move since we have too many minor sides effects:  
- account moves do not receive a number -> search is difficult and accountant wants to have a number that does not change later at validation
- reports (accounting, VAT...) works by defaut on posted entries. Users forget to change the filter sometimes; VAT report _(and Frech FEC report) does not even allows to includes draft entries
- expenses does not have a sequence, you have to validate the entry to get one but then you loose possibility to cancel/modify.
- Mass entry posting takes ages at the end of the month for bigger companies
- It is even worst if you work with analytical accounts.

So we want at C2C change the approach : The idea is to always post all entries like Odoo standard suggests and to install account_cancel to give flexibility to cancel/modify entries easily. 
We would just need this new module to lock entries with a very simple boolean field.

@sbidoul opinion would be welcome. :) thanks 

Frederic.

**Comment by fclementic2c** [comment]
Functional test OK
:+1:

**Comment by sbidoul** [comment]
@fclementic2c I agree with the side effects of account_default_draft_move, especially the search part. 

It's good to discuss this. I have no strong opinion yet, just a few question/comments:
- in the end, do you remember why does account_default_draft_move hide the Post button on journal entries?
- note that in its latest incarnation account_default_draft_move can honor the "skip draft move" flag for all documents [1]
- at what point in the accounting process would you have accountants lock moves?
- is it not enough to close a period for a journal with account_journal_period_close?

[1] https://github.com/OCA/account-financial-tools/pull/205#issuecomment-115309235

**Comment by luc-demeyer** [comment]
I never liked the account_default_draft_move hence I support very much this approach whereby a simple boolean allows the accountant to lock an entry. This field can also be easily used in custom modules to be set automatically in specific cases.

In our experience most cases can be covered though via the account_cancel (with a per journal setting of the allow/block cancel) in combination with account_journal_period_close.

**Comment by fclementic2c** [comment]
My answers inlines : 
- in the end, do you remember why does account_default_draft_move hide the Post button on journal entries?
  This button was confusing for end-user. And after a 'post' it was impossible for them to cancel/modify the entry (since the idea was to never use account_cancel)
- note that in its latest incarnation account_default_draft_move can honor the "skip draft move" flag for all documents [1]
  Yes, it is good but our issue was that external accounting auditor must be sure that what they audited will never change. But this is only for bigger company so not mandatory in most cases.
- at what point in the accounting process would you have accountants lock moves?
  is it not enough to close a period for a journal with account_journal_period_close?
  Not sure how it works, If you can re-open entry and do modifications then it is not Ok for our countries.

**Comment by jgrandguillaume** [comment]
Hi,

I'm :+1:  this PR because:
-  It allow to "come back" on the way Odoo manage the entries (posting them after generation)
- VAT report can be generated properly, without closing a whole period (like with account_default_draft_move)
- Installing account_cancel allow the end user to work doay to day with ease
- The remaining issue is to prevent somone to touch past closed perdio, this module will ensure this, even for the journal where it is allowed to cancel posted move for eas of use.

Regards,

Joël

**Comment by sbidoul** [comment]
:+1: too, no objection.

That said I still believe account_default_draft_move is useful as a mechanism to honor the "skip draft moves" flags for invoices and bank statements. Your feedback on #250 is welcome.

**Comment by nbessi** [comment]
:+1:

**Pull request merged**
