### PR TITLE
[17.0][MIG] account_chart_update

### LINKED ISSUE #240: [8.0] account_chart_update: object has no attribute '_tax_mapping'
Something from commit 3f3f59c16 seems incomplete, as a reference to self._tax_mapping remains in _prepare_account_vals, which causes traceback on actual trying to update things:

  File "/home/leio/.local/share/Odoo/addons/8.0/account_chart_update/wizard/wizard_chart_update.py", line 1006, in _update_accounts
    account_template, mapping_taxes, mapping_accounts)
  File "/home/leio/.local/share/Odoo/addons/8.0/account_chart_update/wizard/wizard_chart_update.py", line 971, in _prepare_account_vals
    if self.map_tax_template(tax_template, mapping_taxes)]
AttributeError: 'wizard.update.charts.accounts' object has no attribute '_tax_mapping'

@pedrobaeza ?

### PR DESCRIPTION
**Pull request by dreispt**

### CODE REVIEW

**Comment by ioans73** [comment]
@dreispt error installing module in runboat `KeyError: 'Field code_digits referenced in related field definition wizard.update.charts.accounts.code_digits does not exist.'`

**Comment by giarve** [comment]
I assume this PR will be stale

note it has to be adapted for
https://github.com/odoo/odoo/pull/110016

**Comment by yajo** [comment]
Are you taking into account this refactor? https://github.com/odoo/odoo/pull/110016

**Comment by giarve** [comment]
> Are you taking into account this refactor? [odoo/odoo#110016](https://github.com/odoo/odoo/pull/110016)

Not in this PR. The error it raises as told by @ioans73 on installation time is basically due to that.

**Comment by dreispt** [comment]
Yes, this needs significant changes to work, since there were big changes upstream.
I'm don't plan to continue that work at this moment.

@pedrocs-exo you mentioned to me you were planning to work on this, is it still the case?

**Comment by percevaq** [comment]
Is anyone working on this RM? If not, I will migrate the module to 17. Any help is welcome.

Thanks

**Comment by yajo** [comment]
Just make sure it's needed. Odoo uses a completely new system for CoA templates in v17, and they already have methods for loading it AFAIK. So possibly this module is no longer needed or, if needed, it can be much slimmer.

**Comment by victoralmau** [comment]
Superseded by https://github.com/OCA/account-financial-tools/pull/1989

**Pull request closed without merging**
