### PR TITLE
[10.0] [FIX] account move get journal sequence in name

### PR DESCRIPTION
**Pull request by Tonow-c2c**
Same as this PR [https://github.com/acsone/account-financial-tools/pull/6/files](https://github.com/acsone/account-financial-tools/pull/6/files) but with _fresher_ HEAD

### CODE REVIEW

**Review by grindtildeath — COMMENTED** [review]
I'm not sure about this one but it make sense to me, since the name of the asset is already used on move line. However I'm not sure of of its impact on existing databases, and if we shouldn't add a parameter to allow customization.
@luc-demeyer @fclementic2c What do you think ?

@Tonow-c2c Can you please rephrase the commit message ? e.g 'Use default journal sequence to generate account move name'

**Comment by leemannd** [comment]
@Tonow-c2c I was asking me a few questions, but it seems like @grindtildeath already asked them.
Ping me once you have answers or pushed something else

**Review by gurneyalex — CHANGES_REQUESTED** [review]
Please improve commit message: this is not an "IMP" it's a "FIX". Then explain that the previous code is generating account moves with the same number which is a really bad idea.

**Comment by gurneyalex** [comment]
travis red build is not related to the PR (branch 10.0 is red at the moment)

**Comment by Tonow-c2c** [comment]
@grindtildeath and @leemannd I don't now the real impact  maybe @mpanarin and @fclementic2c can explain what is the goal to [https://github.com/acsone/account-financial-tools/pull/6](https://github.com/acsone/account-financial-tools/pull/6)

**Comment by luc-demeyer** [comment]
this same question came up and has been answered in 
https://github.com/OCA/account-financial-tools/pull/677.

I think the current default behaviour should be kept. As an alternative we could make it configurable but in my experience (after having this module rolled already to at least 50 environments over the last couple of years) it is primarily an matter of being capable to explain to the customer why we don't use the journal sequence (so far I have had only one case where I made a small  inherited module to enforce the journal sequence).

**Pull request closed without merging**
