### PR TITLE
[14.0][IMP] account_asset_management: prevent from creating assets from tax lines

### PR DESCRIPTION
**Pull request by mariadforgeflow**
@ForgeFlow

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
Assets are created from the invoice lines only, aren't they?

**Comment by mariadforgeflow** [comment]
Hi @AaronHForgeFlow! It checks each account move line, if its account has an asset_profile_id set it creates the asset. The thing is that non deductible taxes lines have the same account as the product, therefore a new asset was being created for these lines also.

**Review by AaronHForgeFlow — APPROVED** [review]
Thanks for the explanation :)  LGTM :+1:

**Review by flotho — APPROVED** [review]
make sense
code review 
LGTM

**Review by Saran440 — APPROVED** [review]
LGTM :+1:

**Pull request merged**
