### PR TITLE
[FIX] account_asset_management: correct field name

### PR DESCRIPTION
**Pull request by yelizariev**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please install locally pre-commit for being auto-executed, or do the change that is proposed in the red CI.

**Review by StefanRijnhart — APPROVED** [review]
Confirmed by https://github.com/OCA/OpenUpgrade/blob/14.0/openupgrade_scripts/scripts/account/14.0.1.1/upgrade_analysis.txt#L95-L103

**Comment by yelizariev** [comment]
I  made this PR via github UI, I'd like to ask someone to finalize it

**Comment by pedrobaeza** [comment]
Do you mind if I do a direct commit without your attribution?

**Comment by pedrobaeza** [comment]
I'm going to change the PR for doing things correctly, so don't worry about that.

**Review by HaraldPanten — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Thanks for the patch, Ivan:

/ocabot merge patch

**Review by marcelsavegnago — APPROVED** [review]

**Pull request merged**
