### PR TITLE
[IMP] account_asset_management: Add scheduled action for the depreciation asset entries creation.

### PR DESCRIPTION
**Pull request by ValentinVinagre**
Coming from: https://github.com/OCA/account-financial-tools/issues/1011
Created a cron for the automatic generation of depreciation asset entries creation and updated the readme.

### CODE REVIEW

**Comment by ValentinVinagre** [comment]
@HaraldPanten could you review it?
Thanks

**Review by HaraldPanten — APPROVED** [review]
Minor changes. It solves https://github.com/OCA/account-financial-tools/issues/1011 LGTM 👍

**Review by pedrobaeza — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]

**Comment by ValentinVinagre** [comment]
All green, ready to merge.

**Comment by HaraldPanten** [comment]
Hi @pedrobaeza , any advice on how to solve Travis pending status? Everything seems to be OK... 🤔 THX!

**Pull request merged**
