### PR TITLE
Move module icon in static/description

### PR DESCRIPTION
**Pull request by yvaucher**

### CODE REVIEW

**Comment by adrienpeiffer** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by pedrobaeza** [comment]
I can merge this one as trivial

**Comment by yvaucher** [comment]
Thanks

**Comment by yvaucher** [comment]
Icon is now displayed 
https://www.odoo.com/apps/modules/8.0/currency_rate_update/

**Pull request merged**
