### PR TITLE
[11.0][ADD] account_fx_spot

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
Account FX Spot
===============

This module extends the functionality of Accounting to support Foreign
Exchange Spot Transactions. A **Foreign Exchange Spot Transaction**, also
known as FX spot, is an agreement between two parties to buy one currency
against selling another currency at an agreed price for settlement on
the spot date. The exchange rate at which the transaction is done is
called the spot exchange rate.

Configuration
=============

To configure this module, you need to:

#. Go to *Accounting > Configuration > Settings*.
#. Enable the *Multi-Currencies* option.

Usage
=====

With this module, you will be able to:

* Create FX Spot Transactions.

#. Go to *Accounting > Foreign Exchange > FX Spot Transaction*.
#. Select a Partner and fill the outgoing and incoming amounts and currencies.

* Register Payments for FX Spot Transactions.

#. Select Several transactions from the tree view.
#. Click on *Action > Register Payment*.

or

#. Go to the form view for an open transaction.
#. Click on *Register Payment*.

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
WIP

**Comment by pedrobaeza** [comment]
Are we going to finally move this to OCA/currency?

**Comment by LoisRForgeFlow** [comment]
@pedrobaeza yes, but the repo isn't created, is it?

**Comment by pedrobaeza** [comment]
Well, @jbeficent can create it also :wink: , but I can do it when I recover from my visit to Barcelona + Madrid.

**Comment by JordiBForgeFlow** [comment]
@pedrobaeza For some reason I do not have permissions to create or change repositories in OCA. Perhaps you can give me the permissions..

**Comment by pedrobaeza** [comment]
@jbeficent you are member the same as me of "OCA board" group that has this permission, so you should be able to:

seleccion_003

**Comment by LoisRForgeFlow** [comment]
closed in favor of https://github.com/OCA/currency/pull/2

**Pull request closed without merging**
