### PR TITLE
[ADD][12.0] account_template_active

### PR DESCRIPTION
**Pull request by legalsylvain**
This module allows to disable account template items, adding
an ``active`` field on the following models:

* ``account.account.template``

account_account_template_tree

* ``account.fiscal.position.template`` and it two related models
    * ``account.fiscal.position.account.template``
    * ``account.fiscal.position.tax.template``

account_fiscal_position_template_form

This module can be interesting in a multi company context,
if you install a lot of accounting templates, with some changes.

It can also be interesting if you want to developp a custom localization
module based on the official one, but with some removed / added / altered items.

**Note:**

* The field ``active`` is present in the Odoo ``account`` module for the model
  ``account.tax.template``. for that field, this module only adds the ``active``
  field on the tree view.

account_tax_template_tree

#GRAPOCA

### CODE REVIEW

**Review by tonygalmiche — APPROVED** [review]
I installed this module on my computer
I also installed these modules to see the menus indicated:
```
account_group_menu
account_menu
account_tag_menu
account_type_menu
```
Everything works as shown
Thanks for this module

**Review by HaraldPanten — APPROVED** [review]
LGTM. Functional review 👍

**Comment by StefanRijnhart** [comment]
Nice module! I ported it to 14.0: https://github.com/OCA/account-financial-tools/pull/1187. Please squash commits in this PR.

**Comment by legalsylvain** [comment]
Hi all. thanks for your review. 
@StefanRijnhart : I squashed commits & reviewed the v14 branch.

I think this PR can be merged.

regards.

**Comment by StefanRijnhart** [comment]
Thanks!

/ocabot merge nobump

**Pull request merged**
