### PR TITLE
[10.0] add ability to manage negative invoices/refunds

### PR DESCRIPTION
**Pull request by sergiocorato**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why is this needed? AFAIK, negative invoices are allowed.

Please don't include in the README something in Italian. Imagine we put the description in all languages... Let's think something smarter at other level. Commenting with the OCA board for looking to alternatives.

**Comment by sergiocorato** [comment]
> Why is this needed? AFAIK, negative invoices are allowed.
> 
> Please don't include in the README something in Italian. Imagine we put the description in all languages... Let's think something smarter at other level. Commenting with the OCA board for looking to alternatives.

Yes until v.11 they are allowed (not in v.12), but not correctly managed in payments, see issue https://github.com/odoo/odoo/issues/19280
Ok for translation.
Alternatives? for translation?

**Comment by pedrobaeza** [comment]
Then this should be in OCA/account-payment, and with the proper name: `account_payment_negative_invoice` or similar.

**Comment by pedrobaeza** [comment]
And please include in the README this information about the why.

**Comment by sergiocorato** [comment]
ok I move there, thanks

**Comment by sergiocorato** [comment]
superseeded by https://github.com/OCA/account-payment/pull/222

**Pull request closed without merging**
