### PR TITLE
[11.0][mig] account_reversal

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
Standard migration to 11.0

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please squash translation commits (both Launchpad and Transifex).

**Comment by pedrobaeza** [comment]
@ursais I have seen that your were assigned to account_reversal method, but @jbeficent has already done it. I hope you haven't duplicated efforts.

**Comment by JordiBForgeFlow** [comment]
@pedrobaeza Done. Thanks.

**Comment by pedrobaeza** [comment]
I don't see migration commit

**Comment by JordiBForgeFlow** [comment]
@pedrobaeza fixed!

**Review by rgarnau — APPROVED** [review]
LGTM :+1:

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by etobella — APPROVED** [review]
LGTM 👍

**Comment by pedrobaeza** [comment]
Next time please check existing PRs, as I did the migration some time before and with improved commit squashing and tests: #557. Please check at least the tests for incorporating them (and commit history can't be now improved, let's see on v12).

**Pull request merged**
