### PR TITLE
currency_rate_update: Update currency rate from NBRM

### PR DESCRIPTION
**Pull request by DarkoNikolovski**
Update currency rate from National Bank of the Republic of Macedonia

### CODE REVIEW

**Comment by DarkoNikolovski** [comment]
@pedrobaeza Could you help me with an external dependency on RunBot. I have added it into .travis.yml and in the **openerp**.py but still is not installed and the check fails
`Unable to install module "currency_rate_update" because an external dependency is not met: No module named pysimplesoap`

Thanks.

**Comment by pedrobaeza** [comment]
Hi, as this introduces a new dependency, we should add it as a new module, not modifying current one.

**Comment by DarkoNikolovski** [comment]
Ok. I will create a new module for this one.

**Comment by DarkoNikolovski** [comment]
I am closing this PR. Will create new one with separate module for NBRM rate update.

**Pull request closed without merging**
