### PR TITLE
Excessive context for API V8 write()

### PR DESCRIPTION
**Pull request by kittiu**
TypeError: write() got an unexpected keyword argument 'context'

### CODE REVIEW

**Comment by elicoidal** [comment]
Please give travis some love :)

**Comment by kittiu** [comment]
Travis seem to fail in the master v8 branch?

**Review by alexis-via — APPROVED** [review]

**Comment by elicoidal** [comment]
@kittiu super strange indeed @gurneyalex any idea of the reason?

**Review by elicoidal — APPROVED** [review]

**Comment by pedrobaeza** [comment]
It's due to incompatibility between Odoo's account_asset and account_asset_management. We have to split tests. I'll do it later. Merging this one meanwhile.

**Comment by pedrobaeza** [comment]
#493 should fix it.

**Pull request merged**
