### PR TITLE
Fix bug #301

### PR DESCRIPTION
**Pull request by alexis-via**
I don't know if it's the right solution to fix bug #301, but it's an easy fix.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1: while my question on the issue is being debated

**Comment by alexis-via** [comment]
Let's merge this please :+1:

**Comment by pedrobaeza** [comment]
I need at least another supporting thumb, and please evaluate my alternative approach

**Comment by yvaucher** [comment]
:+1:

**Comment by yvaucher** [comment]
(merging)

**Comment by yvaucher** [comment]
Merged at https://github.com/OCA/account-financial-tools/commit/29ccdea5950f08eb93e9e91528ebbe02c90209d7

**Pull request closed without merging**
