### PR TITLE
8.0 Small enhancements in account_invoice_constraint_chronology

### PR DESCRIPTION
**Pull request by alexis-via**
Add post_install script to have good default options after module installation
Update to latest OCA coding standards
Replace onchange by a constraint on account.journal (the onchange was not working because the field was conditionnaly set to readonly)

@adrienpeiffer As you are the original author of the module, what do you think of these small changes ?

### CODE REVIEW

**Comment by chafique-delli** [comment]
@alexis-via , thank you for these changes
:+1:

**Comment by adrienpeiffer** [comment]
Hi Alexis,
Thanks for this PR ! I check it.

**Comment by alexis-via** [comment]
@adrienpeiffer only I point needs explaination: as you certainly know, when you change the value of a readonly field via onchange, the new value is not written to DB. That's why I removed the attrs/readonly on the check_chronology field and switched from an on_change to a constraint.

**Review by adrienpeiffer — APPROVED** [review]
Code review and functional test

**Pull request merged**
