### PR TITLE
[10.0][IMP] account_chart_update: Major refactoring

### PR DESCRIPTION
**Pull request by pedrobaeza**
* Don't cache recordsets
   
  When marking methods as ormcache, you can't return recordsets, as they keep the cursor information, and that cursor can be closed (worker spawn for example) when you need to access again data.

  This is fixed returning IDs instead, and browsing when needed

* Compare all fields from template
    
  Not all fields were properly compared with previous code. This means also to exclude some of them, but now we have a full and extensible system.
    
* Optimize cached method
* Generate accounts and fiscal positions using Odoo methods (tax already did)
* README by fragments
* Add tests

cc @Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@sbidoul that comment should go in the other PR

**Comment by pedrobaeza** [comment]
Please tell what do you think about this for moving on this and v11 migration.

**Comment by sbidoul** [comment]
Looks good (superficial code review only). Thanks for this work!

**Comment by sbidoul** [comment]
(removed my misplaced comment)

**Review by rafaelbn — APPROVED** [review]
Thanks :+1:

**Comment by pedrobaeza** [comment]
OK, I have got full coverage for avoiding checking all corner cases, so merging with confidence.

**Pull request merged**
