### PR TITLE
[MIG] account_menu: Migration to 13.0

### PR DESCRIPTION
**Pull request by rven**
This module adds all missing menu entries for **Account** module.
* Chart of Account Templates
* Account Types
* Account Tags
* Account Group
* Bank Statements

In v12, this module installed 4 other modules:
* account_coa_menu
* account_group_menu
* account_tag_menu
* account_type_menu

Ref : https://github.com/OCA/account-financial-tools/issues/857

This PR removes the need of the single installation of the modules, all files are moved to this module.
The migration of the other modules is not needed anymore.

### CODE REVIEW

**Review by schout-it — APPROVED** [review]
lgtm

**Comment by pedrobaeza** [comment]
You should specify that this more than a migration, but a merge of several modules, isn't it?

**Comment by rven** [comment]
> You should specify that this more than a migration, but a merge of several modules, isn't it?

Of course, is it ok now?

**Comment by pedrobaeza** [comment]
Great, thanks!

**Review by StephanRozendaal — APPROVED** [review]
LGTM!

**Comment by rven** [comment]
@pedrobaeza could this be merged?

**Comment by pedrobaeza** [comment]
@rven sorry, you have to apply all the new black formatter stuff:

https://odoo-community.org/blog/the-oca-blog-1/post/black-isort-pre-commit-97

Please follow instructions in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0

**Comment by rven** [comment]
Done!

**Comment by alexis-via** [comment]
There is a mistake in this migration: the tag_ids field on account.tax existed in v12, but is DOESN'T exist on v13. So, when adding tax_ids on account.account.tag, it's not the reverse of a native M2M, it's a new field.
I'll fix that in my port to v14.

**Pull request merged**
