### PR TITLE
[10.0][ADD] Modules which allow an account adviser to update lock dates

### PR DESCRIPTION
**Pull request by benwillig**
An adviser is not able to update lock dates. Theses 2 modules add a wizard which allow account adviser users to update theses data.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why not having only one module for both?

**Comment by benwillig** [comment]
Because ```account_permanent_lock_move``` is an OCA module and if we got only one module, we force users to install ```account_permanent_lock_move``` even if it's not needed.

**Comment by pedrobaeza** [comment]
OK about the explanation on `account_lock_date_update`, but please include in `account_permanent_lock_move` directly the features of `account_permanent_lock_move_update`.

**Comment by benwillig** [comment]
But what if a user uses ```account_permanent_lock_move``` and doesn't want to allow his advisers to update lock dates?

**Comment by pedrobaeza** [comment]
Put a security group in the module, and you have that granularity.

**Review by adrienpeiffer — APPROVED** [review]
:+1:  works like a charm !

**Comment by sbidoul** [comment]
I think the module structure is good as is. Adding new module is also less disruptive for existing installations. 

Perhaps we should make  `account_permanent_lock_move_update` autoinstall=True.

**Review by gurneyalex — APPROVED** [review]

**Comment by gurneyalex** [comment]
@benwillig thanks, I just hit the issue on a customer's projet and your module is going to save my day.

**Review by ThomasBinsfeld — APPROVED** [review]
Functional and code review :+1:

**Pull request merged**
