### PR TITLE
[15.0][MIG]account_asset_management

### PR DESCRIPTION
**Pull request by manuelregidor**
Supersedes: https://github.com/OCA/account-financial-tools/pull/1339
Depends: https://github.com/OCA/reporting-engine/pull/609

### CODE REVIEW

**Comment by HaraldPanten** [comment]
@MiquelRForgeFlow @rafaelbn @ValentinVinagre @pedrobaeza

**Review by rafaelbn — APPROVED** [review]
Thank you! 👍

**Comment by kittiu** [comment]
Hello, should we wait for this fix to get merged?
https://github.com/OCA/account-financial-tools/pull/1323

**Comment by HaraldPanten** [comment]
I agree with @kittiu .

@manuelregidor do you mind adding https://github.com/OCA/account-financial-tools/pull/1323 ?

THX!

**Comment by manuelregidor** [comment]
@HaraldPanten @rafaelbn Commit https://github.com/OCA/account-financial-tools/pull/1323 added

**Review by antoniocanovas — APPROVED** [review]
Functional review Ok

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by HaraldPanten — APPROVED** [review]
Functional review

**Pull request merged**
