### PR TITLE
[FIX] leap year resilience in account_asset_management tests

### LINKED ISSUE #352: account_asset_management: tests are red
the tests of account_asset_management are red. 

https://travis-ci.org/OCA/account-financial-tools/jobs/108216715#L249

### PR DESCRIPTION
**Pull request by sbidoul**
fixes #352

### CODE REVIEW

**Comment by sbidoul** [comment]
travis lint issues are completely unrelated to this PR, I can't fix that now, sorry.

**Comment by pedrobaeza** [comment]
@sbidoul, I'm afraid they are related:

```
account_asset_management/tests/test_account_asset_management.py:143:80: E501 line too long (80 > 79 characters)
account_asset_management/tests/test_account_asset_management.py:146:80: E501 line too long (80 > 79 characters)
account_asset_management/tests/test_account_asset_management.py:159:80: E501 line too long (80 > 79 characters)
account_asset_management/tests/test_account_asset_management.py:162:80: E501 line too long (80 > 79 characters)
account_asset_management/tests/test_account_asset_management.py:233:80: E501 line too long (80 > 79 characters)
account_asset_management/tests/test_account_asset_management.py:236:80: E501 line too long (80 > 79 characters)
account_asset_management/tests/test_account_asset_management.py:241:80: E501 line too long (80 > 79 characters)
account_asset_management/tests/test_account_asset_management.py:244:80: E501 line too long (80 > 79 characters)
```

These are the real errors. The rest are only warnings. And they're introduced by your changes. You are using 80 chars instead of 79. The limitation is 80 cols, but this means 79 chars.

**Comment by sbidoul** [comment]
@pedrobaeza indeed, thanks for pointing it to me. Fixed. Apparently MQT is more strict that vim's pymode default config.

**Comment by pedrobaeza** [comment]
Thanks :+1:

**Comment by pedrobaeza** [comment]
Merging this for solving Travis issues.

**Pull request merged**
