### PR TITLE
[11.0][mig][account_fiscal_year]

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
Account Fiscal Year
===================

This module extends `date.range.type` to add `fiscal_year` flag.

Override official `res_company.compute_fiscal_year_dates` to get the
fiscal year date start / date end for any given date.
That methods first looks for a date range of type fiscal year that
encloses the give date.
If it does not find it, it falls back on the standard Odoo
technique based on the day/month of end of fiscal year.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I haven't understood yet the need for this module in financial reports. Can you explain me?

**Comment by JordiBForgeFlow** [comment]
This PR is intended to supersede https://github.com/OCA/account-financial-tools/pull/573. We'll need to merge it fast, because https://github.com/OCA/account-financial-reporting/pull/367 has been merged assuming that this module exists (my fault)

**Comment by JordiBForgeFlow** [comment]
@pedrobaeza The dependency was already there in v10. I maintained it.

**Comment by pedrobaeza** [comment]
Yeah, but for what? Maybe it's better to remove the dependency.

**Comment by sbidoul** [comment]
The dependency of account_financial_report_qweb on account_fiscal_year should not be mandatory.

account_fiscal_year is only useful for companies with a fiscal year that does not match the calendar year (at least it was in v9 at Sorrento...). Not sure for v11.

**Comment by JordiBForgeFlow** [comment]
It is being used here:
https://github.com/OCA/account-financial-reporting/blob/11.0/account_financial_report/wizard/trial_balance_wizard.py#L63

**Comment by JordiBForgeFlow** [comment]
and here: https://github.com/OCA/account-financial-reporting/blob/11.0/account_financial_report/wizard/general_ledger_wizard.py#L71

**Comment by sbidoul** [comment]
[compute_fiscalyear_dates is from Odoo](https://github.com/odoo/odoo/blob/11.0/addons/account/models/company.py#L75)

It's enriched by account_fiscal_year, but it should still work if account_fiscal_year is absent.

**Comment by sbidoul** [comment]
Actually account_fiscal_year is only needed when the fiscal year duration is longer or shorter than a calendar year. My comment above is incorrect, because Odoo does have a "fiscal year last day".

**Comment by JordiBForgeFlow** [comment]
OK, I am now removing the dependency. I'll ping you on the new PR.

Meanwhile it is not too bad that you review this PR :)

**Review by sbidoul — APPROVED** [review]

**Comment by JordiBForgeFlow** [comment]
I have squashed the unnecessary Transifex commits

**Review by pedrobaeza — APPROVED** [review]
I have squashed the rest of the commits by author/logic and I'm going to merge as this is straight-forward

**Pull request merged**
