### PR TITLE
[11.0][account_loan] Change logger level on import dependency

### PR DESCRIPTION
**Pull request by jcoux**
According to the guidelines:
https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#importerror

Change the logger level from `error` to `debug`.

### CODE REVIEW

**Review by simahawk — APPROVED** [review]

**Comment by JordiBForgeFlow** [comment]
@jcoux Was there any specific reason for changing this?

**Comment by jcoux** [comment]
@jbeficent The reason is that I use this repository in my project, without install this module, and I have a the missing dependency error for nothing. I wanted to avoid to have useless errors.

**Review by guewen — APPROVED** [review]
This is described here https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#importerror
It makes no sense to show an error log which will then appear in your monitoring, only because you don't have a dependency for an addon you don't use.

**Review by Tonow-c2c — APPROVED** [review]
LGTM

**Pull request merged**
