### PR TITLE
11.0 mig account balance line

### PR DESCRIPTION
**Pull request by rruebner**

### CODE REVIEW

**Comment by feketemihai** [comment]
@rruebner Can you please squash transifex commits..

**Review by feketemihai — APPROVED** [review]
Squashing commits would be good, but they are not too much, so no impediment.

**Review by pedrobaeza — APPROVED** [review]
Yeah, at least adjacent "OCA Transbot..." commits.

**Review by adrienpeiffer — APPROVED** [review]
👍

**Pull request merged**
