### PR TITLE
[14.0][IMP] account_loan: remove numpy from explicit requirements

### PR DESCRIPTION
**Pull request by etobella**
We need to force numpy version 1.15 in order to make it work inside runboat, but it should not be necessary

### CODE REVIEW

**Comment by HekkiMelody** [comment]
The tests are still failing like they were for me https://github.com/OCA/account-financial-tools/actions/runs/4369202540/jobs/7642722633#step:8:104 (and it's even more worrying that they're showing green in spite of the error)

**Review by flotho — APPROVED** [review]
LGTM

**Comment by francesco-ooops** [comment]
> The tests are still failing like they were for me https://github.com/OCA/account-financial-tools/actions/runs/4369202540/jobs/7642722633#step:8:104 (and it's even more worrying that they're showing green in spite of the error)

@etobella @flotho what about this?

**Pull request merged**
