### PR TITLE
[REF] adopting account_menu

### PR DESCRIPTION
**Pull request by legalsylvain**
Simple PR : Adopting ``account_menu``

### CODE REVIEW

**Comment by legalsylvain** [comment]
>  if interested, create a pull request to add your GitHub login to the maintainers key of the addon manifest.

@OCA-git-bot : good idea! I will think about it. :-)

**Comment by pedrobaeza** [comment]
:rofl:

/ocabot merge nobump

**Comment by pedrobaeza** [comment]
Ey, wait, you have put `menu` instead of `maintainers`.

**Comment by legalsylvain** [comment]
> Ey, wait, you have put menu instead of maintainers.

Sorry. my bad. Fixed.

**Pull request merged**
