### PR TITLE
13 account chart refactor update taxes

### PR DESCRIPTION
**Pull request by luc-demeyer**

### CODE REVIEW

**Comment by luc-demeyer** [comment]
I encountered a situation where I needed to sync some tax objects from the templates but some account settings on the repartition lines were customised and should be preserved.
Hence I started with adding two more options for the tax repartition lines-
- Update Tax Account
- Update Tax Tags
image

While implementing & testing this enhancement I came accross a whole set of issues in the tax update logic:
- same issue as in https://github.com/OCA/account-financial-tools/pull/1052
- accounts not set when creating new repartition lines
- cash basis accounts not handled in 'deferred' mode
- tags settings incorrect

In order to fix it, I implemented logic based upon the approach in account/models/chart_template.py for tags and deferred account settings.

This PR also makes it clear that we should more unit tests to this module.

**Comment by MiquelRForgeFlow** [comment]
Hey @luc-demeyer I have been testing. Imagine in v12 you have a bill and put a tax (that have tax children) in a line. Then when migrating to v13, suppose new tax repartition lines are generated for each tax without tax children and the journal items are updated to point to those tax repartition lines. But happens in v13 that some localizations (ie, l10n_es) have substituted those old taxes with tax children for taxes with multiple tax repartition lines. I expected that running this module tool of update chart template after migration, I could adapt to the new localization taxes. But what I found was the following: in the journal items (move lines) the tax_repartition_line_id field is not updated. I mean, the tax repartition lines generated in the migration for tax children are still there but inactive. But those linked tax repartition lines should have been substituted for the new multiple repartition lines of their substituting taxes. It surprises me to see that the tax_ids field is correctly updated with new taxes but not the tax_repartition_line_id field.

I hope I explained the problem and could you test what I am saying. Let me know if I can help with anything.

**Comment by luc-demeyer** [comment]
@MiquelRForgeFlow 
The purpose of this module is to synchronise the tax objects with the templates.
That means that a newly encoded invoice will take into account the updated taxes but legacy account.move.line entries are not updated.

We could add a wizard doing this to this module but I think we should make a new module for that (I'll do this exercise next month for a couple of customer projects hence we may use this experience as a starting point for such an OCA module).

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
@luc-demeyer In the method diff_fields, it can break in `real[key]` if key not in real. Can you fix this in a way to avoid the break?

**Comment by MiquelRForgeFlow** [comment]
@luc-demeyer I made a PR to your branch here https://github.com/luc-demeyer/account-financial-tools/pull/14

**Comment by luc-demeyer** [comment]
@MiquelRForgeFlow 
Thanks for proposing a solution to protect against a key error.
I don't think though that the proposed solution is the right one.
if we get a key error than there is probably something wrong in the self.fields_to_ignore(template._name) method.
Can you give me the concrete steps to reproduce this key error ?

**Comment by MiquelRForgeFlow** [comment]
@luc-demeyer for example, having a custom module that defines a new field for account.tax.template but not in the account.tax model. Then, if you don't have "expected", then breaks in the second "if".

BTW, if you look the code in previous versions like v12, you will see that the "try except" solution was already implemented.

**Comment by luc-demeyer** [comment]
@MiquelRForgeFlow 
Adding a field to the template without the corresping real object seems strange to me but I suppose you have a valid use case for that. 
I suggest to limit the number of lines in the try/except clause  to the place where the problem can occur and add a _logger message since in most cases such an exception will be caused by an error in this module.
Concerning your custom module: I think it could be a good idea to add an auto-install account_chart_update_custom module to avoid ending up in this key exception.

**Comment by MiquelRForgeFlow** [comment]
> I suggest to limit the number of lines in the try/except clause

I don't think it can be limited more. See in https://github.com/OCA/account-financial-tools/blob/12.0/account_chart_update/wizard/wizard_chart_update.py#L604L621, that's the same group of lines affected.

> Adding a field to the template without the corresping real object seems strange to me but I suppose you have a valid use case for that.

Use case: https://github.com/OCA/l10n-spain/pull/1443

**Comment by MiquelRForgeFlow** [comment]
@luc-demeyer cold you rebase? first commit is already in branch 13.0

**Comment by luc-demeyer** [comment]
@MiquelRForgeFlow 
I fixed the issue reported by you this way https://github.com/OCA/account-financial-tools/pull/1056/commits/018b2900c197d289d16471b5fc39f601e29fd0a9
Please check if ok.

**Comment by pedrobaeza** [comment]
This branch is not clean. Please rebase properly and let the specific commits.

**Comment by gaikaz** [comment]
@luc-demeyer 
As Pedro mentioned, could you please rebase your commits, so we could review?

**Comment by pedrobaeza** [comment]
Superseded by #1251

**Pull request closed without merging**
