### PR TITLE
Change separator of author in manifest to be displayed correctly in apps...

### PR DESCRIPTION
**Pull request by yvaucher**
....odoo.com

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I didn't know that multiple authors are now correctly handled.

:+1:

**Comment by yvaucher** [comment]
@pedrobaeza I think it is new
e.g.:https://www.odoo.com/apps/modules/8.0/base_report_to_printer/

**Comment by sbidoul** [comment]
:+1: 

Interesting evolution. It still remains difficult to give proper visibility to contributors, which, as @pedrobaeza once mentioned, sometime have done more for a module than the original author.

**Comment by guewen** [comment]
:+1:

**Pull request merged**
