### PR TITLE
[16.0][MIG] account_balance_line

### PR DESCRIPTION
**Pull request by destroT**
I removed views no longer needed (account_move_line_balance_tree_grouped, account_move_line_balance_audit_tree)

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This one is supposedly not needed anymore, as the core includes this field.

**Comment by destroT** [comment]
I understand, thank you

**Comment by pedrobaeza** [comment]
But if you think it brings some value, please tell.

**Comment by destroT** [comment]
After all, I don't think it adds much additional value.
In earlier versions it was more useful, but now it only shows the `balance` field without changing manually the optional fields in the tree view.

**Comment by pedrobaeza** [comment]
OK, thanks for checking.

**Pull request closed without merging**
