### PR TITLE
[ADD][account_credit_control] Add an additional text after the details of the credit control summary report

### PR DESCRIPTION
**Pull request by benwillig**
Migration of https://github.com/OCA/account-financial-tools/pull/303

### CODE REVIEW

**Review by adrienpeiffer — APPROVED** [review]
As it merged in version 8.0, It should have been in the migration, So :+1:

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Please change module version

**Comment by benwillig** [comment]
@pedrobaeza Module version updated

**Comment by pedrobaeza** [comment]
As it requires to update module, better to change middle number (https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#version-numbers), but it's not blocking (not too many people cares too much about the version, but at least we have a different one).

**Comment by benwillig** [comment]
I agree with your point of view. I changed the middle number.

**Comment by pedrobaeza** [comment]
hehe, I mean the middle from the module version (that's 10.0.1.**1**.0), but hey, no problem, I change it while merging. Thanks for this.

**Review by pedrobaeza — APPROVED** [review]

**Comment by benwillig** [comment]
Ups sorry. Thanks!

**Pull request merged**
