### PR TITLE
[MIG] account_invoice_currency: Migration to 11.0

### PR DESCRIPTION
**Pull request by aitorbouzas**
Migrated the module. It works exactly the same, no new features, no changes.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:clap: 

This module has less importance now in >v9, as Odoo includes most of the currency fields already. Are you directly using this in any place?

**Comment by aitorbouzas** [comment]
Yes, i'm planning to use it for mod347 since it's a dependency. Maybe the dependency must be removed? Anyway, this is migrated now.

**Comment by pedrobaeza** [comment]
Yeah, having it migrated is a plus, but I think we can remove it. I plan to make a big refactoring on 347, so migrating it now maybe it's not a good idea. Any way, you don't need until the end of the year, isn't it?

**Review by pedrobaeza — APPROVED** [review]

**Comment by aitorbouzas** [comment]
I don't need it right now, but i'll need it as soon as possible for testing purposes (new big customer). I'll wait for you to make the refactoring.
Also, tests were failing locally for an unknown reason, let's see if it was because of my build...

**Comment by pedrobaeza** [comment]
Here they are correct (See Travis green already)

**Comment by aitorbouzas** [comment]
Uh, ok. I was having an error in the test line that was creating a new res.partner with just 'name': 'Test partner'. The error was saying that the column "sale_warn" could not have null value...

**Comment by pedrobaeza** [comment]
That's because you have sale installed in your DB. One way to avoid that problem is to add:
```python
class Test(common.<...>Case):
    at_install = False
    post_install = True
```
This way, tests are executed when all modules have been loaded, so no more problem with new required fields added by other modules.

**Review by feketemihai — APPROVED** [review]

**Pull request merged**
