### PR TITLE
[15.0][MIG]base_vat_optional_vies: migration from 14.0 to 15.0

### PR DESCRIPTION
**Pull request by AlvaroTForgeFlow**
Standard migration from 14.0 to 15.0

@ForgeFlow

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
The functional test LGTM. However, the readme shows this:

```
*NOTE*: Although VIES validation is set in your company, this validation
will not block VAT ID write (main difference to Odoo standard behavior) if this
VAT ID is valid in its country.
```

But that is not True, not in this migration, and not in stable version in v14.0. @HaraldPanten  do you know if the readme is incorrect?

**Comment by HaraldPanten** [comment]
Hi @AaronHForgeFlow The README looks correct to me.

With Odoo standard, if you choose to use VIES validation user will be able to write only valid VIES VAT numbers for contacts. If VAT is not validated by VIES, a new contact can not be saved.

With this module, user will have a checkbox in contact's form to let you know if VIES has been validated or not, but you'll be able to save a new contact, even if VIES hasn't been validated. User is not forced to have a valid VIES VAT number for each new contact.

Where did you find the issue?

THX

**Comment by AaronHForgeFlow** [comment]
@HaraldPanten  I tested this migration and I realized I was not able to save a new contact because the VIES could not been validated. That is same as standard behavior. However, I tested in v14 and the behavior is the same, you cannot save a contact with incorrect VIES. It seems to me that this is a bug that needs to be fixed in v14 as well.

**Comment by HaraldPanten** [comment]
I see the failing that you're mentioning in runboat. But it has been working properly for a long time...

Might it be related to any changes from Odoo side?

**Comment by AaronHForgeFlow** [comment]
I see there are several commits on that module during 2021 but I am not able to identify the one that makes this module to fail. Could it be this one https://github.com/odoo/odoo/commit/0268986b60477c7fb46d93f45f3355f546f0155c#diff-9f9999aaef19572635590a2e911ff2a96a60c2cfc8049265ae9c6238796f8755 ?

**Comment by HaraldPanten** [comment]
> I see there are several commits on that module during 2021 but I am not able to identify the one that makes this module to fail. Could it be this one [odoo/odoo@0268986#diff-9f9999aaef19572635590a2e911ff2a96a60c2cfc8049265ae9c6238796f8755](https://github.com/odoo/odoo/commit/0268986b60477c7fb46d93f45f3355f546f0155c#diff-9f9999aaef19572635590a2e911ff2a96a60c2cfc8049265ae9c6238796f8755) ?

Hhhmmm... I don't think so, as we installed the module after this date in V14 and we didn't face any issue.

Steps to reproduce:

1- Create a new contact (company) with a valid VAT number.

2- The VAT number musn't be valid in VIES. Try, for example --> B47747530 (Spain)

3- Odoo doesn't allow you to save this new contact because --> _The VAT number [B47747530] for partner [test] either failed the VIES VAT validation check or did not respect the expected format ESA12345674._

** I also tried ESB47747530

Could you shed some light here, @pedrobaeza ? Any clue?

**Comment by pedrobaeza** [comment]
I can't say without analyzing, and right now I'm not able to.

**Comment by HaraldPanten** [comment]
@AaronHForgeFlow I've seen a "strange" behaviour.

1- Create a new contact (INDIVIDUAL) with a valid VAT number.

2- The VAT number musn't be valid in VIES. Try, for example --> 45098604C (Spain)

3- No validation issue 🤔

**Comment by AaronHForgeFlow** [comment]
@HaraldPanten Individual never pass the VIES check, only companies, am I wrong?

**Comment by HaraldPanten** [comment]
> @HaraldPanten Individual never pass the VIES check, only companies, am I wrong?

Yes, it's for companies only. Maybe I didn't explain me well enough. What I meant is:

1- If you try to create a new contact (company) with this module installed, you'll have a validation error.

2- If you create the contact as an individual and then you change the contact to a company the workflow of the module is correct.

So... there's something strange in the create that doesn't allow to use the module properly.

Did you try in your local/client environment? It's working fine for us in V14

**Comment by AaronHForgeFlow** [comment]
I tested in a blank database in my local, for both, v14 and this PR.

The trigger of the check is the change in the vat or the country of the partner, so there should be no difference between the create and the edition of the record.

I do not see in the code of this module anything to catch the exception and continue so that it is why I though that was not implemented.

**Comment by HaraldPanten** [comment]
@ValentinVinagre could you check that with Aarón, and try to find the issue or if anything has changed lately? THX!

**Comment by AaronHForgeFlow** [comment]
I think now it works as the readme says, so LGTM ;)

**Review by AaronHForgeFlow — APPROVED** [review]

**Review by HaraldPanten — APPROVED** [review]

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
