### PR TITLE
[14.0][FIX] Add entry_number field in ledger reports views

### PR DESCRIPTION
**Pull request by Shide**
Add `entry_number` field in ledger reports views.
- General Ledger
- Partner Ledger

MT-885 @moduon @yajo @rafaelbn

### CODE REVIEW

**Review by yajo — APPROVED** [review]
I don't know where to go in the UI to review this, but code looks ok.

**Review by ghost — APPROVED** [review]
Checked General Ledger and Partner Ledger and LGTM!

**Review by HaraldPanten — APPROVED** [review]
LGTM

**Pull request merged**
