### PR TITLE
[11.0][MIG] account_cost_center

### PR DESCRIPTION
**Pull request by astirpe**

### CODE REVIEW

**Review by tbaden — APPROVED** [review]
thanks for the work 👍 
I did a code review: LGTM

**Review by etobella — COMMENTED** [review]
Code Reviewed and tested on runbot!
LGTM :+1:

**Comment by tbaden** [comment]
@etobella you have to use the "review changes" button in the "files changed" tab to approve this PR
https://odoo-community.org/page/review

**Review by AaronHForgeFlow — COMMENTED** [review]
Hi @astirpe I created two invoices for different cost centers on runbot and seems the cost center it is not consistent between the invoice and the journal item. See invoice: http://3371233-806-990f50.runbot3.odoo-community.org/web#id=11&view_type=form&model=account.invoice&menu_id=132&action=208

**Comment by AaronHForgeFlow** [comment]
@astirpe I just realized this issue is related to this reason: Users can change the cost center in the invoice and the invoice lines are not updated accordingly. Regards.

**Comment by astirpe** [comment]
@aheficent right, thanks!

**Review by etobella — APPROVED** [review]

**Comment by etobella** [comment]
> @etobella you have to use the "review changes" button in the "files changed" tab to approve this PR
> https://odoo-community.org/page/review

I did it there, but I forgot to check the approve, sorry

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Functional ok

**Comment by astirpe** [comment]
@pedrobaeza this migration PR is ready to merge, would you check it?
Also the V10 and V9 migration PRs are ready to merge:

- V10: https://github.com/OCA/account-financial-tools/pull/659
- V9: https://github.com/OCA/account-financial-tools/pull/442

**Comment by pedrobaeza** [comment]
OK, merging according previous reviews.

**Pull request merged**
