### PR TITLE
refactore asset xls report to ease creation of custom report

### PR DESCRIPTION
**Pull request by florian-dacosta**
In case we want to display different assets in a custom report, we just have to overwrite the query and not the whole big method `_acquisition_report`, `_active_report` or `_removal_report`

### CODE REVIEW

**Comment by luc-demeyer** [comment]
@florian-dacosta 
The PR looks ok to me
One question: what's the use case behind the 'custom' report ?
If it's a general requirement (e.g. 'draft' vs 'confirmed' assets) than we can better add filter options to the reporting wizard screen (while of course keeping the queries in separate methods as proposed by your PR).

**Comment by florian-dacosta** [comment]
In the case of my client, he just wants to remove the removed asset from the active tab of the xls report because they already are present in the remove tab.

And he wants to add fields in the remove tab, but I do not really know how to do this simply without overwrite all `_removal_report` method.

I just thought that keeping the queries in seperate methods can't hurt but can help in some cases.
I am not sure if we can make other improvements to ease the creation of a custom report. (like to ease the addition of fields like 'fy_start_value')

So yeah, I guess this case is a general requirement, but since the assets present in the excel tabs are taken from the queries, I am not sure what you mean when you say ' we can better add filter options to the reporting wizard screen'

**Comment by luc-demeyer** [comment]
@florian-dacosta 

1) In the case of my client, he just wants to remove the removed asset from the active tab of the xls report because they already are present in the remove tab

Strange requirement. The report is a legal report and hence you want to get a complete overview of all depreciations during the reporting year (and hence also the those from the assets removed during the fiscal year). 
This is in imho not a general requirement (can indeed be done via a custom module where you modify the _active_report query. 

2) And he wants to add fields in the remove tab, but I do not really know how to do this simply without overwrite all _removal_report method.

Just add those fields to the template via inherit (cf. account_asset.py, def xls_removal_template, add the new fields and also update the fields list (via def _xls_removal_fields).

3) I just thought that keeping the queries in seperate methods can't hurt but can help in some cases.
I am not sure if we can make other improvements to ease the creation of a custom report. (like to ease the addition of fields like 'fy_start_value')

Separating the query is indeed better, hence I support this PR.
Adding new fields is easy and foreseen (cf. my answer to point 2) but in this case I don't see the need since all the info in the active report. I also checked this report with several accountants, hence maybe the easiest solution is to challenge the customer 'requirement'. 

4) So yeah, I guess this case is a general requirement, but since the assets present in the excel tabs are taken from the queries, I am not sure what you mean when you say ' we can better add filter options to the reporting wizard screen'

Currently the only filters on the wizard screen are the 'fiscal year' and the 'parent asset'. On my (low priority) wish list is to add also the option to include draft assets in the report (keep 'confirmed' as the default but allow to also include draft ones).

**Comment by sebastienbeau** [comment]
Even if our customer have strange need :S , having the request in inheritable method is cool. So :+1:

**Comment by chafique-delli** [comment]
The PR is ok for me. 
So :+1:

**Comment by luc-demeyer** [comment]
@florian-dacosta do you intend to also make a PR with this improvement for V8 ?

**Comment by florian-dacosta** [comment]
yeah I guess it is better to do it also in v8, I'll try to make it this week.

**Pull request merged**
