### PR TITLE
[10.0][FIX] account_credit_control: fix translation in report and style

### PR DESCRIPTION
**Pull request by adrienpeiffer**

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
It should be 10.0.1.2.0 as it requires module update, but it's not so much important

**Comment by adrienpeiffer** [comment]
Style problem was fixed in another PR. Remains the translation one.

**Comment by adrienpeiffer** [comment]
@benwillig Can you take a look on this one ?

**Review by benwillig — APPROVED** [review]
LGTM :+1:

**Review by ThomasBinsfeld — APPROVED** [review]
Code review :+1:

**Comment by adrienpeiffer** [comment]
@pedrobaeza I think this one is ready to merge :small_airplane:

**Pull request merged**
