### PR TITLE
[MIG][15.0] product_category_tax

### PR DESCRIPTION
**Pull request by JoanMForgeFlow**
Standard migration to version 15.0. depends on https://github.com/OCA/product-attribute/pull/978

### CODE REVIEW

**Review by BernatPForgeFlow — APPROVED** [review]

**Review by mariadforgeflow — APPROVED** [review]
Functional review. LGTM!

**Comment by LoisRForgeFlow** [comment]
@dreispt this depends on https://github.com/OCA/product-attribute/pull/978, can you merge it to able to move forward? thanks

**Comment by JoanMForgeFlow** [comment]
@dreispt could we merge this PR?
thanks in advance

**Pull request merged**
