### PR TITLE
[15.0] dotfiles update needs manual intervention

### PR DESCRIPTION
**Pull request by etobella**
Dear maintainer,

After updating the dotfiles, `pre-commit run -a`
fails in a manner that cannot be resolved automatically.

Can you please have a look, fix and merge?

Thanks,

### CODE REVIEW

**Comment by matteoopenf** [comment]
@pedrobaeza  is possible merge to fix pre-commit here  https://github.com/OCA/account-financial-tools/pull/1635?
thank you

**Review by matteoopenf — APPROVED** [review]

**Review by patrickt-oforce — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@matteoopenf you need to supersede the PR and fix remaining pre-commit stuff.

**Comment by matteoopenf** [comment]
> @matteoopenf you need to supersede the PR and fix remaining pre-commit stuff.

ok thank you for the help I will do

**Comment by matteoopenf** [comment]
@etobella have you any idea to fix?

**Comment by etobella** [comment]
Don't worry. I will do it directly here

/ocabot merge patch

**Comment by matteoopenf** [comment]
> Don't worry. I will do it directly here
> 
> /ocabot merge patch

thank you so much for the help

**Pull request merged**
