### PR TITLE
80 asset_management compute_depreciation_board fix

### PR DESCRIPTION
**Pull request by luc-demeyer**
correction of depreciation board calculation when creating init entries in (not yet) defined fiscal years

### CODE REVIEW

**Comment by laetitia-gangloff** [comment]
Hello,

I tested my use case and it works as expected.

Thank you

:+1:

**Comment by alexis-via** [comment]
Code review :+1:

**Comment by luc-demeyer** [comment]
two positive reviews.
In the meanwhile I also installed this fix at a couple of customer sites with positive results.
I think this one is ready for merge.

**Comment by pedrobaeza** [comment]
Can you please avoid SQL sentences and use a simple ORM search?

**Comment by luc-demeyer** [comment]
I am not sure if this should be blocking for the merge since:
- I am replacing a buggy sql statement by a corrected one, hence it's better to have the corrected version published
- this module is full of SQL statements. Replacing all of the SQL by ORM would be a major task with the risk of breaking the logic and with potential serious negative performance impacts. The SQL clause that I am correcting is in the depreciation board calculation. If you have thousands of assets with monthly depreciations than the ORM approach could bring down the system (you have a recompute of all tables when the recompute trigger has been set, e.g. when changing fiscal year duration).
- this SQL call doesn't bypass the ORM ACL's since the select is within a set of depreciation line ids which have been looked up via an ORM search.

**Comment by sbidoul** [comment]
@pedrobaeza moving to ORM, although desirable, would be a major undertaking for this module, and is out of scope for this PR.

:+1:

**Comment by pedrobaeza** [comment]
I'm talking only to put this patch in ORM, not to move all module to ORM. It's very simple and more readable:

``` python
depr_line_obj = self.pool['account.asset.depreciation.line']
fy_amount_check = 0.0
line_ids = depr_line_obj.search(
    cr, uid, [('id', 'in', posted_depreciation_line_ids),
              ('line_date', '>=', entry['date_start']),
              ('line_date', '<=', entry['date_stop'])],
    context=context)
if line_ids:
    line = depr_line_obj.browse(cr, uid, line_ids[0], context=context)
    fy_amount_check = line.amount or 0.0
else:
    fy_amount_check = 0.0
```

**Comment by luc-demeyer** [comment]
@pedrobaeza 
Pedro,
the SQL call contains a SUM(amount) statement.
Your suggestion does not include the "SUM" logic.
Imagine now a table recompute for a company with 5000 assets over 20 years with monthly depreciations -> ORM approach requires 5000 times python loop to sum of (up to) 20 x 24 = 480 iterations.
I don't think we should we go that path. The ORM is great for rapid application development but not always the best approach when  it comes to performance.

I therefor still believe that this PR is ready for merge.

**Comment by pedrobaeza** [comment]
OK, I miss that, but it's only to put a sum. I'm not going to enter now in a debate of ORM/SQL, but for sure you can develop efficiently without SQL. If the full module is not oriented as how Odoo should work with ORM (store computed fields for example), indeed this PR can't change that, but I'm now starting to use it, and I'm very dissapointed to see SQL in all places, and performance is not an excuse for making each operation in SQL.

**Comment by jgrandguillaume** [comment]
Hi,

I agree that we should use ORM rather than SQL. But it is still good to have this fix, So I'm :+1: 

Regards,

Joël

**Pull request merged**
