### PR TITLE
[15.0][MIG]account_fiscal_month: Migration to 15.0

### PR DESCRIPTION
**Pull request by bizzappdev**

### CODE REVIEW

**Comment by bizzappdev** [comment]
Ready for Review

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
@bizzappdev you should remove the WIP in the title 😉

**Review by JuanyDForgeflow — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]
code LG

**Comment by AaronHForgeFlow** [comment]
I did not merge this because I am wondering here if similar refactor is needed in the module. Same as it was done in https://github.com/OCA/account-financial-tools/commit/bca798b61dcf12e4ada8f34ce833503d6664a139#diff-fbccdc5e9d169fb654a5c7024c6ceeeab6fc035879cd081a8122764a88f67056 for the account_fiscal_year module. It is weird to me that fiscal months are date ranges but fiscal years are independent objects.

**Review by AaronHForgeFlow — APPROVED** [review]
As long as Odoo introduced financial years but not financial months, then it is ok to me keep using date ranges for financial months.I would rather like financial years also to be like that, but I am afraid that cannot be changed right now.

**Comment by AaronHForgeFlow** [comment]
@bizzappdev  can you please rebase?

**Comment by MiquelRForgeFlow** [comment]
It's not a problem of rebase. It's github having degraded operations.

**Comment by AaronHForgeFlow** [comment]
@MiquelRForgeFlow ok, let's try again

/ocabot merge nobump

**Pull request merged**
