### PR TITLE
7.0 account check deposit

### PR DESCRIPTION
**Pull request by sebastienbeau**

### CODE REVIEW

**Comment by alexis-via** [comment]
Great module ! :+1:

**Comment by sbidoul** [comment]
A couple of hidden files to remove:
- account_check_deposit/report/.directory
- account_check_deposit/report/.mako

**Comment by sbidoul** [comment]
account_data.xml creates a journal linked to the main company.
Should that not be in the demo data section?

**Comment by alexis-via** [comment]
@sbidoul If you want to use this module, you need a journal dedicated to checks received. That's why we decided to put it in the "standard" data instead of the demo data: it just saves configuration time when you deploy this module in production.

**Comment by sbidoul** [comment]
@alexis-via yes I see the use. In some circumstances however, you could imagine that base.main_company has no chart of account? Not blocking for me though.

So :+1: (code review only, as I work in a country where checks have been deprecated before I was born :smile:)

**Comment by brother-bernard** [comment]
Essential when receiving a lot of bank checks (eg for donations or mail orders). The module works fine :+1:

**Pull request merged**
