### PR TITLE
[MIG] base_vat_optional_vies: Migration to 14.0

### PR DESCRIPTION
**Pull request by jcbr87**
Base_vat_optional_vies module migration

### CODE REVIEW

**Comment by jcbr87** [comment]
Hello,
I have carried out according to the OCA procedure for migration. If possible, tell me what else I need to do for the change to be approved.
Thanks

**Comment by jcbr87** [comment]
Hello,
Can someone review this repository it shows me an error in the codecov/project but as far as I can see it is for another module that I am not touching in my branch.
Thanks

**Comment by pedrobaeza** [comment]
No need to worry about that one. Focus on green pre-commit + runbot + Travis.

**Comment by jcbr87** [comment]
@pedrobaeza , How can I get it to run the pre-commit in the repository.

**Comment by pedrobaeza** [comment]
Approved for running

**Comment by jcbr87** [comment]
@pedrobaeza I need to do something else to continue the process.

**Comment by pedrobaeza** [comment]
Squash your migration commits and get reviewers from your pull request. You can review other PRs and ask in exchange that they review yours.

**Comment by jcbr87** [comment]
@pedrobaeza I do not have permission to ask any collaborator to review, or just by a note in the comments?

**Comment by pedrobaeza** [comment]
Put a note pinging people.

**Comment by jcbr87** [comment]
@dalonsod Hello, can you validate this PR please.

**Comment by jcbr87** [comment]
@peremg Hello, can you validate this PR.
Thanks

**Comment by jcbr87** [comment]
@cmanuelalvarez11 Hello, can you validate this PR.
Thanks

**Comment by jcbr87** [comment]
@jaiodoo Hello, can you validate this PR.
Thanks

**Review by dalonsod — APPROVED** [review]
Tested on runbot, LGTM

**Comment by dalonsod** [comment]
@jcbr87 regarding to codecov error, you should make a rebase

**Comment by jcbr87** [comment]
@dalonsod I have tried other PR but I did not stay, as they already told me that it was not necessary because I left it like that. But if you have a guide it would be great.
Thanks

**Comment by dalonsod** [comment]
> @dalonsod I have tried other PR but I did not stay, as they already told me that it was not necessary because I left it like that. But if you have a guide it would be great.

Well, I'm not sure if PR will be merged without making rebase before... but it should be easy. Please try `git fetch origin` and `git rebase origin/14.0` . Then, make a force push.

And also a squash for your latest commits should be needed, as @pedrobaeza said.

**Comment by pedrobaeza** [comment]
The rebase is performed by ocabot merge command, so no need of that, but yes for the squashing, as we don't want a dirty commit history.

**Comment by jcbr87** [comment]
@pedrobaeza I already think I have squash the comments. I don't know if I need to do anything else.
Thanks

**Comment by pedrobaeza** [comment]
I don't think so:

Selección_007

You have made a merge commit, not squashing one. See https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

**Comment by jcbr87** [comment]
@pedrobaeza Now I do believe that I have done squash.

**Comment by pedrobaeza** [comment]
There's still a rebel one:

Selección_008

**Comment by jcbr87** [comment]
@pedrobaeza Now I do believe that I have done squash.

**Comment by pedrobaeza** [comment]
Yes, there's now only one migration commit.

**Comment by jcbr87** [comment]
@pedrobaeza I don't know if I need to do anything else  for merge.
Thanks

**Comment by pedrobaeza** [comment]
A second review of the content is needed, and I'm not the right person for that. You can review other PRs, and ask in exchange that they review yours.

**Comment by jcbr87** [comment]
@dreispt Hello, can you validate this PR please.
Thanks

**Review by pere-aquarian — APPROVED** [review]

**Pull request merged**
