### PR TITLE
[14.0][ADD] account_asset_stock_move

### PR DESCRIPTION
**Pull request by kittiu**
Normally, asset is created when vendor bill is confirmed (asset profile is set on invoice line)

But in case real time stock is used, stock move will create account moves, and it is possible to create asset on confirm of stock picking.

This should be useful for organization that want to create asset during stock in and not when confirm vendor bill.

- [x] Test

### CODE REVIEW

**Comment by newtratip** [comment]
@kittiu, please check https://github.com/OCA/account-financial-tools/pull/1240/commits/018292a19f0a889def6f6d32a85f3ddcea2fd359

**Comment by kittiu** [comment]
> @kittiu, please check [018292a](https://github.com/OCA/account-financial-tools/commit/018292a19f0a889def6f6d32a85f3ddcea2fd359)

I am ok

**Review by ps-tubtim — APPROVED** [review]
Code LGTM.

**Review by Saran440 — APPROVED** [review]

**Comment by marcelsavegnago** [comment]
cc @douglascstd @augustodinizl

**Comment by tv-openbig** [comment]
@kittiu Do you want to merge this PR ? I have reviewed the functionality locally and it is very useful. 

Bildschirmfoto 2023-09-18 um 13 49 30

In the screenshot you can see that these assets was created from a stock move initiated by a manufacturing order (self produced asset).

**Pull request merged**
