### PR TITLE
[14.0][MIG] account_chart_update: Migration to 14.0

### PR DESCRIPTION
**Pull request by Reyes4711-S73**
Standard migration to 14.0

### CODE REVIEW

**Comment by omar7r** [comment]
Functionally works, thanks you.
A little improvement if you agree: Should be possible change the type of record, maybe the wizard detects a register as new and other to deactivate, but maybe, these two records are the same, then we could manually delete the deactivate record and convert new to update in the other record, and the register will be updated correctly. It'd be enough deleting "readonly=True" on "type" fields.

Regards

**Comment by pedrobaeza** [comment]
@omar7r changing that is not good for ux. If you don't want to delete such record, just remove the line instead of changing the type

**Comment by omar7r** [comment]
@pedrobaeza But I want update the other record nor insert neither deactivate it. In 12.0 we did it in a complementary module (https://github.com/Comunitea/external_modules/tree/12.0/account_chart_update_allow_edit) and in the majority of version migrations we need change the type, for updating and recreate xml_ids in a few taxes. If I don't do this, these taxes isn't updated.

**Comment by pedrobaeza** [comment]
I see that a bit risky, as many references are done by XML-ID, and that is not going to change such reference. The proper way is to adjust the XML-ID, name of code for making the matching

**Comment by omar7r** [comment]
It's other way, that needs more time. This module, in general is risky, it needs a good knowledge of charts and carrefully executions, this could be another possibility and a possibility that exists in older version of module, the readonly was added in 9.0, but ok,  I will migrate our module to 14.0. 

* If you check the option of Recreate Xml Ids in the wizard, the update changes the xml_id of tax.

Thanks.

**Comment by pedrobaeza** [comment]
Maybe we can integrate it here if you do: readonly=False if you have checked "Regenerate XML-IDs". What do you think?

**Comment by omar7r** [comment]
In 14 version, i didn't can test for now the regeneration of xml_ids, only the update and new actions of fiscal positions, testing the canary islands chart, i will test the recreation in next days, but in 12 version I used it several times, the change of mapping tax templates in spanish reports from reference to xml_id required that, and it worked fine. When I test it in 14, will do PR with changes

**Review by HaraldPanten — APPROVED** [review]
Functional review in runbot

**Comment by HaraldPanten** [comment]
@omar7r @pedrobaeza any news here?

THX.

**Comment by omar7r** [comment]
@HaraldPanten @pedrobaeza Tested and working, I can do a PR to this with the readonly=False commented above.

**Comment by pedrobaeza** [comment]
There are some warnings to fix:
```
2021-04-26 08:24:00,996 161 WARNING openerp_test odoo.fields: Field wizard.update.charts.accounts.lang: unknown parameter 'size', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it
2021-04-26 08:24:00,997 161 WARNING openerp_test odoo.fields: Field wizard.update.charts.accounts.tax_ids: unknown parameter 'ondelete', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it
2021-04-26 08:24:00,997 161 WARNING openerp_test odoo.fields: Field wizard.update.charts.accounts.account_ids: unknown parameter 'ondelete', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it
2021-04-26 08:24:00,997 161 WARNING openerp_test odoo.fields: Field wizard.update.charts.accounts.fiscal_position_ids: unknown parameter 'ondelete', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it
```
@omar7r if you want to supersede it and add such option, go ahead.

**Comment by Reyes4711-S73** [comment]
@pedrobaeza and  @omar7r I will do this changes

**Comment by Reyes4711-S73** [comment]
@omar7r please, review the new content if is this the change you mentioned before

**Comment by omar7r** [comment]
Thanks you @Reyes4711 Yes this is the change with the variabillity commented by @pedrobaeza I think is needed a small fix, now you defined the form view of maps, but you have to add to the form view the update_tax_id, update_account_id etc... for allowing change it in the case you want to change the type.

**Comment by Reyes4711-S73** [comment]
Yes @omar7r I reviewed the xml file and only remains the update_tax_id, the others are in their form views. So, now I add this field, test that view, and upload the code again.
Thank you for your quickly response

**Comment by Reyes4711-S73** [comment]
@omar7r  added update_tax_id at form view

**Review by omar7r — APPROVED** [review]
LGTM

**Pull request merged**
