### PR TITLE
[15.0] [MIG] account_move_line_tax_editable

### PR DESCRIPTION
**Pull request by JSeguiN97**

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
Could you include this? dbb40615cf350b505f36cb4aba2c1774708a4020 from this PR? https://github.com/OCA/account-financial-tools/pull/1352

/ocabot migration account_move_line_tax_editable

**Comment by rafaelbn** [comment]
Hello @JSeguiN97 , please could you please attend https://github.com/OCA/account-financial-tools/pull/1368#issuecomment-1084353991 ? Thanks!

**Comment by HaraldPanten** [comment]
@manuelregidor  @ValentinVinagre could you review?

**Comment by HaraldPanten** [comment]
@sbidoul Do you know why is runboat failing here?

THX!

**Comment by sbidoul** [comment]
@HaraldPanten that's the good old `vatnumber` that is unmaintained. We need to get rid of it (I thought that was done, BTW, as we discussed that elsewhere in this repo, see for instance https://github.com/OCA/account-financial-tools/pull/1360#issuecomment-1076354460)

**Comment by HaraldPanten** [comment]
> @HaraldPanten that's the good old `vatnumber` that is unmaintained. We need to get rid of it (I thought that was done, BTW, as we discussed that elsewhere in this repo, see for instance [#1360 (comment)](https://github.com/OCA/account-financial-tools/pull/1360#issuecomment-1076354460))

Yep, I thought we did before 🤔. Let's see...

**Comment by HaraldPanten** [comment]
> Hey @JSeguiN97, thank you for your Pull Request.
> 
> It looks like some users haven't signed our **C**ontributor **L**icense **A**greement, yet. You can read and sign our full Contributor License Agreement here: https://odoo-community.org/page/cla Here is a list of the users:
> 
> * Benjamin Willig [benjamin.willig@acsone.eu](mailto:benjamin.willig@acsone.eu) (no github login found)
> * Fekete Mihai [mihai.fekete@forbiom.eu](mailto:mihai.fekete@forbiom.eu) (no github login found)
> * Joan [joan.segui@qubiq.es](mailto:joan.segui@qubiq.es) (no github login found)
> 
> Appreciation of efforts, OCA CLAbot

By the way... @JSeguiN97 did you sign the OCA CLA?

THX

**Comment by rafaelbn** [comment]
/ocabot rebase

Note: https://github.com/moduon/account-financial-tools/commit/7df0b274c6b4bd9b0dfce679082c7e960de57b54

**Comment by ValentinVinagre** [comment]
@rafaelbn I think @JSeguiN97 didn't add the https://github.com/OCA/account-financial-tools/commit/dbb40615cf350b505f36cb4aba2c1774708a4020 commit, and only "copied"/"pasted" the changes in the [MIG] commit.

**Comment by rafaelbn** [comment]
OK, so @JSeguiN97 , can you answer about this PR please? If no answer after 29 days of the first question [[JSeg](https://github.com/JSeguiN97) ](https://github.com/OCA/account-financial-tools/pull/1368#issuecomment-1087433609) I think any one can open a new PR and this one will be closed. thank you! 😄 🙏

**Comment by etobella** [comment]
I think you can open a new PR and close this.

**Comment by rafaelbn** [comment]
Closing then

**Comment by HaraldPanten** [comment]
Once this PR is merged --> https://github.com/OCA/account-financial-tools/pull/1352 , our team is going to supersede this PR

**Pull request closed without merging**
