### PR TITLE
[ADD] account_tax_chart_interval: Tax chart for a period interval

### PR DESCRIPTION
**Pull request by pedrobaeza**
# Tax chart for a period interval

Regular tax chart wizard lets you select only one period. With this module,
you can select an initial and ending period, and you will get taxes data
for that interval.
# Known issues / Roadmap
- sum_period compute logic has been completely overwritten when coming from
  tax chart wizard because there is no provided hook or facility, so changes
  in the computation upstream (unlikely, but possible) will not be reflected
  with this module.

### CODE REVIEW

**Comment by sbidoul** [comment]
@pedrobaeza there is a couple of pep8 issues

**Comment by pedrobaeza** [comment]
Done!

**Comment by rafaelbn** [comment]
:+1:

**Comment by antespi** [comment]
:+1:

**Comment by angelmoya** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Travis errors are unrelated, so I merge.

**Comment by AlbertCabedo** [comment]
:+1:  testeado en base de datos test

**Comment by sbidoul** [comment]
@pedrobaeza in my experience, upstream refactorings to allow extensions are usually accepted on the stable version.

**Comment by pedrobaeza** [comment]
Well, you can see the date of this refactoring I proposed: https://github.com/odoo/odoo/pull/1468, but I can try with this one.

**Pull request merged**
