### PR TITLE
[15.0][IMP] account_asset_management: big code cleanup (forward port)

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Forward port of https://github.com/OCA/account-financial-tools/pull/1513.

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
:astonished:  LGTM

**Review by bosd — APPROVED** [review]
LGTM

**Comment by AaronHForgeFlow** [comment]
@pedrobaeza this was merged in v14 is it ok to you to move this to 15 and newer versions?

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Please take into account my comment in https://github.com/OCA/account-financial-tools/pull/1513#issuecomment-1331922981

**Comment by bosd** [comment]
uuh ooh, almost stale..
@MiquelRForgeFlow Do you plan on continue to work on this one?

**Comment by MiquelRForgeFlow** [comment]
Rebased.

@bosd , no, I can't dedicate more time on this, as I am full with other projects.

**Pull request closed without merging**
