### PR TITLE
[8.0][ADD] account_asset_disposal addon

### PR DESCRIPTION
**Pull request by antespi**
# Account asset disposal

This module extends the functionality of account_asset and automatically
generates the asset close move

@Tecnativa

### CODE REVIEW

**Comment by antespi** [comment]
Travis error is related with other addon:

```
Module test summary
FAIL account_asset_management
(...)
```

**Comment by antespi** [comment]
Travis error is related with `account_asset_management` addon

**Comment by antespi** [comment]
Rebased, squashed and all greeen :smile: 
I think this could be marked as needsreview

**Comment by rafaelbn** [comment]
Rebuilding for testing

**Comment by andhit-r** [comment]
@antespi i tested on runbot. I still found **Set  to Close** button, not **Disposal** button

account_asset_disposal

**Comment by pedrobaeza** [comment]
@andhit-r I have fixed and refine the module in general. Please try.

**Review by pedrobaeza — APPROVED** [review]
Tried and improved

**Comment by luismontalba** [comment]
Tested on runbot but the 'Disposal' button (instead of standard 'Set to Close') is not there:

seleccion_001

**Comment by pedrobaeza** [comment]
@luismontalba this is due to a bad .travis.yml that makes that the module is not installed. I have changed it now and next Runbot build should be OK.

**Comment by luismontalba** [comment]
I'm Trying to rebuild runbot but it seems that some problem remains

**Pull request closed without merging**
