### PR TITLE
[15.0][MIG] account_sequence_option

### PR DESCRIPTION
**Pull request by ps-tubtim**
Standard Migration.

### CODE REVIEW

**Review by Saran440 — APPROVED** [review]
Functional Test :+1:

**Comment by Saran440** [comment]
This PR depend on base_sequence_option - https://github.com/OCA/server-tools/pull/2743

**Comment by patrickt-oforce** [comment]
@ps-tubtim the PR linked by @Saran440 was closed in favour of [OCA/server-tools#2275](/OCA/server-tools/pull/2275), can you send an empty commit to force CI to restart?

**Comment by matteoopenf** [comment]
@ps-tubtim  reminder

**Comment by patrickt-oforce** [comment]
@pedrobaeza can this PR be rebased, after merge of [OCA/server-tools#2275](/OCA/server-tools/pull/2275), to trying get all checks green?

**Comment by pedrobaeza** [comment]
Being an organization branch, it should be done by the contributors themselves. The rebase command is not working here (due to limitations imposed by GitHub which I don't understand).

**Comment by Saran440** [comment]
@patrickt-oforce @matteoopenf I fixed it. Can you recheck and approve it, please?

**Comment by matteoopenf** [comment]
> @patrickt-oforce @matteoopenf I fixed it. Can you recheck and approve it, please?

I check thank you so much for the help

**Comment by Saran440** [comment]
Failed because PR https://github.com/OCA/account-financial-tools/pull/1758 is not merged

**Comment by matteoopenf** [comment]
> Failed because PR #1758 is not merged

thank you I try to ask the merge

**Comment by patrickt-oforce** [comment]
@Saran440 please can you locally run pre-commit tool on branch and push the update files? If you are unsure how to use pre-commit ask and we will help you

**Comment by matteoopenf** [comment]
> @Saran440 please can you locally run pre-commit tool on branch and push the update files? If you are unsure how to use pre-commit ask and we will help you

@patrickt-oforce  I ask for merge the https://github.com/OCA/account-financial-tools/pull/1758

**Comment by matteoopenf** [comment]
> Failed because PR #1758 is not merged

https://github.com/OCA/account-financial-tools/pull/1758 fixed

**Comment by patrickt-oforce** [comment]
Hi @Saran440 PR #1758 was merged, can you proced with an empty commit, to restart CI checks

**Comment by matteoopenf** [comment]
@Saran440 if you want we have the test in 16.0 in this commit https://github.com/OCA/account-financial-tools/pull/1775/commits/0ee4941b994c51201aac977373795ec5119982a3 you will be feel free to do a backport

**Comment by Saran440** [comment]
Hi, @pedrobaeza 

Test script is error because module `account_move_name_sequence` and this PR shouldn't be installed in the same database.
Is there a way to skip the test scripts for this module?

**Comment by matteoopenf** [comment]
@Saran440  can you do a rebase, to allow start runboat?
thank you so much

**Review by matteoopenf — APPROVED** [review]

**Pull request merged**
