### PR TITLE
[13.0][FIX] Pre commit fails with "AttributeError: module 'collection…

### PR DESCRIPTION
**Pull request by BT-rmartin**
…s' has no attribute 'MutableSet

Applying same solution as in 
https://github.com/OCA/oca-addons-repo-template/pull/79 to fix the issue in the pre-commit

### CODE REVIEW

**Comment by BT-rmartin** [comment]
@sbidoul @yajo @chienandalu @pedrobaeza Please, review this input based on a solution you did for the oca-addons-repo-template

**Comment by pedrobaeza** [comment]
Please use copier instead for updating the template: `copier -f update`.

**Comment by BT-rmartin** [comment]
Thanks @pedrobaeza @yajo but when I try to run it I get some issues
image
Could you please help me with that?

**Comment by pedrobaeza** [comment]
You have to use copier beta version, or use in your local machine a lower Python version.

**Comment by BT-rmartin** [comment]
> copier beta version

Where is it? I don't find it in https://readthedocs.org/projects/copier/versions/

**Comment by pedrobaeza** [comment]
https://github.com/copier-org/copier/releases/tag/v6.0.0b0

**Comment by BT-rmartin** [comment]
I tried but I get some issues when trying to get the beta copier working
python3 -m pip install https://github.com/copier-org/copier/archive/refs/tags/v6.0.0b0.tar.gz

image

**Comment by pedrobaeza** [comment]
Fixed in 9ae29ffdea757e1f1b2d12f8582e13cb1710bb6e

**Comment by BT-rmartin** [comment]
@pedrobaeza Thanks a lot  :+1:

**Pull request closed without merging**
