### PR TITLE
[10.0][MIG] account_chart_update

### PR DESCRIPTION
**Pull request by sylvainvh**

### CODE REVIEW

**Comment by jbaudoux** [comment]
This is a port of https://github.com/OCA/account-financial-tools/pull/420 to v10

**Comment by sylvainvh** [comment]
Hi, nobody can help me ?

**Comment by pedrobaeza** [comment]
The module should be validated first in v9. I found a problem, but @jbaudoux said that he's not able to reproduce it. I need to find time to check again the error. Then, I will review this one. Anyway, if this is correctly working, it can be reviewed apart, but you need to find reviewers. One way to do it is reviewing other PRs from the same repo and asking in return that they review yours.

**Comment by levkar** [comment]
It works good. +1

Edit: After some deeper testing it looks like it has many problems.

1) It doesn't update directly related fields such as account type, tax group.
2) Fiscal positions are not updated properly.

**Comment by levkar** [comment]
I fixed every bug I found in this PR and get it working. Now it works for all tax, account and fiscal positions. Contribution of the migration of this addon got so complex (lots of changes, v9 PR is closed and another one is open which is not working and yet there is this v10 PR which also does not work) that I have no clue how to contribute at this point. I will be very happy to contribute if somebody tells me how I can proceed. 

PS: @tools.ormcache is evil anyway

**Comment by pedrobaeza** [comment]
@levkar do you have a modified version of this module then?

**Comment by levkar** [comment]
Yes I have a modified version of this PR.

**Comment by pedrobaeza** [comment]
Please point me to the branch that contains that changes and I'll integrate it here.

**Comment by levkar** [comment]
https://github.com/levkar/account-financial-tools/tree/chart_update_v10

**Comment by pedrobaeza** [comment]
@levkar I understood you bad. I thought that one was for v9, not for v10. Can you backport changes to make it work on v9 or this one is correct?

**Comment by levkar** [comment]
This PR (#460) and https://github.com/levkar/account-financial-tools/tree/chart_update_v10 is for V10.
I backported the same fixes for PR (#420) which is for v9 right here:
https://github.com/levkar/account-financial-tools/tree/chart_update_v9

Thanks Pedro!

**Comment by pedrobaeza** [comment]
I have finally caught this and solved v9 problems, and now this branch contains all the 9.0 commits + the 10.0 migration.

@levkar, sorry but your changes didn't convinced me, as you made a step back to the previous less generic formula and also remove the cache mechanism. Check f97668c3627337cc2d711493b8412b89a3c320aa to see that it's easier and more generic this way.

@sylvainvh @jbaudoux please review now this PR and let's merge it if everything is correct.

**Comment by pedrobaeza** [comment]
@mreficent, maybe you can develop tests for this version for complementing the migration.

**Comment by pedrobaeza** [comment]
Can somebody review this for finally merging it?

**Comment by pedrobaeza** [comment]
Merging this one as I have tested several times. Any problem can be solved later via PR.

**Pull request merged**
