### PR TITLE
[SEC] fix vulnerable use of pickle

### PR DESCRIPTION
**Pull request by gurneyalex**
the module is still not ported to v9, but this will save trouble
when it finally is

### CODE REVIEW

**Comment by tafaRU** [comment]
:+1:

**Comment by guewen** [comment]
:+1:

**Comment by pedrobaeza** [comment]
As this module is not yet installable, the procedure for migrating the module includes a kind of cherry-pick of the latest changes in v8 (https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0#if-the-module-already-exists-in-the-90-branch-but-it-doesnt-contain-all-the-commit-history-or-youre-not-sure-if-it-have-it), so this one will be included, and merging the PR would lead to conflicts, so my vote is :-1: for this one.

**Comment by gurneyalex** [comment]
@pedro you just merged #354, so for consistency I suggest this one gets merged too (the addon is not ported in v8 either)

**Comment by pedrobaeza** [comment]
That one catched me! Isn't merged in v8? In any case, the procedure is still valid from v8 to v9, although for migrating it for v8 will need to deal with that in the migration, but I won't block this PR if you want to follow consistency.

**Pull request merged**
