### PR TITLE
initial german translations

### PR DESCRIPTION
**Pull request by rschnapka**
to most modules ... I believe the i18l_fr_siret wouldn't really need german translation, or?
template-file renamed
some cool modules here - gotta go testing :-)

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Some extra line feeds.

**Comment by rschnapka** [comment]
all excess linefeeds now should be removed, I hope. Some other corrections (or "making thing better" issues) added as well.

**Comment by pedrobaeza** [comment]
Thanks :+1:

**Comment by yvaucher** [comment]
:+1:

**Pull request merged**
