### PR TITLE
[IMP] account_asset_management: use reload_on_button instead of reloading page

### PR DESCRIPTION
**Pull request by sbidoul**
Cool trick I just discovered, BTW.

### CODE REVIEW

**Comment by laetitia-gangloff** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by sbidoul** [comment]
This one should be good for merging.

**Comment by lmignon** [comment]
:+1:

**Comment by bwrsandman** [comment]
Cool!

**Pull request merged**
