### PR TITLE
[12.0][MIG] account_group_menu

### PR DESCRIPTION
**Pull request by rven**

### CODE REVIEW

**Comment by grindtildeath** [comment]
Please integrate https://github.com/OCA/account-financial-tools/pull/703 's commit. A review there would also be appreciated :wink:

**Comment by rven** [comment]
@grindtildeath #703 is already merged in 11.0, your changes are also merged in this PR.

**Comment by grindtildeath** [comment]
@rven Thanks, but here you're taking ownership of my commit, it's not a big deal but not a good thing to do.
To respect a commit author, you could do :
```
git reset --hard HEAD^  
git fetch origin
git cherry-pick 48d9907ce2b0587770d05ab666a5efa7fc07a9d3
```
1st remove last commit.
2nd updates upstream references
3rd "cherry picks" the commit preserving its author
 :wink: 

BTW travis is red here :(

**Comment by rven** [comment]
@grindtildeath This looks better, not?
Thanks for the reply and the improvement on the merge of the PR ;-)

**Comment by pedrobaeza** [comment]
Travis and runbot are red

**Comment by pedrobaeza** [comment]
@rven Are you going to finish these PRs?

**Comment by rven** [comment]
@pedrobaeza I don't understand the error message:

psycopg2.ProgrammingError: relation "ir_module_module" does not exist
LINE 1: UPDATE ir_module_module SET state='installed' WHERE state IN...

It seems something is wrong in building the odoo environment?
Have you ever seen this error before? Do you know what is wrong? How to fix this?

**Comment by pedrobaeza** [comment]
Yeah, it's due to https://github.com/OCA/account-financial-tools/commit/7d720d6b492e2e5b42379750b64bd7af580d5714. Please rebase your branch over last 12.0 main branch and it will be solved.

**Comment by rven** [comment]
@pedrobaeza I rebased the code to the last 12.0 main branch.
The Travis CI build passed, but the runbot build failed, I don't see any error on the build page?

**Comment by pedrobaeza** [comment]
They are some warnings in the logs, that is accessible seeing "Full all logs" under the gears dropdown:
```
2018-10-31 11:02:15,957 153 WARNING openerp_test odoo.models: account.tax.create() with unknown fields: cash_basis_account
2018-10-31 11:02:15,961 153 WARNING openerp_test odoo.models: account.tax.create() with unknown fields: cash_basis_account
2018-10-31 11:02:15,964 153 WARNING openerp_test odoo.models: account.tax.create() with unknown fields: cash_basis_account
```

**Comment by rven** [comment]
@pedrobaeza All checks are passed now ;-)

just squashing commits...

**Review by pedrobaeza — APPROVED** [review]

**Review by tbaden — APPROVED** [review]

**Pull request merged**
