### PR TITLE
[13.0][MIG] account_fiscal_year

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Sorry, supersede of https://github.com/OCA/account-financial-tools/pull/898. It's just to correct the commit history, because in v12 we did something weird.

- [x] https://github.com/OCA/server-ux/pull/99

### CODE REVIEW

**Review by astirpe — APPROVED** [review]

**Comment by astirpe** [comment]
@mreficent travis is red...

**Comment by MiquelRForgeFlow** [comment]
@astirpe now is green

**Review by HaraldPanten — APPROVED** [review]
Functional review. LGTM 👍 

Shouldn't you change these branch conflicts?

Thanks!

**Comment by AaronHForgeFlow** [comment]
@MiquelRForgeFlow Please rebase, there are conflicts

**Comment by MiquelRForgeFlow** [comment]
@AaronHForgeFlow conflicts solved

**Review by AaronHForgeFlow — APPROVED** [review]
code review LGTM :+1:

**Pull request merged**
