### PR TITLE
Added group for restrict visibility on validate button on account_move on account_default_draft_move

### PR DESCRIPTION
**Pull request by agb80**
In some workflows the accountant needs to validate each one of the
accounts_moves as soon as reviewe the move. That simplifies the
control for the review process
This commit adds a group for allow Validate button to be visible
for some users only

### CODE REVIEW

**Comment by elicoidal** [comment]
Hi @agb80 
Thanks for your contribution to the OCA
Please review the contribution guideline (https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md) and template (https://github.com/OCA/maintainer-tools/blob/master/template/module/__openerp__.py#L3 and https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst) so that your contribution can be accepted.
Thanks and best regards

**Comment by agb80** [comment]
Thanks for your comments @elicoidal, as this is just a patch for an existing module I try to change as little as possible. Do you want that me to fix the errors in travis?

**Comment by elicoidal** [comment]
@agb80 AFAIU, this is not a patch as you add a security group and modify the workflow/validation process.
I would create a specific module and would follow the common OCA guidelines for the module
@pedrobaeza @dreispt can you confirm?

**Comment by agb80** [comment]
Honestly I don't think the small changes I done require a new module, could you just confirm that I need to create a new module to proceed?

**Comment by sbidoul** [comment]
@agb80 the change you propose would change the behaviour of the module in existing installations, so I agree with @elicoidal it should be made in a separate module.

Moreover, it is not particularly related to account_default_draft_move and could be useful when not using account_default_draft_move.

Finally, be careful that there could be other ways to post moves than clicking on this button. In general, security should be implemented on the business logic side and hiding the button in the form is only a usability complement.

**Comment by pedrobaeza** [comment]
Totally agree with @sbidoul's comments

**Comment by agb80** [comment]
@sbidoul I know there are several ways to post account moves, let me explain further the user case for what I make the changes proposed: it's a small company which has a secretary typing invoices and payments. The accountant is not working full time on the company and needs to review each move captured by secretary because obvious lack of knowledge.

We installed account_default_draft_move for set in draft all moves by default and allow accountant review and change anything as needed. Then the accountant ask for a simple way to post each move as soon as she reviewed and validate them. On that way she can use the post state also as a control for reviewed moves.

I really feel a new module for the changes I'm proposing is overkill but anyway, going to extract them.

**Pull request closed without merging**
