### PR TITLE
[FIX] remove asset category in customer invoice and refund + add analyti...

### PR DESCRIPTION
**Pull request by vrenaville**
Remove asset category from customer invoice and refund and add analytic account account when generate move line on removal

### CODE REVIEW

**Comment by fclementic2c** [comment]
tests OK 
:+1:

**Comment by luc-demeyer** [comment]
:-1: 
Functional review : 
You cannot remove the asset_id from the customer invoice since this is crucial for the early removals  when your country's posting_regime is "Gain/Loss on Sale". 
If you find this field annoying (I can imagine this for the users in France), than it would be better to make it invisible when posting_regime is "Residual Value".

Making the category_id invisible for sales invoices is an improvement, hence that part of the PR should be kept.

**Comment by vrenaville** [comment]
@luc-demeyer it's my fault, I have delete the asset id by mistake

**Comment by vrenaville** [comment]
@luc-demeyer I have improve my PR according to your comment
Thanks for the review

**Comment by luc-demeyer** [comment]
@vrenaville 
:-1: 
Thanks for the correction. 
I have now tested the code:
Two remarks:
1) account_asset_remove.py, line 223 : the analytic_account_id should be removed since this is a balance account (adding this on the P&L accounts on done in the rest of that module is an improvement, thanks for that).
2) account_asset_view.xml,, line 16
The xml_id changed from "view_customer_invoice_asset" into "invoice_form_add_quantity" 
cf : <record model="ir.ui.view" id="invoice_form_add_quantity">
This looks like a typical cut&paste problem.

If these issues are fixed, than this PR is a nice improvement that I hope will get merged soon.
Tx,
Luc

**Comment by gurneyalex** [comment]
@luc-demeyer @vrenaville  what is the current status of this PR?

I just merged #230 in 8.0

**Comment by luc-demeyer** [comment]
This PR doesn't add anything any more and can be closed thanks to merge of #230.

**Pull request closed without merging**
