### PR TITLE
[13.0][IMP] account_move_line_purchase_info optional in tree view

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
Tree view for journal items is growing too much

cc @ForgeFlow

### CODE REVIEW

**Review by JordiMForgeFlow — APPROVED** [review]
LGTM 👍🏼

**Review by LoisRForgeFlow — APPROVED** [review]
:heavy_check_mark:

**Review by mariadforgeflow — APPROVED** [review]

**Review by etobella — APPROVED** [review]
👍

**Review by ps-tubtim — APPROVED** [review]

**Pull request merged**
