### PR TITLE
[14.0][BCK] account_asset_management: KeyError

### PR DESCRIPTION
**Pull request by bosd**
Backport of #1723

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Fast-tracking this:

/ocabot merge patch

**Comment by bosd** [comment]
The bot is taking a while. I noticed that GH actions on OCA repo's is very slow as well.
(as well as with the runboats)
@sbidoul Is something going on with the server?

**Comment by pedrobaeza** [comment]
I think the Codecov situation is not yet resolved, so this won't get merged yet. More details on Discord infrastructure group.

**Pull request merged**
