### PR TITLE
8.0 account_check_deposit : Port to new API

### PR DESCRIPTION
**Pull request by alexis-via**
Port account_check_deposit to new API and do some clean-up (move description from **openerp**.py to README.rst, remove seq from journal because it is auto-created)

### CODE REVIEW

**Comment by alexis-via** [comment]
It also fixes an issues when you duplicate a account move line that is linked to a check deposit : with an added copy=False, it won't add this new entry to the check deposit.

**Comment by legalsylvain** [comment]
Hi @alexis-via 

Thanks for porting this module to the new API !

2 points : 
- this module create a new journal "check_received_journal". I guess it should be in a "demo" data file... Don't you ? If yes I gess you could let "check_received_journal_seq". (in demo data too)
- if you apply new convention, could you git mv files into correct folders. [ref](https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md) (data / demo / models views / etc...)

Otherwise, LGTM. (code review only).

Regards.

**Comment by rvalyi** [comment]
@alexis-via same remarks as @legalsylvain, LGTM otherwise. Eager to use this module here BTW, let see how that will look in v9...

**Comment by fclementic2c** [comment]
Sorry for being a bit off-topic but do you think this module worth to be ported to odoo9 now there is a standard module for cheque? (comments would be appreciated in https://docs.google.com/spreadsheets/d/1HzzOtwe1-0cgbw1DwwVeHI79nwXmD8ub468u4NOpffU/edit#gid=0 line 34

thanks

Frederic

**Comment by alexis-via** [comment]
@legalsylvain 
1) well, there are arguments pro and against. The argument "pro" keeping it like this is that you MUST create such a journal to make the module work, so, if it's created automatically at module installation, it makes life easier for users. And if you already had such a journal before installing account_check_deposit, you can still delete it, it's not difficult. So I don't want to change this in this PR. You can still propose another PR to change that if you think it's worth trying to change that.
2) done, I created sub-dirs

**Comment by legalsylvain** [comment]
Hi again @alexis-via, 

1/ Yes we need a journal, but not necessarily in base.main_company... And your args is not very coherent with the fact you removed sequence in this PR and the message you added [here](https://github.com/OCA/account-financial-tools/pull/319/files#diff-0caf4e47c5ca34fd8ae0cc9ecd112bb0L20) : anyway, user have to do setting around this new journal, so please let him create the journal as he wants, in the company he wants, ...
Let sequence and move all this data in demo data section is more consistent.

2/ Thanks !

@fclementic2c : thanks to point that. Did you tried both modules ? (Odoo / V9 and OCA / V8)

Regards.

**Comment by luc-demeyer** [comment]
I tested this PR and it looks ok for me, hence :+1: for merge.

Concerning the remark from Sylvain:
I also prefer to move the Check Journal creation to the demo data but since the current published OCA module already has this problem we can fix this IMHO via a separate PR.

A few suggestions for improvements (via new PR's):
1) I think we can drop the  'check_deposit_account_id' on res.company level and use the default_debit_account_id of the check journal in stead (less configuration work).
2) I think we should add a field on the check deposit form which allows the user to specify the "check deposit" reference of the bank. This field should be propogated into the account_move created at check deposit validate time so that we can use it to reconcile the bank statement entry with the cheque deposit payment.

If there is agreement on above suggestions, than I can make 2 PR's (after merge of this PR).

One last remark: 
We use this module in combination with the account_invoice_pay_filter module (cf. Noviat's apps.odoo.com repo: https://github.com/luc-demeyer/noviat-apps). 
If there are people within the OCA finance community who find this module interesting and hence are ready to invest some time for the review/test/commit than I can make an OCA PR.

**Comment by pedrobaeza** [comment]
I consider this module useless using account_direct_debit + account_banking_payment_transfer with the transfer account defined for the cheques deposit account, although for completing the wheel I need this PR to be merged: https://github.com/OCA/bank-payment/pull/169

**Comment by alexis-via** [comment]
@luc-demeyer 
1) We cannot drop 'check_deposit_account_id' on res.company ; the role of this account is not the same as the defaut_credit/debit account. Or maybe you wanted to put a different value to default_credit_account and default_debit_account on the check journal ? If this is your point, well... why not, but let's do that kind of change when porting the module to v9, not in a stable branch.
2) I have not heard of such a "check deposit" reference given by the bank.... I'll ask my users. It's easy to add in a separate module because the creation of the account.move has a "_prepare" method.

**Comment by alexis-via** [comment]
@pedrobaeza 
I like the idea of using account_direct_debit and account_banking_payment_transfer for check deposit !!! :) I must say that, with the current status of account_debit_debit in the stable 8.0 branch of OCA, it's a bad idea because account_direct_debit is too fat and impacts the workflow of invoices. But, with my "revolution" PR https://github.com/OCA/bank-payment/pull/214 which removes the inherit of the invoice workflow in account_direct_debit, it becomes reasonable I think !

**Comment by pedrobaeza** [comment]
OK, I will work with you in having your revolution merged. I'll make some PRs to your branch.

**Comment by luc-demeyer** [comment]
@alexis-via 

1) check_deposit_account_id

I'll illustrate my point with concrete account moves:
- customer invoice 1: we generate the following account_move to indicate payment by check 
  Credit 1000 EUR on Account 411 (plus reconcile of 411 account to mark invoice as paid)
  Debit 1000 EUR on Account 5112 (Chèques à encaisser)
- customer invoice 2: 
  Credit 2000 EUR on Account 411
  Debit 1000 EUR on Account 5112
- We add both invoices to the Check Deposit. If we configure the res_company check_deposit_account_id equal to the Check Deposit journal default_credit_account ((which is equal to the default_debit_account) than we get the following account_move after validate:
  Credit 3000 EUR on Account 5112
  Debit 1000 EUR on Account 5112 (reconciled with the check payment  entry of invoice 1)
  Debit 2000 EUR on Account 5112 (reconciled with the check payment  entry of invoice 2)

So we end up with an unreconciled 3000 EUR on Account 5112 which is what we want. 
The last step is the payment by the bank: when we import the bank statement with the 3000 EUR than we register this transaction on the 5112 Account and reconcile it.

That's how I currently use this module and I don't need a separate res_company parameter.
You indicate in this conversation that the role of the res_company parameter is different. Can you explain ?

2) Check Deposit Reference given by the bank

I have the concrete case at one of our customers with the french 'CIC Nord' bank.
They have pre-printed documents from CIC Nord. Such a document is the paper equivalent of the Check Deposit Object. These document have a pre-filled unique reference number and this reference number comes back as payment reference on the bank statements (hence we can reconcile automatically).

For this customer project I have added a (non-mandatory) "deposit_ref" field to the object which I put into the account_move ref field when it's filled in by the customer (if not I fall back to the standard logic of your module)

I think it's useful to have this (optional) deposit_ref field as part of this module since I can hardly imagine that CIC Nord is the only bank assigning a unique reference to each check deposit.

**Comment by MOSAMAD** [comment]
:+1:

**Comment by brother-bernard** [comment]
:+1:

**Comment by legalsylvain** [comment]
thank you to wait before merging.

**Comment by alexis-via** [comment]
@luc-demeyer 
1) I am surprised that you use the same account 5112 when you receive the check and when you deposit it at the bank. I would do the following:
- customer invoice 1: we generate the following account_move to indicate payment by check Credit 1000 EUR on Account 411 (plus reconcile of 411 account to mark invoice as paid) Debit 1000 EUR on Account 5112 (Chèques à encaisser)
- customer invoice 2: Credit 2000 EUR on Account 411 Debit 1000 EUR on Account 5112
- We add both invoices to the Check Deposit. We get the following account_move after validate: Credit 3000 EUR on Account 5113 (Chèques remis en banque) Debit 1000 EUR on Account 5112 (reconciled with the check payment entry of invoice 1) Debit 2000 EUR on Account 5112 (reconciled with the check payment entry of invoice 2).

Account 5112 (Chèques à encaisser) is configured on the "Check Received" journal (defaut credit AND default debit). Account 5113 (Chèques remis en banque) is configured on the company.

This has one small advantage: you can see in the trial balance the amount of checks you have in your hand and the amount of checks that you sent to the bank and that haven't been credited on your bank account yet.

2) I haven't heard of such a system yet. I'll ask my customers about it. But, what is important, is that it's easy to implement because we have the appropriate _prepare methods in this module. Of course, it can become standard if we figure out that this system is used by many banks. So far, I haven't seen it and my customers use their own check deposit report, not the one of the bank.

**Comment by luc-demeyer** [comment]
@alexis-via 
1) Using the same 5112 account is recommended in e.g.  http://www.assistant-juridique.fr/comptabilisation_reglements.jsp hence we can live without this parameter (but I agree that a separate account has this small trial balance advantage). As stated previously in this thread, it's a minor remark that is not blocking for the PR but it can be subject to a separate PR (e.g. make the res_company parameter optional and adapt the query to use the default_debit_account in case the res_company parameter is not set).
2) Also this remark is not blocking for this PR but I don't see why we shouldn't add this as an optional field to the check deposit object (hence avoiding inherited _prepare_move_vals method).

**Comment by sebastienbeau** [comment]
Hi I think we can merge the work already done and propose extra PR linked to this PR to improve the module if necessary. Regarding the fact of using account_direct_debit and account_banking_payment_transfer I think will should think about it when porting the module to 9 version as everything will need to be rewriten.

So :+1:

**Comment by alexis-via** [comment]
@sebastienbeau OK, could you merge it then ? Or someone else with the super powers to merge ?

**Comment by alexis-via** [comment]
ping. Someone with the super-powers could click on the "merge" button please ?

**Comment by legalsylvain** [comment]
Hi and Happy new years !

Thanks for porting this module.

**Comment by alexis-via** [comment]
@legalsylvain thanks Mr Super-Power ! :)

**Pull request merged**
