### PR TITLE
[12.0][MIG] account_type_menu

### PR DESCRIPTION
**Pull request by rven**

### CODE REVIEW

**Review by ThomasBinsfeld — APPROVED** [review]

**Review by benwillig — APPROVED** [review]

**Review by mpanarin — APPROVED** [review]

**Comment by rven** [comment]
@pedrobaeza Could this be merged?
PR https://github.com/OCA/account-analytic/pull/192 and https://github.com/OCA/account-financial-tools/pull/707 are depending on this.

**Comment by sbidoul** [comment]
Thanks!

**Comment by pedrobaeza** [comment]
@sbidoul please remember to mark the check on the migration issue when merging a migration PR (and if module belongs to a lower version, add the module to the N+1 version list).

**Comment by sbidoul** [comment]
@pedrobaeza noted, thanks!

**Pull request merged**
