### PR TITLE
port account_move_template to v10

### PR DESCRIPTION
**Pull request by jzahid**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Have you followed migration guide for bringing last commit history? https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0#technical-method-to-migrate-a-module-from-90-to-100-branch

**Comment by elicoidal** [comment]
@pedrobaeza this code is definitively not PEP8 compliant.
How is it possible that it passes Travis? Did I miss something?
Besides, there is no codecov for this repo?

**Comment by pedrobaeza** [comment]
Uhm, I have found that UNIT_TEST was activated on .travis.yml and this should be the problem. I have removed it in https://github.com/OCA/account-financial-tools/commit/d9667f930573e513ccc7007162ba7ef54a2064fe

A rebase is needed for having this correct.

**Comment by elicoidal** [comment]
@pedrobaeza Thanks for your help!

**Comment by nhomar** [comment]
Hello.

I am trying to test this manually.

Some comments:

- Mark it as Installable True.
- We should improve the layout in order to be cleanest on v10 - 11 - and enterprise ready.
- I saw an apps module which overwrite this module. Should we fix that?

I will make the work, it is fairly a day work, I will open a new PR because I need this module __now__ I will inform the work here.

**Comment by nhomar** [comment]
I just finished the migration here:

https://github.com/OCA/account-financial-tools/pull/511

I took some functional decisions and making video to show the rationale.

**Pull request closed without merging**
