### PR TITLE
[MIG] [17.0] account_partner_required migration to 17.0

### PR DESCRIPTION
**Pull request by luisDIXMIT**
Standard migration

@etobella

### CODE REVIEW

**Review by etobella — APPROVED** [review]
LGTM  :+1: 

/ocabot migration account_partner_required

**Comment by peluko00** [comment]
Can you rebase please @luisDIXMIT  runboat

**Comment by luisDIXMIT** [comment]
@peluko00 comments attended. Thanks!

**Review by peluko00 — APPROVED** [review]
LGTM, tested in runboat

**Review by mpascuall — APPROVED** [review]
Working good, checked in runboat

**Comment by etobella** [comment]
runboat is not responding. Let's try again


/ocabot merge nobump

**Pull request merged**
