### PR TITLE
[12.0][MIG] account_spread_cost_revenue

### PR DESCRIPTION
**Pull request by astirpe**
This is the porting of _account_spread_cost_revenue_ (https://github.com/OCA/account-financial-tools/pull/715) to V12.

### CODE REVIEW

**Comment by astirpe** [comment]
@CasVissers

**Comment by CasVissers-360ERP** [comment]
@astirpe 
Initial feedback:
- Journal entry (account.move) change the name to spread name, not spread line name
- string="Reconciled entries" doesn't the smartbutton open journal entries?
- It would be easy to have extra options on the template: 1. Number of Repetitions 2. Period Type 3. Start date (with option Prorata Temporis)
- The chatter logs to move with database ID, name would make more sense (maybe also as a link) _Created move(s) 109_
- Option to post all spread lines would be easy
- Spread lines can be posted even though the invoice is not confirmed. Should only be posted/allowed if invoice is in state open & paid
- Account Spread created in chatter-> 'Invoice_type' spread created
- Should not be able to remove spread if account moves are posted
- Spread cannot be removed if still linked to an invoice line
- When unlinking a spread, add message to chatter of origin invoice "Spread unlinked for invoice line 'name'"

**Comment by astirpe** [comment]
@CasVissers 


> Journal entry (account.move) change the name to spread name, not spread line name

It is already the spread name, am I missing something?


> string="Reconciled entries" doesn't the smartbutton open journal entries?

The smartbutton opens only the journal entries that are reconciled (partially or fully)


> It would be easy to have extra options on the template: 1. Number of Repetitions 2. Period Type 3. Start date (with option Prorata Temporis)

It is easy, yes. At this moment the template only has a small set of fields, just to allow the integration with the contract module (see https://github.com/OCA/account-financial-tools/pull/737). But I will add those extra options!


> The chatter logs to move with database ID, name would make more sense (maybe also as a link) Created move(s) 109

OK


> Option to post all spread lines would be easy

Isn't the cron job enough? Anyway it's a easy feature to be developed.


> Spread lines can be posted even though the invoice is not confirmed. Should only be posted/allowed if invoice is in state open & paid

We actually allow to post spread lines even if the invoice is not confirmed. And we allow it even in case no invoice is created yet! It's like this by design. You may want to read this thread: https://github.com/OCA/account-financial-tools/pull/715. The reason is that we want to allow to do the spreading even when the invoice is not yet received.


> Account Spread created in chatter-> 'Invoice_type' spread created

OK. The "Account Spread created" message cannot be modified as it's a built in message for the creation of a record. But I can fix the next message to: "Spread table 'invoice_type' created."


> Should not be able to remove spread if account moves are posted

OK


> Spread cannot be removed if still linked to an invoice line

OK


> When unlinking a spread, add message to chatter of origin invoice "Spread unlinked for invoice line 'name'"

OK

**Comment by astirpe** [comment]
@CasVissers done. Would you give it a try?

**Comment by CasVissers-360ERP** [comment]
@astirpe 

- Button post spread all works fine.
- _Journal entry (account.move) change the name to spread name, not spread line name_ 
I mean journal entry should contain name of spread line name since this contains the number of the spread line i.e. /11
- _The smartbutton opens only the journal entries that are reconciled (partially or fully)_ 
Are you sure? spread_mls = self.line_ids.mapped('move_id.line_ids') . Doesn't contain anything about being reconciled? 
- _We actually allow to post spread lines even if the invoice is not confirmed. And we allow it even in case no invoice is created yet! It's like this by design. You may want to read this thread: #715. The reason is that we want to allow to do the spreading even when the invoice is not yet received._ 
I understand this use case when a spread is not related to an invoice line, but when related I would expect a constraint.
- _Cannot delete spread(s): there are some posted Journal Entries._ (I think "some" can be removed here)
- _When unlinking a spread, add message to chatter of origin invoice "Spread unlinked for invoice line 'name'"_ I was think to do this on the origin invoice, to make sure all followers get the message.

BTW this a big improvement on account_cost_spread, very nice.

**Comment by astirpe** [comment]
@CasVissers 

> Journal entry (account.move) change the name to spread name, not spread line name
> I mean journal entry should contain name of spread line name since this contains the number of the spread line i.e. /11

Done

> The smartbutton opens only the journal entries that are reconciled (partially or fully)
> Are you sure? spread_mls = self.line_ids.mapped('move_id.line_ids') . Doesn't contain anything about being reconciled?

Be sure that the invoice is validated: you will get the reconciled journal entries.

> We actually allow to post spread lines even if the invoice is not confirmed. And we allow it even in case no invoice is created yet! It's like this by design. You may want to read this thread: #715. The reason is that we want to allow to do the spreading even when the invoice is not yet received.
> I understand this use case when a spread is not related to an invoice line, but when related I would expect a constraint.

@yung-wang what do you think about this?

> Cannot delete spread(s): there are some posted Journal Entries. (I think "some" can be removed here)

Done

> When unlinking a spread, add message to chatter of origin invoice "Spread unlinked for invoice line 'name'" I was think to do this on the origin invoice, to make sure all followers get the message.

Done: message also added in the invoice.

**Review by CasVissers-360ERP — APPROVED** [review]
Changes are sufficient. I think a very nice module/addition to Odoo. Minor improvements are possible but not big enough to stop a release.

**Review by yung-wang — APPROVED** [review]
We are woking with it now and seems like all issues are fixed. thanks

**Comment by astirpe** [comment]
Well, the concerned addon has me as a declared maintainer, but I don't have the rights to merge :smile_cat:

**Review by CasVissers-360ERP — APPROVED** [review]
Tested and working now.

**Comment by CasVissers-360ERP** [comment]
@astirpe Not yet merged?

**Comment by astirpe** [comment]
Merging is up to the @OCA/accounting-maintainers

**Comment by CasVissers-360ERP** [comment]
@astirpe Because still not merged maybe a nice addition:
Allow spreads to be archived. Similar to Odoo base assets.
As an option it would be nice that spreads are automatically archived when all lines are posted.

**Comment by astirpe** [comment]
@CasVissers yes, good idea!

**Comment by CasVissers-360ERP** [comment]
@astirpe 
Only thing I miss is a chatter message saying the spread has been archived. Nice addition!

**Comment by CasVissers-360ERP** [comment]
@OCA/accounting-maintainers I have this module active for a couple of months at 4 customers, only positive feedback thus-far.

**Comment by astirpe** [comment]
Thank you @aheficent !

Could you also check the V11 https://github.com/OCA/account-financial-tools/pull/715? It's Ready to Merge since a long time.

**Pull request merged**
