### PR TITLE
[IMP]account_loan: modifications to work in multi-company context

### PR DESCRIPTION
**Pull request by odooNextev**

### CODE REVIEW

**Review by sergiocorato — APPROVED** [review]
LGTM

**Review by francesco-ooops — APPROVED** [review]
LGTM

**Review by HekkiMelody — APPROVED** [review]
Code review, LGTM

**Comment by francesco-ooops** [comment]
@sergiocorato merge?

**Comment by francesco-ooops** [comment]
@OCA/accounting-maintainers can this backporting be merged please?

**Comment by francesco-ooops** [comment]
@pedrobaeza merge svp

**Comment by pedrobaeza** [comment]
@etobella should say

**Review by etobella — APPROVED** [review]

**Comment by etobella** [comment]
/ocabot merge patch

Can you port it to 15 and 16 please?

**Comment by francesco-ooops** [comment]
@etobella here you go: https://github.com/OCA/account-financial-tools/pull/1813

**Comment by AnizR** [comment]
you might need to backport this: https://github.com/OCA/account-financial-tools/pull/1816

**Comment by francesco-ooops** [comment]
@AnizR thanks for the heads up!

**Pull request merged**
