### PR TITLE
FIX odoo preload of account_move_batch_validate with connector error

### PR DESCRIPTION
**Pull request by jjscarafia**
@pedrobaeza  with the static folder added (and the icon) odoo now make like a pre-load of the module `account_move_batch_validate` and raise an error of import `ImportError: No module named connector` if you dont have that [connector](https://github.com/OCA/connector/tree/8.0/connector) available on your instance.

You can see this [travis build](https://travis-ci.org/ingadhoc/odoo-argentina/jobs/76338804) for an example

This PR delete static folder till better solutions is found

### CODE REVIEW

**Comment by nhomar** [comment]
@jjscarafia you are right... those imports need to be inside try:except, a PR is welcome....

**Comment by pedrobaeza** [comment]
A better solution is provide here: #281, so I close this one. Please review.

**Comment by StefanRijnhart** [comment]
Reopening because of https://github.com/OCA/account-financial-tools/pull/281#issuecomment-132956170

**Comment by guewen** [comment]
:+1:

**Comment by pedrobaeza** [comment]
OK, let's do it this way.

:+1:

**Comment by lmignon** [comment]
Because of https://github.com/OCA/account-financial-tools/pull/281#issuecomment-132956170 :+1:  for this one in place of #281. We really need a fix from Odoo....

**Comment by pedrobaeza** [comment]
Indeed the solution should come from Odoo. My patch can be work out to provide an alternate decorator in case of ImportError, but now it's too much work for only this thing.

**Comment by StefanRijnhart** [comment]
Thanks for the speedy response everyone! I validated the CLA in the OCA database succesfully, so I'm proceeding with the merge.

**Comment by lmignon** [comment]
For the record the issue in Odoo is https://github.com/odoo/odoo/issues/7507 (unfortunately closed)

**Comment by yvaucher** [comment]
@jjscarafia Thanks for the quick fix.

Sorry for having made trouble with those PR by adding bunch of icons while I needed to kill some time.

**Comment by jjscarafia** [comment]
Thanks all of you for the great and quick work. I woke up and lot has happend!

**Pull request merged**
