### PR TITLE
[FIX] Protect connector imports

### PR DESCRIPTION
**Pull request by StefanRijnhart**
cc @lmignon

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by lmignon** [comment]
I prefer to remove the static directory to avoid unwanted import by odoo when the module is not installed. This kind of hack is against proper coding rules...

**Comment by pedrobaeza** [comment]
I don't agree. This protection and the depends section on manifest is enough for the health of the code.

**Comment by StefanRijnhart** [comment]
Agree with @pedrobaeza on this one.

**Comment by lmignon** [comment]
I will not fight me on this subject, bu it's just an other hack in the way of writing code in python to turn around mistakes and constrains from openerp... If I remember well, in this case openerp adds the module in the pythonpath because there is a static folder. Without the static folder, the code could stay proper (An other way to solve this issue). But feel free to merge this change since it probably solve a blocking issue in a lot of cases.  :+1:

**Comment by StefanRijnhart** [comment]
Of course you are right. Odoo is the real culprit here. Thanks for the review!

**Comment by sbidoul** [comment]
:+1:

**Pull request merged**
