### PR TITLE
[11.0][MIG] account_fiscal_position_vat_check: Migration to 11.0

### PR DESCRIPTION
**Pull request by carlos-domatix**

### CODE REVIEW

**Review by feketemihai — APPROVED** [review]

**Comment by rven** [comment]
Hi Carlos,

I didn't notice you were already working on the module account_fiscal_position_vat_check to migrate it to 11.0.

Can you merge the tests I created in my fork https://github.com/rven/account-financial-tools/tree/feature/11.0-mig-account_fiscal_position_vat_check/account_fiscal_position_vat_check/tests
into this PR?
This way the codecov/patch is 100%.

**Comment by pedrobaeza** [comment]
@rven you can create a new PR with your fork, as @carlosDomatix is not answering.

**Comment by rven** [comment]
@pedrobaeza see https://github.com/OCA/account-financial-tools/pull/681
Tests are failing on Module account_lock_date_update: 0 failures, 1 errors

> odoo.exceptions.AccessError: ('The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: account.update.lock_date, Operation: read)', None)

Which has nothing to do with my changes.

**Comment by pedrobaeza** [comment]
Superseeded by #681

**Pull request closed without merging**
