### PR TITLE
[MIG] <account_move_line_search_extension> migrated to v8

### PR DESCRIPTION
**Pull request by oihane**

### CODE REVIEW

**Comment by fclementic2c** [comment]
Careful, in v7 this module has no form view (or broken ?) and it was impossible to post manual entries with taxe inclusive VAT.

**Comment by adrienpeiffer** [comment]
Hi, 
I think that migration is already in progress here #110

**Comment by luc-demeyer** [comment]
This PR should be closed since I already ported the module in 2014 (https://github.com/OCA/account-financial-tools/pull/110).
I updated PR 110 a minute ago with improved support for search on analytic account (this was already the case in the previous update of this module but I recently discovered a conflict with account_analytic_plan which is fixed now.

**Comment by sbidoul** [comment]
@oihane Thanks you for your contribution.

We must unfortunately close yours PR since it is a duplicate of #110. I invite you to test and review #110.

**Pull request closed without merging**
