### PR TITLE
Forward port '7.0' until e68377c

### PR DESCRIPTION
**Pull request by sbidoul**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
`account_credit_control_dunning_fees/security/ir.model.access.csv` shouldn't be on root.

The rest LGTM.

**Comment by sbidoul** [comment]
@pedrobaeza good catch. I moved the file to **unported**

**Comment by sbidoul** [comment]
@adrienpeiffer can you check why account_journal_period_close has a failing test on this branch?

**Comment by pedrobaeza** [comment]
It says that _TestAccountConstraintChronology_ is adding a record that already exists on account.journal.period. I can't say more for now.

**Comment by sbidoul** [comment]
@pedrobaeza @adrienpeiffer actually, the test is running fine, its Travis that gives a false negative.

The test does

```
self.assertRaises(IntegrityError,
                          create_journal_period,
                          self, period_id, journal_id, context)
```

and Odoo logs the IntegrityError, which in turn Travis interprets as an error despite the test succeeding.

So it's maintainer_quality_tools that needs to be adapted.

**Comment by pedrobaeza** [comment]
Why Travis doesn't complain up to date? Can we change test in any way to avoid it?

**Comment by sbidoul** [comment]
@pedrobaeza actually the test suite for account_journal_period_close did not run at all in v7.

We fixed it in #38. When #38 is merged I'll update this PR.

**Comment by sbidoul** [comment]
This one is now ready (merge of 7.0 in 8.0 plus manual conflict resolution). The real commits in this PR are (in chronological order):
- 0e9760a
- 014ed5b
- bcdf628
- dad7e08
- 6fb6824

These are the merge/conflict resolution commits. All the other come from the 7.0 branch.
It is easier to understand when viewing the history in gitk than github.

**Comment by pedrobaeza** [comment]
As on 7.0, :+1:

**Comment by lmignon** [comment]
:+1:  as on 7.0

**Comment by adrienpeiffer** [comment]
:+1:

**Pull request merged**
