### PR TITLE
update 7.0 account_move_line_search_extension

### PR DESCRIPTION
**Pull request by luc-demeyer**
The latest update contains a number of enhancements and bugfixes:

support for search on analytic account
code restructured to allow adding fields via inherited module
partner search fixed to support also inactive partners
removal of code that became obsolete after turning the view into read-only

### CODE REVIEW

**Comment by luc-demeyer** [comment]
@pedrobaeza 
Pedro,
I am not sure if you are the right person for this request, if not please let me know who I can turn to.
I get an error message on this PR stating that there are merge conflicts to be resolved but I don't see what the conflicts are and hence have no idea how to resolve this. Any suggestion on how to resolve this one (and how I can myself figure out what's wrong).

I submitted this PR for both V7 and V8 and also the V8 one fails (cf. https://github.com/OCA/account-financial-tools/pull/110)

**Comment by pedrobaeza** [comment]
You are working with an outdated branch, and if you have tried to rebase the branch to get the updated one, the conflicts have appeared.

You have to fix the conflicts, deciding what to keep and what to remove, and then make `git rebase --continue` to finish the rebase process. Then, making a `git push -f` overwrite this branch to get a correct PR.

**Comment by luc-demeyer** [comment]
@pedrobaeza
The rebase effectively showed a conflict but after resolving this and git push -f the problem remains (and still no clear error message about what's wrong). How can I proceed ?

**Comment by pedrobaeza** [comment]
It seems to be OK now, isn't it?

**Comment by luc-demeyer** [comment]
it says : Failed - 1 errored and 1 pending checks.

**Comment by pedrobaeza** [comment]
Yeah, but that's because runbot doesn't work correctly on v7 branch, and Travis is still making the test.

I meant correct at Git level.

**Comment by luc-demeyer** [comment]
@pedrobaeza 
do we have the same issue on V8 ? 
Travis test was successfull for https://github.com/OCA/account-financial-tools/pull/110 but runbot failed.

**Comment by pedrobaeza** [comment]
As I see on log, there are only warnings on runbot, but for now CI integration show this on GitHub as red, so nothing to worry about in my opinion.

**Comment by chrisdec** [comment]
:+1: (functional test)

**Comment by pedrobaeza** [comment]
Note to self: review it.

**Comment by pedrobaeza** [comment]
Let's merge this old one although maybe is not in use anymore.

**Pull request merged**
