### PR TITLE
[FIX] account_move_validation_improvement: order by date

### PR DESCRIPTION
**Pull request by sbidoul**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1: Seems correct.

Travis will be fixed in another PR according @sbidoul

**Comment by lepistone** [comment]
I also :+1: once travis is green.

**Comment by sbidoul** [comment]
@pedrobaeza @lepistone it will not become green (unrelated pylint issues) and I can't rebase because I edited online.

**Comment by pedrobaeza** [comment]
Yeah, right, it depends on #81 

We can fast track it when it becomes green and make the rebase here.

**Comment by sbidoul** [comment]
Rebased and green.

**Comment by tafaRU** [comment]
:+1: I proceed with the merge.

**Pull request merged**
