### PR TITLE
[15.0][MIG] account_move_fiscal_month

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

@ForgeFlow

Depends on:

- https://github.com/OCA/account-financial-tools/pull/1543

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
Functional, works the same as in v14

**Comment by AaronHForgeFlow** [comment]
Hi @JasminSForgeFlow dependency is merged. Can you rebase? Thanks

**Comment by JasminSForgeFlow** [comment]
> Hi @JasminSForgeFlow dependency is merged. Can you rebase? Thanks

Done, Thanks

**Review by LoisRForgeFlow — APPROVED** [review]
Code review LGTM

**Pull request merged**
