### PR TITLE
7.0 add account reconciliation reopen

### PR DESCRIPTION
**Pull request by eLBati**
This module allows to reopen reconciliations by creating an additional journal
entry and unreconciling the existing journal items.

See the following example

**Confirmed invoice**

| N | Account | DR | CR |
| --- | --- | --- | --- |
| 1A | Debtors | 1000 |  |
| 1B | Sales |  | 1000 |

**Paid invoice**

| N | Account | DR | CR |
| --- | --- | --- | --- |
| 2A | Bank | 1000 |  |
| 2B | Debtors |  | 1000 |

_1A_ and _2B_ are reconciled by _A1_

**Reopening**

For example, the bank takes back the money. You have to reopen the credit.

So, you can select the _1A_ journal item and run the _reopen reconciliation_
wizard.

The module generates the following entry

| N | Account | DR | CR |
| --- | --- | --- | --- |
| 3A | Debtors | 1000 |  |
| 3B | Bank |  | 1000 |

The module cancels the _A1_ reconciliation and create a new one between
_2B_ and _3A_

### CODE REVIEW

**Comment by eLBati** [comment]
Tests are failing because the module writes the `account.move.line` field `reopening_line_ids` and `account_constraints` doens't allow to write fields different from `["reconcile_id", "reconcile_partial_id"]`

Anyway, `account_constraints` module should not be installed, see https://github.com/OCA/maintainer-quality-tools/issues/85

Moreover, I think `account_constraints` should allow extra modules to bypass some check, if needed, just setting a flag in the context.
Thoughts?

**Comment by eLBati** [comment]
green :metal:

**Comment by nbessi** [comment]
@fclementic2c can you validate the functional part.

**Comment by eLBati** [comment]
I put the travis part in a separate PR https://github.com/OCA/account-financial-tools/pull/35

**Comment by fclementic2c** [comment]
Lorenzo, in this use case I would not break the 1st reconcile. 2 possibilities : 
- Either, you still expect a payment (after the refund) and whenever this one will be credited you will reconcile it with the refund (or even better, the 4 entries all together so you will see the full tracability in the payment tab of the invoice)
- Or you do not expect anymore the payment, and you must create a credit note. You will than reconcile this credit note with the refund.

I would add that best practises in Odoo is to post bank transactions through the bank statement not by manual entry (although it is not mandatory).

Don't you agree ?

Frederic

**Comment by eLBati** [comment]
Hello @fclementic2c 
I know this procedure is not advisable. Nevertheless, some customers explicitly want to follow it.

I added a warning in the module description, advising to use the correct way in standard cases.
However, I think the module can anyway be useful to those bookkeepers who want to follow this procedure.

**Comment by sbidoul** [comment]
Hi Lorenzo,

I read the description of this module (not yet read the code nor tested).

In the scenario that is described in the module manifest (ie using a Bank account), I think it is dangerous as it would create moves on the bank account that would not be reflected in bank statements. Like @fclementic2c I believe it is bad practice, and I would prefer to see the module forbid such an operation when the counterpart is on bank accounts (type=liquidity).

That said, I believe the module could be useful in scenarios such as payment/debit orders where the invoice move line is reconciled with a move to a transfer account as soon as the payment order is sent.
In such situations, it can happen the payment/debit order is rejected, and we want to undo the transfer move and leave the invoice open, as this module does.

So if you agree to add a security to avoid making it too easy to create spurious moves on bank accounts I'll investigate further.

**Comment by eLBati** [comment]
Hello @sbidoul 

> In the scenario that is described in the module manifest (ie using a Bank account), I think it is dangerous as it would create moves on the bank account that would not be reflected in bank statements

Actually, in this example, the bank takes back the money. So, the bank account reflects the real bank statement.
This could happen for example when the company issues [ricevute bancarie](https://github.com/OCA/l10n-italy/tree/7.0/l10n_it_ricevute_bancarie): the bank immediately deposits the money in your bank account, but, if the final customer does not pay, the bank takes back the money.
If this only happens in Italy, we can add the contrainst to the global module and remove it by a l10n-italy module

**Comment by sbidoul** [comment]
@eLBati 

The issue I see with the bank statement is that your scenario will create moves on the bank account, and when the user imports the bank statement afterwards, the bank statement object will also create moves on the bank account, and you will end up with duplicates, unless you create all bank statement entries manually. This is the same remark as @fclementic2c above.

Note that Odoo v9 will probably resolve this issue by matching existing moves when importing bank statements.

**Pull request closed without merging**
