### PR TITLE
[15.0][MIG] account fiscal year

### PR DESCRIPTION
**Pull request by pegonzalezspesol**
Work done:
- Do it installable
- Do the tests pass

Work in progress:
- Functional revision

### CODE REVIEW

**Comment by manuelregidor** [comment]
Hi @pegonzalezspesol Do you think you'll be able to follow this PR? Thank you!

**Review by manuelregidor — APPROVED** [review]
Technical review. LGTM.

**Review by HaraldPanten — APPROVED** [review]
Functional review. LGTM

**Pull request merged**
