### PR TITLE
8.0 account check deposit

### PR DESCRIPTION
**Pull request by sebastienbeau**
Note there is a pull request for the V7 version #64 , please comment there and not here.

### CODE REVIEW

**Comment by alexis-via** [comment]
It seems to me that the Travis error is not caused by the module account_check_deposit. If someone with more experience with Travis can have a look...

**Comment by rvalyi** [comment]
Indeed it seems unrelated, seems some kind of bad luck with the build (it happens on Travis).

In fact somebody with write access to the repo could trigger a new build http://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit
(not me)

An other possibility is to remove these files https://github.com/OCA/account-financial-tools/pull/64#issuecomment-61965523 and push again

**Comment by alexis-via** [comment]
It's green now !

**Comment by alexis-via** [comment]
This has been merged in 7.0, so let's merge this in 8.0 ! :+1:

**Comment by pedrobaeza** [comment]
Rebase is needed, due to the merge from 7.0 that was done.

**Comment by alexis-via** [comment]
yes, and I see that, in the v8 branch, there is a module **unported**/account_check_deposit... ARG ! Who did that ? why ? It seems to me that it's a bad idea given the fact that we had a pending PR for the 8.0 branch...

**Comment by pedrobaeza** [comment]
It was a general merge from all last updates in 7.0 made by @sbidoul. Well, any of the reviewers think about pending PRs, sorry.

**Comment by sbidoul** [comment]
@alexis-via I regularly propose a merge of 7.0 into 8.0 so it's easy to track what fixes in 7.0 have been forward-ported to 8.0 and have a clean history.

I had not seen this PR otherwise I would have raised a warning here.

**Comment by alexis-via** [comment]
OK, I'll ask a git expert to do the rebase stuff and sort the unported/conflicts... I'm not a git expert !

**Comment by sebastienbeau** [comment]
I have updated the PR ;). Let's wait for travis

**Comment by sebastienbeau** [comment]
Travis is green !

**Comment by florian-dacosta** [comment]
:+1:

**Comment by alexis-via** [comment]
Thanks for the rebase @sebastienbeau 
Let's merge it now ! :+1:

**Comment by sbidoul** [comment]
:+1:

**Comment by jgrandguillaume** [comment]
:+1:

**Pull request merged**
