### PR TITLE
[11.0][ADD] account_spread_contract

### PR DESCRIPTION
**Pull request by astirpe**
This module allows to spread costs or revenues over a period defined in a contract.

When creating recurring invoices, the cost/revenue spread functionality is enabled on the invoice lines.
The costs/revenues spread functionality is provided by module _account_spread_cost_revenue_.

Depends on:

- [x] account_spread_cost_revenue #715

### CODE REVIEW

**Review by yung-wang — APPROVED** [review]
Tested it in test environment.

- The spread date takes the date from the next invoice.
- The Template name is using the description of the contractline.
- The entry with analytic account is also posted and linked to the spread board.
- The period of the contract is linked to the spread. So if the contract is 3 months, if will default the spread also to 3x 1 months.

**Review by CasVissers-360ERP — APPROVED** [review]
Functional test. LGTM

**Comment by astirpe** [comment]
@CasVissers thanks for the review!
This PR depends on https://github.com/OCA/account-financial-tools/pull/715, that is still pending because it needs reviews. You may want to review that PR as well.

**Comment by astirpe** [comment]
Can this one be merged?

**Comment by astirpe** [comment]
Rebased. Branch 11.0 seems broken because of this:
```
account_move_template/README.rst:85: [E7901(rst-syntax-error), ]  Duplicate implicit target name: "authors".
account_move_template/README.rst:93: [E7901(rst-syntax-error), ]  Duplicate implicit target name: "contributors".
```

**Pull request merged**
