### PR TITLE
[13.0][MIG] account_lock_to_date

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
"Standard" migration

cc @ForgeFlow

### CODE REVIEW

**Review by AdriaGForgeFlow — APPROVED** [review]
Code review :+1:

**Review by ivantodorovich — APPROVED** [review]
LGTM :+1:

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Comment by AaronHForgeFlow** [comment]
just rebased and run pre-commit again.

/ocabot merge nobump

**Pull request merged**
