### PR TITLE
[14.0] Add module account_cash_deposit

### PR DESCRIPTION
**Pull request by alexis-via**
This module manages cash deposits (cash to bank) and cash orders (bank to cash). See readme subdir for more info.

cash_deposit_form
)

Remarks:
1) This module supports both cash deposits and cash orders, but I decided to name it "account_cash_deposit" to have a clear and easy-to-understand name, and also because, when running a brick-and-mortar shop, you make much more cash deposits than cash orders!
2) the model cash.unit could be moved to a dedicated module if some developers are interested by the model and don't want to depend on account_cash_deposit. It's not fun to have to maintain 2 modules instead of 1, but I'm not against the idea. I didn't do it so far because I think that, if you're interested by the model cash.unit, you're certainly also interested by the cash deposit or cash order feature. But, if you think cash.unit should be moved to a dedicated module, propose a module name and OCA project and say so **rapidly** (when this module will be in production, I will start to be against the idea just because I don't want to do the migration on production DB).

### CODE REVIEW

**Comment by TeoGoddet** [comment]
I'd love to have cash units separately

**Comment by alexis-via** [comment]
@TeoGoddet What do you plan to use it for ?

**Comment by alexis-via** [comment]
I updated the module today following a feedback from a user: it now uses the inter-bank transfer account as counterpart.

**Review by njeudy — APPROVED** [review]
just test it and ok for me, work like it does :)

**Review by acalmett — APPROVED** [review]
Used in production, no code review.

**Pull request merged**
