### PR TITLE
[14.0][MIG]account_asset_management_menu: Migration to 14.0

### PR DESCRIPTION
**Pull request by GuillemCForgeFlow**
@ForgeFlow
Standard migration

### CODE REVIEW

**Review by HaraldPanten — APPROVED** [review]
Functional review

**Review by AaronHForgeFlow — APPROVED** [review]
Functional + code :+1:

**Comment by olgamarcocb** [comment]
@GuillemCForgeFlow can you rebase? Travis should be fixed with #1300 :wink:

**Comment by GuillemCForgeFlow** [comment]
> @GuillemCForgeFlow can you rebase? Travis should be fixed with #1300 wink

Done!

**Review by LoisRForgeFlow — APPROVED** [review]
Tested :+1:

**Review by olgamarcocb — APPROVED** [review]
LGTM :+1:

**Pull request merged**
