### PR TITLE
[14.0][MIG] account_check_deposit

### PR DESCRIPTION
**Pull request by alexis-via**
For the moment, still in beta. I still have to clarify a few things on:
- the new datamodel of account.journal (the new M2O fields on account.account)
- cancellation of move
Tests have not been ported yet.

But I tested the module and it works well.

### CODE REVIEW

**Comment by Saran440** [comment]
@alexis-via 
Hi, this module is migrated on PR https://github.com/OCA/account-financial-tools/pull/1082
Could you review this PR?

**Comment by kittiu** [comment]
@alexis-via can we close this as it is duplicated? Or anything you want to add to #1082 ?

**Comment by alexis-via** [comment]
No, this PR should not be closed. It contains several improvements that are not present in your PR. We'd better merge the best PR.

**Comment by kittiu** [comment]
@Saran440 you can help review this? I agree we go with the best one.

**Comment by kittiu** [comment]
Test failing.
```
    from . import test_check_deposit
  File "/home/travis/build/OCA/account-financial-tools/setup/account_check_deposit/odoo/addons/account_check_deposit/tests/test_check_deposit.py", line 7, in <module>
    from odoo.addons.account.tests.account_test_classes import AccountingTestCase
ModuleNotFoundError: No module named 'odoo.addons.account.tests.account_test_classes'

```

**Comment by alexis-via** [comment]
FYI, I plan to do the following change : remove the fields "check_deposit_offsetting_account" and "check_deposit_transfer_account_id" on res.company. The transfer account will be the bank account of the check journal. Please refer to my recent post in https://github.com/OCA/bank-payment/issues/740 to understand the reasons of this change.

**Comment by alexis-via** [comment]
I have a better idea: the transfer account will be the outstanding receipts account of the bank journal on which you do the check deposit. That way, if you have an outstanding receipts account different for each bank journal, the amounts for confirmed check deposits will be in an account which is specific to the bank on which you made the deposit. The bank account of the check journal will not be used (the suspense account of the check journal will not be used either).

**Comment by alexis-via** [comment]
I implemented what I described in my previous comment.

**Comment by alexis-via** [comment]
If nobody is against it, I think I'll add a chatter on account.check.deposit.

**Comment by alexis-via** [comment]
I don't plan to make other changes. Ready to merge.

**Comment by newtratip** [comment]
@Saran440, @kittiu Could you review/approve this PR ? I will change PR Url in our project from #1082 to #1088 if it's OK.

**Review by kittiu — APPROVED** [review]
Good for me.

**Review by Saran440 — APPROVED** [review]

**Comment by alexis-via** [comment]
Thanks @kittiu for the review and merge !

**Pull request merged**
