### PR TITLE
[16.0][MIG] account_usability

### PR DESCRIPTION
**Pull request by legalsylvain**
[MIG] account_usability from 15.0 to 16.0

- account.tax.group views : remove views as there are now included in odoo account module
- account.account.template views : port privatized views in odoo 16.0 from Odoo 15.0 CE.
- account.account.tag views : adapt to V16
- account.fiscal.position.template views : add missing fields
- account.group views : adapt to V16
- account.type views : remove as the model disappeared
- account.chart.template views : port privatized views in odoo 16.0 from Odoo 15.0 CE.
- improve documentation
- FIX : remove useless duplicated fr_FR.po file
- ADD : display again 'Show full accounting features' group that is hidden in CE release

### CODE REVIEW

**Comment by alexis-via** [comment]
I don't think it's a good idea to put my xx_usability modules in OCA. My usability modules are a patchwork of small things that improve/fix usability issues on the official module ; it's against the concept of an OCA module !

**Review by alexis-via — APPROVED** [review]

**Review by rafaelbn — APPROVED** [review]
/ocabot merge patch

**Comment by legalsylvain** [comment]
Hi reviewers. could you take a look on this patch ? #1559 ? 

Thanks !

**Pull request merged**
