### PR TITLE
[15.0][MIG] account_move_print

### PR DESCRIPTION
**Pull request by emadshaaban92**

### CODE REVIEW

**Comment by HviorForgeFlow** [comment]
@emadshaaban92 can you review https://github.com/OCA/account-financial-tools/pull/1277? Once it is moved forward we can keep history in this PR, Thanks!

**Comment by HaraldPanten** [comment]
> @emadshaaban92 can you review #1277? Once it is moved forward we can keep history in this PR, Thanks!

V14 Migration is being merged. 👍

**Comment by emadshaaban92** [comment]
> @emadshaaban92 can you review #1277? Once it is moved forward we can keep history in this PR, Thanks!

Done

**Comment by rafaelbn** [comment]
Hello @emadshaaban92 , please could you rebase? 👍

**Comment by emadshaaban92** [comment]
> Hello @emadshaaban92 , please could you rebase? +1

Done

**Review by rafaelbn — APPROVED** [review]
Functional review 👍 

I personally miss the address of the company but also I don't have this need so up to you 😄 

imagen

**Comment by rafaelbn** [comment]
Hello @AlvaroTForgeFlow @JordiBForgeFlow , maybe you want to review this module that you did 😄

**Comment by HaraldPanten** [comment]
Please, check pre-commit

**Comment by emadshaaban92** [comment]
> Please, check pre-commit

Sorry, I did the rebase in a different environment so the pre-commit didn't run.
Now it should work

**Review by hitrosol — APPROVED** [review]
LGTM

**Pull request merged**
