### PR TITLE
Add support for Bitcoin as a currency.

### PR DESCRIPTION
**Pull request by rossigee**
dJust clearing down some patches from a local dev folderan figured that some people might find this useful. Putting it out there for 9.0, as that's what I developed and tested it on and am currently using it with. Will submit separate PR for 10.0 once I've had a chance to update and re-test it on that.

### CODE REVIEW

**Comment by rossigee** [comment]
I don't have access to a printer right now, so I can't print or sign the CLA. I've put it on a USB stick, maybe I'll get time at some point to find someone who can print it for me.

I understand the need for a CLA, but couldn't it at least be one that is digitally signed? Printing/signing things is so 20th century :)

**Comment by sbidoul** [comment]
@rossigee a digitally signed PDF is acceptable too.

**Comment by rossigee** [comment]
@sbidoul - that's great - where can i find more info about how to do that?

The CLA page only talks about printing, scanning and e-mailing.

**Comment by adrienpeiffer** [comment]
@rossigee I think you can download the PDF, sign it digitally and send it by email at cla@odoo-community.org

**Comment by rossigee** [comment]
@adrienpeiffer - ICLA file PGP-signed and attached to e-mail, as requested.

**Pull request closed without merging**
