### PR TITLE
[14.0][FIX] account_asset_management

### PR DESCRIPTION
**Pull request by ps-tubtim**
Cherry-pick https://github.com/OCA/account-financial-tools/pull/1127

### CODE REVIEW

**Review by HaraldPanten — APPROVED** [review]
LGTM

**Review by Saran440 — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
can you add the module name in the last commit message so it doe snot look so generic? Ty!

**Comment by ps-tubtim** [comment]
@AaronHForgeFlow The last commit updated.

**Comment by ps-tubtim** [comment]
The commit `8de035b` fix `_check_dates` function when `method_end` is False.

**Pull request merged**
