### PR TITLE
[15.0][MIG] account_fiscal_position_vat_check

### PR DESCRIPTION
**Pull request by Shide**
Straight migration of account_fiscal_position_vat_check

Migrated after https://github.com/OCA/account-financial-tools/pull/1418

Tasks:
- Squashed/Fixup translation and administrative commits
- Bumped version

@rafaelbn @yajo please review

MT-855 @moduon

### CODE REVIEW

**Review by yajo — APPROVED** [review]
The migration looks OK.

Please attend the pre-commit error so we can merge.

**Comment by HaraldPanten** [comment]
@yajo Don't be too hasty 😂😂 I'll check this one today

**Review by HaraldPanten — APPROVED** [review]
Works like a charm. THX!

**Pull request merged**
