### PR TITLE
[13.0][FIX]account_asset_management: devaluate assets created in locked periods on the first open day

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
Fixes https://github.com/OCA/account-financial-tools/issues/1568

cc @ForgeFlow

### CODE REVIEW

**Review by rafaelbn — APPROVED** [review]
Thank you! 👍🏼

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
The idea of putting init entry is for assets started in other software. The use case you expose should work this way:

- Open the period
- Post the depreciation entry
- Change the depreciation entry date to January

So this PR should be closed in my opinion

**Comment by luc-demeyer** [comment]
I share the same opinion as @pedrobaeza on this one.

**Comment by AaronHForgeFlow** [comment]
I disagree, the depreciation cannot be posted in the past, the period is financially closed. All corrections must be done in an open period. That is a requirement for many companies.
The init entry may be introduced for a different reason, but it is affecting the depreciation anyway, so that is not a valid argument IMO.

**Comment by pedrobaeza** [comment]
You can manually change what you want, so nothing prevents you to do it in case you screwed it not declaring the assets before closing the period, but it's not something that officially should be done, and more having more frequently the case when you are putting assets already started in other software and you just want to continue with them, not to depreciate everything at the beginning.

**Comment by AaronHForgeFlow** [comment]
If no one agrees I will close this. However, I insist, covering this for me is higher priority than covering the importing of data from other software. When importing assets from other software you can create all the depreciation lines manually instead of creating the asset in a past date.

**Comment by pedrobaeza** [comment]
You can put this as an option to be selected in the asset, and False by default, but in this state, it's not acceptable.

**Comment by AaronHForgeFlow** [comment]
Ok, I will do that, thanks for considering it.

**Pull request closed without merging**
