### PR TITLE
[ADD] Add account_storno module.

### PR DESCRIPTION
**Pull request by feketemihai**

### CODE REVIEW

**Comment by feketemihai** [comment]
@StefanRijnhart How to restart runbot because it should be ok...since in the last commit i only added the OCA as authors and the previous commit was ok?

**Comment by StefanRijnhart** [comment]
I don't know of a more elegant way than amending the last commit and force push

**Comment by feketemihai** [comment]
ok...Thanks.

**Comment by feketemihai** [comment]
@elicoidal Hi Eric, could you test the module if it's ok for China as well...

**Comment by elicoidal** [comment]
@feketemihai https://github.com/feketemihai
I will do so and keep you posted although so far I always was able to 
functionally push to keep using Odoo standard feature.*
*
Eric CAUDAL

**Comment by elicoidal** [comment]
I have tested for China and so far so good: 
- accounting entries with negative numbers
- account reversal
- Refund (sales and purchases)
- Negative invoices
  I was a bit surprise at first to see that actually refund are simply replaced by negative invoices.
  One issue: in demo db, create a supplier refund. Total appears positive but balance appear as negative number. This is "normal" as the accounting entry is negative but users are gonna freak out. I would suggest to set the display as positive
  Secondly, when pay the credit note you have to force the negative number (it should be negative by default) as otherwise you end up with a double quantity. 
  Third, in this case (payment of refund), the payment numbers are negative as well in the payment voucher which I am not sure this is correct. I will have my accountant double check this point.

**Pull request closed without merging**
