### PR TITLE
[14.0][FIX] account_asset_management: smart button count inactive asset

### PR DESCRIPTION
**Pull request by KNVx**
Smart button on account_move is counting inactive assets.

This fix is included in #1135 
Please, can you review it @eantones

### CODE REVIEW

**Comment by eantones** [comment]
LGTM!

**Review by flotho — APPROVED** [review]
Easy code review 
LGTM

**Review by eantones — APPROVED** [review]

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Have you measure the performance? I think is less performant this way. You can even use `search_count` in the other for more performance.

**Comment by KNVx** [comment]
Yes, I did, queries with search or search_count do the query to database every time we refresh the invoice.
With this code, the move lines and their corresponding assets are cached, so there's no access to db.

**Comment by pedrobaeza** [comment]
OK, please put such comment that is preferred over `search_count` or `read_group` for benefiting from the cache.

**Comment by KNVx** [comment]
The same way to recover assets is added in the action view assets

**Comment by eantones** [comment]
Rebased and conflicts solved. Can it be merged?

**Pull request closed without merging**
