### PR TITLE
[10.0][MIG] account_reversal migration

### PR DESCRIPTION
**Pull request by Cedric-Pigeon**
Odoo added the reversal feature in core. So this migration rebase the behavior on standard wizard.

- [x] Depends on: https://github.com/odoo/odoo/pull/15179

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why are you not taking commit https://github.com/OCA/account-financial-tools/commit/4ff1b53966f07d55d0ac41a126408a2506bea3dc from 9.0?

**Comment by Cedric-Pigeon** [comment]
@pedrobaeza Correct me if I am wrong but it doesn't use odoo core methods to reverse moves which I think it is not good

**Comment by pedrobaeza** [comment]
They are not using it because Odoo rejected to put hooks, which can be the same thing that now. Anyway, start from it, and change to the hooks, but don't discard the rest of the improvements and don't screw up the migration path (you should provide migration scripts if changing something of the DB layout).

**Comment by Cedric-Pigeon** [comment]
@pedrobaeza ok I will redo my PR based on it

**Comment by pedrobaeza** [comment]
Thanks for your consideration

**Comment by Cedric-Pigeon** [comment]
@pedrobaeza done

**Review by sbidoul — APPROVED** [review]
Tested on runbot. Works fine. No code review.

**Comment by guewen** [comment]
The `from openerp` should be replaced by `from odoo`

**Comment by florian-dacosta** [comment]
I don't think that using the native Odoo method `_reverse_move` is a good idea.
I agree that it is usually better to use odoo core method, but in this case, from what I saw in version 9, it is way to slow.
I was trying to reverse an journal entry with 1300 lines in version 9, and I never could because it was so slow... (the `write` on account.move.line last forever!)
I installed the oca module and then I could reverse my journal entry with 1200 line in 1 minute and 20 sec.

So, the odoo method works for small  journal entry, but for big one, it just does not work (at least in version 9. I could not test in version 10 because I haven't big database at disposal, but since the code is the same, I guess the problem remains.)

That's why, for me, this part from version 9 is essential : https://github.com/OCA/account-financial-tools/blob/9.0/account_reversal/models/account_move.py#L23

**Comment by sbidoul** [comment]
@florian-dacosta interesting argument indeed!

**Comment by grindtildeath** [comment]
I opened a PR (https://github.com/acsone/account-financial-tools/pull/4) on your branch with odoo import and a test case using 200 move_lines to monitor processing time.
So it seems that @florian-dacosta is right when saying it's quite slow.

**Comment by max3903** [comment]
Ping

**Comment by sbidoul** [comment]
@Cedric-Pigeon can you have a look?

**Comment by Cedric-Pigeon** [comment]
Hello all, regarding your last comments about performance I will re-work my PR to skip Odoo standard feature

**Comment by Cedric-Pigeon** [comment]
@sbidoul @florian-dacosta  @grindtildeath Changes done, performance are effectively better.

**Review by max3903 — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@Cedric-Pigeon can you please squash together all "OCA Transbot" commits plus the un-meaningful ones from you using the guide https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests?

Or should I do it for you?

**Pull request merged**
