### PR TITLE
[11.0][MIG] account_move_batch_validate

### PR DESCRIPTION
**Pull request by grindtildeath**
supersedes #711 since contributor github account was deleted.

### CODE REVIEW

**Comment by grindtildeath** [comment]
@simahawk @tschanzt Can you please move your reviews here ?

**Review by simahawk — APPROVED** [review]

**Comment by simahawk** [comment]
@yelizariev @sbidoul @adrienpeiffer anyone willing to pass by for a review? :innocent:

**Review by sbidoul — APPROVED** [review]
Looks good. Nice to remove the bare commit. (code review only)

**Review by adrienpeiffer — APPROVED** [review]
LGTM

**Pull request merged**
