### PR TITLE
[ADD][11.0] Multipartner bank account

### PR DESCRIPTION
**Pull request by mlaitinen**
A module that replaces the bank account (`res.partner.bank`) SQL constraint with a Python constraint and allows overriding it in the user interface.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Bank account is not something in account, but base module, isn't it? So the name might be something like `partner_bank_account_non_unique` and go to OCA/bank-payment

**Comment by pedrobaeza** [comment]
Any way, this is dangerous, as the constraint is there for ensure an unique result when matching in certain places (like in bank statement import) the bank account, so this may lead to errors in code (like singleton error) or unexpected behaviors at least, so put a BIG WARNING about that and I don't advise the use of this module.

**Comment by mlaitinen** [comment]
:+1: I'll create a new MR to OCA/bank-payment.

It is indeed dangerous, but we have very valid use-cases from at least two clients. How do you deal with  two vendor bills from two different vendors that use the same bank account (eg. the same factoring service which isn't their own bank account)?

**Comment by sbidoul** [comment]
cc/ @chrisdec @gva-acsone

**Comment by pedrobaeza** [comment]
But they are different vendors with different VAT number? That's forbidden in our country.

**Comment by mlaitinen** [comment]
They are two different vendors and the only thing they have in common is that they are using the same invoice factoring service. And this factoring service has the same bank account number for both vendors. The only differentiator is the payment reference that is used to identify the correct company that should in the end receive the money.

At least in Finland it's not forbidden. https://en.wikipedia.org/wiki/Factoring_(finance)

**Comment by sbidoul** [comment]
If the use case is factoring, I'm not sure releasing the uniqueness constraint on bank accounts is the best path.

Perhaps the factoring case must be handled at payment time (eg having the user explicitly say he wants to pay the invoice to a different bank account / partner than the one of the invoice).

**Comment by pedrobaeza** [comment]
Yeah, that's the path IMO too

**Comment by mlaitinen** [comment]
The current process with this module is this:

1. Vendor bills are fetched from an einvoicing service to Odoo
1. A vendor bill with a factoring account fails to create a new bank account because it already exists under a different vendor
1. The user will see the missing account, override the constraint manually and add the duplicated bank account (only performed once per partner)
1. The user either pays the invoice online or uses Odoo to create a payment order
1. A bank statement is fetched from the bank to Odoo
1. The bank statement line is reconciled with the invoice and the invoice is marked as paid.

If you have a separate factoring partner just for this purpose:
- you won't be able to add it to the payment order from the invoice
- the factoring partner will have negative receivables and the vendor receivables will never get reconciled.

**Comment by pedrobaeza** [comment]
Then IMO you have to:

- Modify e-invoicing service for fetching existing bank account (if any) or create it.
- Link that bank account in the invoice.

No more...

**Comment by mlaitinen** [comment]
That, in turn, would also require changing the domain of the `account.invoice.partner_bank_id` field in a way that you can select any bank account, which also sounds pretty dangerous. And this solution would still cause the imbalance in the receivables of the vendor and the factoring company.

**Comment by pedrobaeza** [comment]
Not really. The domain is only for UI, and you are feeding this from a webservice that can put any "random" data in that field. Any way, current domain in bank account field (standard and bank-payment modified one) is broken depending on the use case.

**Comment by mlaitinen** [comment]
Yes, I checked that it's only for the UI, but isn't it kind of bad user experience if an existing value disappears from the Many2one list when the user touches it? I can already see the tickets in our helpdesk "Help! Bank account was there but now it's lost and we can't select it". And then our helpdesk heroes have to enter Odoo shell and restore the bank account on the invoice.

The threat I see in this model is:

1. Vendor bill X from vendor A arrives in Odoo. Odoo can't find the (factoring) bank account so it creates it under vendor A. No problems so far.
1. Vendor bill Y from vendor B arrives in Odoo. Odoo finds the bank account of vendor A and uses that on the invoice.
1. Vendor bill Y is paid. Vendor B still has the original receivables, but oddly enough the receivables of Vendor A are negative.

Your comments give me new thoughts, thanks for sharing them. I'm afraid whatever the "clean" and safe solution is, it will be complicated.

**Comment by pedrobaeza** [comment]
For better UX, you can have an extra field "factoring partner", that makes on the background the assignation, domain and the rest of the dirty work.

**Comment by yung-wang** [comment]
@mlaitinen and @pedrobaeza 
In the Netherlands we have the same problem. Especially when you're doing business with persons. You can have a bankaccount with multiple persons to be holder of the bankaccount. When 2 persons order for ex. a phone for themself, they need to be registered as different partners/person in Odoo. But they use the same bankaccount. You also want to have the open items belonging to the correct person.

@astirpe Maybe interesting for you.

**Pull request closed without merging**
