### PR TITLE
Merge 7.0 into 8.0

### PR DESCRIPTION
**Pull request by lepistone**
This is a prerequisite for being able to cleanly rebase #52.

### CODE REVIEW

**Comment by rdeheele** [comment]
thanks @lepistone , :+1:

**Comment by sbidoul** [comment]
:+1:  Thanks!

**Comment by pedrobaeza** [comment]
But what about https://github.com/OCA/account-financial-tools/pull/52?

**Comment by rdeheele** [comment]
@pedrobaeza dixit @lepistone in last comment on #52 : Once #144 is merged, we can git rebase -X ours #52 against 8.0 and it should work ( @lepistone tried locally).

**Comment by pedrobaeza** [comment]
OK, I only read the final part, sorry

:+1:

**Pull request merged**
