### PR TITLE
[13.0][TEST][DO NOT MERGE][MIG] account_type_menu: Migration to 13.0

### PR DESCRIPTION
**Pull request by pedrobaeza**

### CODE REVIEW

**Comment by dreispt** [comment]
Hello @pedrobaeza, any particular reason to drop this PR ?

**Comment by pedrobaeza** [comment]
Yes, it's not needed AFAIK. There's now https://github.com/OCA/account-financial-tools/tree/13.0/account_menu. Anyway, this was a test for other reason (Maybe CI).

**Comment by dreispt** [comment]
Hmm, I don't think that other module works well if installed on Enterprise.
I I'll probably still need this one.

**Comment by pedrobaeza** [comment]
Then feel free to take this branch as base.

**Pull request closed without merging**
