### PR TITLE
[MIG] account_loan: Migration to 15.0

### PR DESCRIPTION
**Pull request by adrienpeiffer**

### CODE REVIEW

**Review by etobella — APPROVED** [review]
Migration seems easy, and CI is not complaining, so +1 from my side :smile:

**Review by qgroulard — COMMENTED** [review]
Functional review: impossible to create loans payment via the wizard.

image

**Comment by alexeirivera87** [comment]
Hello, any news on this PR ?

regards

**Comment by bosd** [comment]
@adrienpeiffer Can you rebase to retrigger the creation of a runboat?

**Pull request merged**
