### PR TITLE
[14.0][ADD] account_sequence_option

### PR DESCRIPTION
**Pull request by kittiu**
Moved from https://github.com/OCA/account-invoicing/pull/932

### CODE REVIEW

**Comment by HaraldPanten** [comment]
I think this travis failure would be solved by --> https://github.com/OCA/account-financial-tools/pull/1300

Just wait until we can rebase 👍

**Comment by kittiu** [comment]
@HaraldPanten thank you very much for help following up on this. :)

**Review by HaraldPanten — APPROVED** [review]

**Comment by HaraldPanten** [comment]
@pedrobaeza is it OK for merging? THX

**Comment by HaraldPanten** [comment]
@kittiu THX for your nice contribution!

**Pull request merged**
