### PR TITLE
update travis config

### PR DESCRIPTION
**Pull request by gurneyalex**
use UNIT_TEST rather than maintain complex include/exclude rules

### CODE REVIEW

**Comment by tafaRU** [comment]
:+1:

**Comment by bwrsandman** [comment]
While you're at it, please remove .coveragerc as it is supplied by MQT

**Comment by guewen** [comment]
:+1:

**Comment by gurneyalex** [comment]
Note: builds with this config take way to much time, and we are finding this difficult to cope with in OCA/vertical-ngo and we are reverting the change. Maybe you'll want to do the same here.

**Pull request merged**
