### PR TITLE
[FIX] account_chart_update: fix None context issue

### PR DESCRIPTION
**Pull request by sbidoul**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1: 

About this module, I made a test with changes in spanish chart of accounts, and I think there is something wrong, because it matches incorrectly taxes and tax codes, but I'm going deeper before putting any issue.

**Comment by sbidoul** [comment]
Hi Pedro, It matches correctly for Luxemburg. But indeed the code in _map_tax_(code)_template is complex and fragile as it attemps to match on code and/or name...

**Comment by yvaucher** [comment]
:+1:

**Comment by Cedric-Pigeon** [comment]
:+1:

**Pull request merged**
