### PR TITLE
[15.0][FIX] account_move_line_purchase_info: separate vendor bills from journal entries on PO

### PR DESCRIPTION
**Pull request by DavidJForgeFlow**
Journal entries and Vendor Bills appear mixed in Vendor Bills button on Purchase Order Form, I separated them. 

@ForgeFlow

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
Functional and technical review :+1:

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by JuanyDForgeflow — APPROVED** [review]
Functional review :+1:

**Review by AaronHForgeFlow — CHANGES_REQUESTED** [review]
Can you make the Journals entries button to be invisible when the number of journal entries is zero?

Also, the button should be visible to account users only:

**Comment by DavidJForgeFlow** [comment]
> Can you make the Journals entries button to be invisible when the number of journal entries is zero?
> 
> Also, the button should be visible to account users only:
> 
> 

Done!

**Comment by adrienpeiffer** [comment]
I'm not sure to understand your description related to the changes you made. You just add a new smart button showing the journal entries. Invoices are already filtered in the base addon right ? https://github.com/OCA/account-financial-tools/blob/15.0/account_move_line_purchase_info/models/purchase_order.py#L13

**Comment by DavidJForgeFlow** [comment]
> I'm not sure to understand your description related to the changes you made. You just add a new smart button showing the journal entries. Invoices are already filtered in the base addon right ? https://github.com/OCA/account-financial-tools/blob/15.0/account_move_line_purchase_info/models/purchase_order.py#L13

It wasn't working correctly, some journal entries were appearing in vendor bills view. I just fixed it and make the journal entries have their own button

**Comment by adrienpeiffer** [comment]
I don't see where you fix the existing button/action

**Comment by DavidJForgeFlow** [comment]
> I don't see where you fix the existing button/action

The purchase_order.py file wasn't in __init__.py, I just added it

**Comment by adrienpeiffer** [comment]
Oh :smile: Thanks !

**Review by adrienpeiffer — APPROVED** [review]

**Pull request merged**
