### PR TITLE
[10.0] [MIG] account_invoice_currency

### PR DESCRIPTION
**Pull request by seb4itik**
Hi,
My first pull request...

### CODE REVIEW

**Review by seb4itik — COMMENTED** [review]
Mistake in commit message: company_currency_id is already defined in account.invoice, not in res.company !

**Comment by pedrobaeza** [comment]
You need to follow the migration guide and respect commit history: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0. You will save for sure a lot of work too.

**Comment by seb4itik** [comment]
@pedrobaeza: I am afraid I dont't understand what I have done wrong.

**Comment by pedrobaeza** [comment]
Follow these instructions to get the commits that are in 9.0 branch, but not in 10.0 one (because the module migration to 9.0 was made after the 10.0 branch creation): https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0#technical-method-to-migrate-a-module-from-90-to-100-branch

**Comment by seb4itik** [comment]
@pedrobaeza : Thanks for the advice, I will follow the procedure and submit a new PR in 2/3 weeks.

**Pull request closed without merging**
