### PR TITLE
[12.0][ADD] account_invoice_reversal, base_account_reversal

### PR DESCRIPTION
**Pull request by kittiu**
This module allow cancel account document, i.e., Invoice by using journal entry reversal.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Odoo standard already includes reversal options, and we had in previous version (not needed now), the module `account_reversal`. Why a new one?

**Comment by kittiu** [comment]
> Odoo standard already includes reversal options, and we had in previous version (not needed now), the module `account_reversal`. Why a new one?

We have been discussing about this in OCA mailing list - https://odoo-community.org/groups/contributors-15/contributors-130821

Basically, that account_reversal (which is now in core) only reverse journal entry and not cancel invoice (invoice stay paid). Our country accounting practice will need it.

From the email, I aware now that accounting practice are varied by country. And so, I am thinking about moving it l10n-thailand if no one need this feature. WDYT?

Note: I split it to base_account_reversal + account_invoice_reversal, as I though about doing account_payment_reversal later. In future, we could do the same for other front documents if required.

**Comment by pedrobaeza** [comment]
I find this a bit over-engineered for such a "small" addition over basic accounting reversal, but I haven't dug too much on the code.

**Comment by kittiu** [comment]
@pedrobaeza thank you very much for your comment.

There are basically 2 part.
1) base_account_reversal - will add the setting option in Journal, if allow cancel -> make it reversal?
Also it has common reversal wizard (to choose date and journal) and mock function that allow other module to extend to do this kind of cancel reversal (so other module follow same pattern)
2) account_invoice_reversal - to extend the base, and do the real reversal.

Will it be better if I remove the option to setup and just do it for invoice ? (so it end up only 1 simple addon, e.g., account_invoice_reversal)

I am ok to minimize it too, I still not sure if there will be other document that repeat.

**Comment by pedrobaeza** [comment]
IMO it's better to have only 1 module, but let's see other opinion. The same way, I would plug this on the refund invoice wizard instead of a new one.

**Comment by kittiu** [comment]
> IMO it's better to have only 1 module, but let's see other opinion. The same way, I would plug this on the refund invoice wizard instead of a new one.

OK, I will wait a bit and see if any other people have opinion before minimize it (as another PR). I disagree to do it on refund invoice wizard, for us it misleading. If Journal is set to "Allow Cancel", I would rather use this same cancel button, but with reversal.

**Comment by JordiBForgeFlow** [comment]
@kittiu I have reviewed the module and it's awesome. In my past experience with reversals in SAP, you could cancel and invoice, and it would generate a reversal document, just as you are proposing.

But, the invoice would be ready to be reset to draft again, and when you validate again a new journal entry would be created.

This approach would not break the usability for the user. If he's made a mistake on an invoice he can just cancel the invoice, set it back to draft and post it. Behind the scenes the system creates the reversals.

I have implemented this approach in this branch (for some reason I can't do a PR to your repo):
https://github.com/Eficent/account-financial-tools/tree/12.0-add-account_invoice_reversal-jba

**Comment by kittiu** [comment]
@jbeficent thanks for your review. There are some point, I like to discuss. Let me summarize based on my understanding.

**My points**
1. Invoice, once cancelled, it should not allow set to draft. User should create new invoice from SO again.
2. Payment, once invoice is cancelled, it will be back to unreconciled and can use to pay other invoice again, or do payment return (or payment cancel). I do not plan to delete the payment nor its journal entries.

**Your points**
1. Invoice, once cancelled, can set to draft and re-validate again (to create new journal entry)
2. Payment, once invoice is cancelled, delete it and also its journal entries.

**(1)** I would like to argue. If it can set to draft, the link of that invoice to be broken. When new journal entry is created, invoice link to new journal entry and the number of invoice will also skip without trace.
**(2)** Deletion of payment is prohibited, it will make number skips. It will also delete journal entry, which I am quite disagree. (if we don't want that payment, why not just cancel it?, we can do account_payment_cancel the same way).

I think point of discussion boiled down to, allowing or not allowing the deletion of already created evidence.

Note: I also wonder, other country is not serious with deletion of evidence like us?

**Comment by JordiBForgeFlow** [comment]
@kittiu I did not talk about payment in my comments. I agree with you that you should never be able to delete a journal entry. That's what the reversal is for. I only introduced point 1). In my current branch https://github.com/Eficent/account-financial-tools/tree/12.0-add-account_invoice_reversal-jba I am removing the link between the invoice and the corresponding move_id at the time when the invoice is cancelled. It makes more sense to me.

**Comment by kittiu** [comment]
@jbeficent sorry, I just mix the point on email with this. Let's discard the payment from here.
On you branch https://github.com/Eficent/account-financial-tools/tree/12.0-add-account_invoice_reversal-jba I don't see any commit or diff with mine. Have you push?

**Comment by JordiBForgeFlow** [comment]
@kittiu Oops. Now pushed!

**Comment by kittiu** [comment]
@jbeficent I am ok with your suggestion, it is more generic. Please see this https://github.com/kittiu/account-financial-tools/commit/665b1a09b63f09dabf16985aad3a16d17b55e127
It seem we have to unlink more relation with invoice to avoid undesired outcome.

**Review by JordiBForgeFlow — APPROVED** [review]
:+1: Technical and functional review. Works like a charm!

**Comment by ecosoft-odoo** [comment]
@jbeficent @pedrobaeza 
I am planning to continue with account_bank_statement_line_reversal and account_payment_reversal. Do you guys think this is appropriate repo to work on?

**Comment by kittiu** [comment]
Combine modules to new account_document_reversal and close this one.
https://github.com/OCA/account-financial-tools/pull/820

**Pull request closed without merging**
