### PR TITLE
[FIX] travis

### PR DESCRIPTION
**Pull request by etobella**
Travis is failing on 11.0 due to this change

@JordiBForgeFlow @OCA/accounting-maintainers

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Weird...

**Comment by etobella** [comment]
Not the first time #876

**Review by jarroyomorales — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Well, that time, there were deeper changes like PG version (which presumably was the main reason). The rest seems aesthetic.

**Comment by etobella** [comment]
Well, I have tried to launch the current 11.0 version and this PR, but travis is taking a long time nowadays...

This branch: https://travis-ci.org/github/OCA/account-financial-tools/builds/738274818
11.0 base branch: https://travis-ci.org/github/OCA/account-financial-tools/builds/719529898
Let's see if this really solves the problem

**Review by AaronHForgeFlow — APPROVED** [review]

**Pull request merged**
