### PR TITLE
[IMP] Process jobs 'validate_one_move' in a dedicated job channel

### PR DESCRIPTION
**Pull request by lmignon**
To avoid concurrent update when validating the account_move
on ir_sequence, jobs must be processed one by one. Using a
dedicated channel enable to isolate the processing of
the 'validate_one_move' jobs from the root channel

This PR is the forward port of https://github.com/OCA/account-financial-tools/pull/220

### CODE REVIEW

**Comment by guewen** [comment]
@lmignon Could you have a look at https://github.com/OCA/connector/pull/71 which allows to select a channel directly on the `@job`?

If we get it merged, it would be nice to adapt your PR, otherwise :+1:

**Comment by lmignon** [comment]
@guewen Thank you for the link. Your PR makes sense and eases the definition of channels. Once OCA/connector#71 will be merged I'll adapt the PR.

**Comment by guewen** [comment]
@lmignon OCA/connector#71 is merged

**Comment by sbidoul** [comment]
:+1:

**Comment by adrienpeiffer** [comment]
:+1:

**Pull request merged**
