### PR TITLE
[15.0][MIG] account_move_line_menu

### PR DESCRIPTION
**Pull request by koenloodts**

### CODE REVIEW

**Review by gaikaz — APPROVED** [review]

**Review by HaraldPanten — APPROVED** [review]

**Comment by rafaelbn** [comment]
Hello @koenloodts , please could you check https://github.com/OCA/account-financial-tools/pull/1294#issuecomment-1076935382 ? Do you know what the error on test means? Could you fix it ?
  Thank you!

**Comment by dreispt** [comment]
@rafaelbn I think we can try to insist with the merge, it may work.

 /ocabot merge nobump

**Review by rafaelbn — APPROVED** [review]

**Comment by rafaelbn** [comment]
@dreispt test are failing, @koenloodts are you going to look at https://github.com/OCA/account-financial-tools/runs/5684849419?check_suite_focus=true , https://github.com/OCA/account-financial-tools/runs/5684849462?check_suite_focus=true

**Review by Mantux11 — APPROVED** [review]

**Pull request merged**
