### PR TITLE
[14.0][FIX] account_sequence_option: maintain sequence of out-invoices when returning to draft and changing date.

### PR DESCRIPTION
**Pull request by angelgarciadelachica**
[FIX] When you have a posted output invoice, if you return it to draft and change the date, the invoice name is deleted and it asks again for another sequence number. This FIX prevents this from happening and keeps the name.

### CODE REVIEW

**Comment by angelgarciadelachica** [comment]
@ValentinVinagre @HaraldPanten

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by HaraldPanten — APPROVED** [review]
LGTM. @kittiu Does it seem reasonable to you?

**Comment by kittiu** [comment]
> LGTM. @kittiu Does it seem reasonable to you?

I am ok. Odoo account numbering is quite complex, so I think it need more use case like this.

**Comment by HaraldPanten** [comment]
Could you approve, @kittiu ? Then I'll merge.

THX!

**Review by kittiu — APPROVED** [review]

**Pull request merged**
