### PR TITLE
[16.0][MIG] account_asset_number

### PR DESCRIPTION
**Pull request by Saran440**

### CODE REVIEW

**Review by ps-tubtim — APPROVED** [review]
Functional Test: Ok

**Review by dreispt — APPROVED** [review]

**Comment by ljsalvatierra-factorlibre** [comment]
> /ocabot merge nobump

why did you merge this PR instead of the original https://github.com/OCA/account-financial-tools/pull/1687 ??

**Comment by Saran440** [comment]
@ljsalvatierra-factorlibre I'm very sorry, I forgot to check that the module had an origin.

**Comment by ljsalvatierra-factorlibre** [comment]
> @ljsalvatierra-factorlibre I'm very sorry, I forgot to check that the module had an origin.

Honest mistake, thank you for clarifying

**Pull request merged**
