### PR TITLE
10.0 mig currency rate update

### PR DESCRIPTION
**Pull request by nikiwaibel**
hi, this is my first pull request to OCA - hope it's all okay

### CODE REVIEW

**Comment by alexis-via** [comment]
I improved this PR and made a PR to niki's branch https://github.com/nikiwaibel/account-financial-tools/pull/1

**Review by alexis-via — APPROVED** [review]
Code review and test with ECB service

**Review by LeartS — APPROVED** [review]
👍 Code review and test with Yahoo Finance and ECB.

Just one question: I see that all `res.currency.rates` records are set as `00:00:00` time (actually `01:00:00` in my case because of the timezone, which may be a little bug), is there a reason why we can't have multiple rates per day, assuming one executes the rate updater manually?

**Comment by alexis-via** [comment]
I get a crash when I try to add "currencies to update with this service": 

```
ValueError: Invalid domain term (u'id', u'in', {u'rate_ids': [[5], [4, 129]], u'name': u'EUR', u'symbol': u'\u20ac', u'active': True, u'rate': 1, u'date': u'2010-01-01'})
```

**Comment by alexis-via** [comment]
I think we need the same kind of fix for the bug I talked about in my previous comment than the one I made for the module account_payment_order in OCA/bank-payment:
https://github.com/OCA/bank-payment/pull/354

**Comment by alexis-via** [comment]
Here is my PR to fix the bug https://github.com/nikiwaibel/account-financial-tools/pull/2

**Comment by alexis-via** [comment]
@nikiwaibel Have you signed OCA's CLA, or it is just an error of the bot ?

**Comment by nikiwaibel** [comment]
i signed it - some months ago :-)

**Comment by alexis-via** [comment]
The crash I reported 7 days ago and fixed a few days ago was caused by this bug in odoo: https://github.com/odoo/odoo/issues/16072

**Comment by alexis-via** [comment]
Fix for multi-company https://github.com/nikiwaibel/account-financial-tools/pull/3

**Pull request merged**
