### PR TITLE
Enforce tax constraint

### PR DESCRIPTION
**Pull request by bringsvor**
Addition to the account_constraints module to enable limiting postings for an account to a given tax code.

This was a customer requirement in the project I was in, and it is a common feature of other accounting systems. It can be discussed if it is really needed in Odoo where we have the possibility to mix tax codes in a single account, but the accountants wanted it anyway.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for the changes. Why are you still adding enforce_tax_account module?

**Comment by gurneyalex** [comment]
cla OK

**Comment by sbidoul** [comment]
What's the status of this one?

There are at least a few pep8 issues to fix.

**Comment by bringsvor** [comment]
Ok I have now committed fixes for the flake8 errors. Hopefully this will be all right now.

**Comment by pedrobaeza** [comment]
There's still red status and conflicts, so I'm closing this. Feel free to reopen if still interested.

**Pull request closed without merging**
