### PR TITLE
[FIX] adapt test suite for 2015 year change

### PR DESCRIPTION
**Pull request by sbidoul**

### CODE REVIEW

**Comment by sbidoul** [comment]
WIP: we will also fix the test suite for account_journal_period_close cc/ @adrienpeiffer

**Comment by sbidoul** [comment]
rebased to force travis run

**Comment by sbidoul** [comment]
:+1:

**Comment by sbidoul** [comment]
@pedrobaeza this one should be ok now, you can remove the WIP tag.

**Comment by pedrobaeza** [comment]
:+1:

**Comment by sbidoul** [comment]
@pedrobaeza can you merge this one please? It is just test suite stuff to greenify other PR's. (#51 in particular).

**Comment by lepistone** [comment]
This seems a lot of work, and I am not convinced we need it.

It seems like the year and period created in addons/account/demo/account_demo.xml are in the current year. If it is brittle to use those (and yes, it probably is), why don't we create a fixed year and period in the past (like 2013), without any logic? Like in account_demo.xml, but fixed to 2013.

**Comment by sbidoul** [comment]
@lepistone I think that's what @adrienpeiffer does in create_fiscalyear in the test suite.

**Comment by adrienpeiffer** [comment]
@lepistone It's done on  9f65f85 with the creation of an old fiscal year

**Comment by lepistone** [comment]
Hi @sbidoul @adrienpeiffer I know. I was arguing that in tests normally we want compact and readable code more than we want reuse, so I'd prefer to just directly create data in 2013 (or make tests work with the existing data created by odoo) instead of writing a method `create_fiscalyear` and then calling it with 2013.

Still, this is somewhat subjective and minor, so :+1: and I'm merging this one.

Thanks!

**Pull request merged**
