### PR TITLE
[16.0][MIG] account_sequence_option

### PR DESCRIPTION
**Pull request by Saran440**
This module migrated from https://github.com/OCA/account-financial-tools/pull/1635

### CODE REVIEW

**Comment by matteoopenf** [comment]
@Saran440 can you do a rebase?
thank you so much

**Review by patrickt-oforce — APPROVED** [review]

**Review by matteoopenf — APPROVED** [review]
functional test ok
LGTM

**Comment by matteoopenf** [comment]
@Saran440 great work

**Comment by matteoopenf** [comment]
merge?

**Comment by matteoopenf** [comment]
@simahawk is it possibile merge?

**Comment by matteoopenf** [comment]
@kittiu  can you merge also this pr?

**Pull request merged**
