### PR TITLE
[7.0] [ADD] account_invoice_groupby_state

### PR DESCRIPTION
**Pull request by veloutin**
This module adds a "Partner State" grouping for invoices.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
State can be confused with the current "status". I think you can make this with related fields instead such a complex function, don't you think?

Anyway, I see this module too little for being included. What others think?

**Comment by veloutin** [comment]
I agree "State" is confusing, is there a better word for it?

About using related fields, groupby only words on database-persisted fields, that is why I used a function.

**Comment by pedrobaeza** [comment]
But you can store also a related field.

**Comment by sbidoul** [comment]
I share Pedro's comments.
- a related field would be easier to read
- I'm also concerned that the use case is possibly too narrow for inclusion in OCA

**Comment by yvaucher** [comment]
For alternative for "State" you have: Province / Region / County (not country) / Canton and many more ...

For field state, normally they are displayed as Status. But I agree State itself is very confusing without context.
To give context to the user, you could display: "State / Province".

We could also name it Country Subdivision to be completely generic and follow ISO 3166 terms:
http://en.wikipedia.org/wiki/ISO_3166

Otherwise, a stored related field is the good way to do it.

**Comment by pedrobaeza** [comment]
As there's no answer, I close. Feel free to reopen in case there's interest.

**Pull request closed without merging**
