### PR TITLE
[10.0][FIX] account_move_line_tax_editable: Remove duplicate field in…

### PR DESCRIPTION
**Pull request by rousseldenis**
… view

The move_id field already exists in view. The duplicated one disable the first one

### CODE REVIEW

**Comment by rousseldenis** [comment]
@eantones @pedrobaeza @sbidoul @benwillig

**Comment by rousseldenis** [comment]
Introduced in https://github.com/OCA/account-financial-tools/pull/656

**Review by sbidoul — APPROVED** [review]

**Review by benwillig — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Why is Travis red?

**Comment by rousseldenis** [comment]
It seems this is something else because it is account move locking module related.

I have already seen this on another branch I have(before submitting this PR).

**Review by eantones — APPROVED** [review]

**Pull request merged**
