### PR TITLE
[14.0][ADD] account_asset_low_value

### PR DESCRIPTION
**Pull request by kittiu**
Low-Value Asset (LVA) are typically asset with low values and was booked as expense on purchase.
In essence, the low value asset is not really and asset but an expense need to tracke as asset.
As such, it has no residual value, run no depreciation. And when removed, only status is changed (no accounting entry).

To create low value asset, use the Asset Profile with following setting,

1. Asset Account = Expense (low value asset)
2. Number of Years = 0

### CODE REVIEW

**Comment by ps-tubtim** [comment]
I think you should add a **Note** like a normal case to write some things such as the reason for removal.

Selection_146

**Comment by kittiu** [comment]
For normal asset, normally, the Note will be updated into the created Journal Entry. 
But for Low Value, the fact that it will not create new Journal Entry, so, I don't know where to update it.

If you want to update the remove reason back to the asset itself, you will need to enhance account_asset_management itself in another PR, WDYT?

Note: I am fine with having the reason back to the Asset itself too.

**Review by Saran440 — APPROVED** [review]
Functional Test :+1:

**Review by ps-tubtim — APPROVED** [review]
LGTM

**Comment by kittiu** [comment]
@Saran440 would you help rebase. Thanks.

**Pull request merged**
