### PR TITLE
[16.0][MIG] account_move_line_purchase_info

### PR DESCRIPTION
**Pull request by astirpe**

### CODE REVIEW

**Comment by astirpe** [comment]
@RodrigoBM rebased

**Review by AaronHForgeFlow — APPROVED** [review]
LGTM, functional

**Review by RodrigoBM — CHANGES_REQUESTED** [review]
Selección_382

The name of the line should not have to be "[P00016] wwwwwww (Purchase Order)"

```
name = "[{}] {} ({})".format(
    line.order_id.name, name, line.order_id.state
    )
```

**Comment by RodrigoBM** [comment]
ping @astirpe

**Comment by astirpe** [comment]
@RodrigoBM thanks! Fixed in https://github.com/OCA/account-financial-tools/pull/1616/commits/7741880d6587743a1b82df85704966a83bf69457 but I had to add a new module as dependency (base_view_inheritance_extension).

**Review by RodrigoBM — APPROVED** [review]

**Comment by RodrigoBM** [comment]
ping @AaronHForgeFlow

**Comment by AaronHForgeFlow** [comment]
/ocabot migration account_move_line_purchase_info
/ocabot merge nobump

Thank you guys, accepting the new dependency in order to keep same functionality

**Pull request merged**
