### PR TITLE
[18.0][MIG] account_usability: Migration to 18.0

### PR DESCRIPTION
**Pull request by peluko00**
Module migrated to version 17.0

cc https://github.com/APSL 163108

@miquelalzanillas @lbarry-apsl @mpascuall @javierobcn @BernatObrador @ppyczko please review

- [Issue] https://github.com/OCA/account-financial-tools/issues/1944

### CODE REVIEW

**Review by BernatObrador — APPROVED** [review]
LGTM

**Review by mpascuall — APPROVED** [review]
LGTM, tested in runboat

**Review by ppyczko — APPROVED** [review]
LGTM!

**Comment by houssine78** [comment]
@peluko00 do you know why the test are failing ? I've checked the logs but nothing came out from the logs.

**Review by houssine78 — APPROVED** [review]
LGTM

**Comment by houssine78** [comment]
@legalsylvain this PR is ready for merging even if the test fail for no reason I can see.

**Review by legalsylvain — CHANGES_REQUESTED** [review]
Hi. thanks for porting this module ! 

Could you cherry-pick this commit ? https://github.com/OCA/account-financial-tools/pull/1970

so the V18 module has all the latest improvment.

**Comment by legalsylvain** [comment]
> @legalsylvain this PR is ready for merging even if the test fail for no reason I can see.

"2024-11-07 11:59:47,713 241 WARNING odoo odoo.tests.result: 0 failed, 0 error(s) of 0 tests when loading database 'odoo' "

CC : @OCA/community-maintainers, @sbidoul, I don't remember exactly. Is it related to a new thing introduced in V18 CI ?

**Comment by sbidoul** [comment]
The tests fail because there are no tests.

**Comment by peluko00** [comment]
> Hi. thanks for porting this module !
> 
> Could you cherry-pick this commit ? #1970
> 
> so the V18 module has all the latest improvment.

Done! Can tou review again @legalsylvain  please?

**Comment by sbidoul** [comment]
> The tests fail because there are no tests.

So this will resolve itself as soon as another module with tests has been merged.

**Comment by StefanRijnhart** [comment]
@sbidoul I see other PRs battling this issue successfully with the following `checklog-odoo.cfg`.
```
[checklog-odoo]
ignore=
	WARNING.* 0 failed, 0 error\(s\).*
```

**Comment by sbidoul** [comment]
@StefanRijnhart yes that works too. I don't know if the problem is prevalent (as it happens only in repos without tests) and if it's worth adding to the project template.

**Comment by StefanRijnhart** [comment]
I've seen it four times now. It's when modules are split up very granularly and a module without any logic is the lowest dependency in a dependency chain, it's also likely to be the first to be migrated from a repo.

**Review by alexis-via — APPROVED** [review]

**Comment by legalsylvain** [comment]
>  don't know if the problem is prevalent (as it happens only in repos without tests) and if it's worth adding to the project template.

I see it many times on V18. In fact, prevalent or not, it's an error that should be fixed. CI can not be red, if the proposal is valid. here (and in other PRs) the code is valid. So it should be green.

**Review by legalsylvain — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Superseded by #1981

**Pull request closed without merging**
