### PR TITLE
[MIG] account_loan: Migration to 13.0

### PR DESCRIPTION
**Pull request by albariera**
Adapted to new invoice logic.

### CODE REVIEW

**Comment by etobella** [comment]
This will probably need a migration script from 12 to 13.

**Comment by ghost** [comment]
There is a bug when using numpy's pmt function. The financial functions in NumPy are deprecated and eventually will be removed from NumPy. This package is the replacement for the original NumPy financial functions, 'numpy-financial'.

**Comment by albariera** [comment]
> There is a bug when using numpy's pmt function. The financial functions in NumPy are deprecated and eventually will be removed from NumPy. This package is the replacement for the original NumPy financial functions, 'numpy-financial'.

**Comment by albariera** [comment]
Thank you for the review. Comments attended :+1: 
@etobella @alfonsomb

**Review by etobella — APPROVED** [review]
Finally green :green_apple: :green_apple: :green_apple:

**Comment by etobella** [comment]
@alfonsomb could you review this please?

**Comment by ghost** [comment]
> @alfonsomb could you review this please?

It is right!

**Review by AaronHForgeFlow — APPROVED** [review]
Functional review :+1:

**Pull request merged**
