### PR TITLE
[12.0][MIG]account_lock_to_date

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
Based on #https://github.com/OCA/account-financial-tools/pull/815

Tasks done:
- [x] "Standard" Migration
- [x] Rebranding

cc @ForgeFlow

### CODE REVIEW

**Review by AdriaGForgeFlow — APPROVED** [review]
Code review :+1:

**Review by ivantodorovich — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
