### PR TITLE
[12.0] depreciated translations (hr_HR) cleanup

### PR DESCRIPTION
**Pull request by badbole**
clenup of old/depreciated hr_HR translations in favor of new (created) hr translations.

### CODE REVIEW

**Review by HaraldPanten — CHANGES_REQUESTED** [review]
Hi @badbole I think you missed something in your last commit.

By the way, why don't you change translations using Weblate? 🤔

You should check this. THX!

**Comment by badbole** [comment]
@HaraldPanten could you point what am i missing?
as for traslations.. 
did not find proper way TO REMOVE obsolete/depreciated translations.. 
and i am translating modules on weblate, but due to changes in translations , 
"hr_HR" is not used anymore, in favor of "hr" translations... 
could you please suggest the proper way to remove old trasnlations and cleanup mess?

**Comment by HaraldPanten** [comment]
Hi @badbole 

1- Is it possible that you didn't push any changes in your last commit? That's what I'm talking about.  I see several changes in the other ones but not in the last one.

2- You're working on different modules translations: account_asset_management, account_balance_line, account_chart_update... IMO you should do 1 PR for each module changes.

I think this would help 👍

**Comment by badbole** [comment]
@HaraldPanten  I agree on missing files... i see i reverted the repo for other PR.. 
for now i will close this PR without merging. 
for future... if the PR is only for cleanup obsolete translations, 
should i make a PR for each module in repo or is it sufficient to do it in only one PR.. 
( this way, it is only one commit stays in git history for entire repo, wich removes unneded files... without changing anything else?)

**Comment by HaraldPanten** [comment]
> @HaraldPanten I agree on missing files... i see i reverted the repo for other PR..
> for now i will close this PR without merging.
> for future... if the PR is only for cleanup obsolete translations,
> should i make a PR for each module in repo or is it sufficient to do it in only one PR..
> ( this way, it is only one commit stays in git history for entire repo, wich removes unneded files... without changing anything else?)

@badbole hhhmmm... good question. AFAIK you should open a PR for each module changes.

I recommend you to open an issue to ask how to manage this situation. I'm sure that any of the repository PSC would advice you on how to manage these use cases as I'm not 100% sure on how you should do that.

**Pull request closed without merging**
