### PR TITLE
[14.0][ADD] account_move_update_analytic_account

### PR DESCRIPTION
**Pull request by remi-filament**
Add new module allowing to update account analytic on posted moves
(Note that although model has changed, this is now allowed in v16)

### CODE REVIEW

**Comment by rafaelbn** [comment]
Hello @remi-filament , great! this could be really useful!

What about analytic tag? 😄 

I should test this one!

**Comment by fclementic2c** [comment]
Great idea this module. Thanks. I will test it.
I would suggest to use the branch : https://github.com/OCA/account-analytic instead. Don't you think  ?

**Comment by fclementic2c** [comment]
cannot test - Runbot could't start

**Comment by remi-filament** [comment]
Hi @rafaelbn it should be quite straight forward if this module makes sense for other than us to add analytic tags in same wizard.
I give it a first try, but since we are not using these tags I was not sure if it made sense as well or not and it meant I had to manage access rights in wizard to apply changes or not (since for instance if you do not use analytic tags, the field would remain empty (since not diplayed), but does that mean that you have to empty the analytic tags for everyone or is it only because you do not see the field ?)

Let me know what you think about this first version and how it should work for analytic tags from your point of view and I should be able to implement those as well.

**Comment by remi-filament** [comment]
> cannot test - Runbot could't start

Maybe because there is an issue with pre-commit ? (I have not dug into it, but it seems to be related to GitHub actions with Python 11 since I see pre-commit failing everywhere now, while it was OK on my computer...)

**Comment by remi-filament** [comment]
> Great idea this module. Thanks. I will test it. I would suggest to use the branch : https://github.com/OCA/account-analytic instead. Don't you think ?

Yes makes sense, I should move it there !

**Comment by remi-filament** [comment]
Closed as moved to account-analytic (https://github.com/OCA/account-analytic/pull/497)

**Pull request closed without merging**
