### PR TITLE
[16.0][MIG] account_move_force_removal: Migration to 16.0

### PR DESCRIPTION
**Pull request by matteoopenf**

### CODE REVIEW

**Comment by matteoopenf** [comment]
Hi @pedrobaeza, the pre commit is broken here 
image

https://translation.odoo-community.org/translate/account-financial-tools-16-0/account-financial-tools-16-0-account_invoice_constraint_chronology/pt_BR/?checksum=0677552d31f6588b&sort_by=-priority,position  I need to fix this translation, but I can't translate in this language, can you help me?

Thank you so much

**Comment by pedrobaeza** [comment]
You should fix it here in the migration, not on Weblate. The problem is that there are markers (like `%(key)s` that are not on the translation).

**Comment by matteoopenf** [comment]
> You should fix it here in the migration, not on Weblate. The problem is that there are markers (like `%(key)s` that are not on the translation).

ok thank you

**Comment by patrickt-oforce** [comment]
> You should fix it here in the migration, not on Weblate. The problem is that there are markers (like `%(key)s` that are not on the translation).

Hi Pedro, thank you for reply, but seems the solution of fix translation in migration is not working; in po file of pt_BR language ther is an error about key in message, as can be seen here https://github.com/OCA/account-financial-tools/blob/16.0/account_invoice_constraint_chronology/i18n/pt_BR.po#L68

**Comment by pedrobaeza** [comment]
You should replace `{nome}` by `{name}` in the translation. That's another kind of marker.

**Comment by matteoopenf** [comment]
> You should replace `{nome}` by `{name}` in the translation. That's another kind of marker.

I think that should be do in weblate and not in pr, but for now I do an isolated commit to fix the problem

**Comment by pedrobaeza** [comment]
Yes, indeed it should be also fixed on previous versions on Weblate, but as this is something out of our scope, let's fix it here at least.

**Comment by matteoopenf** [comment]
> Yes, indeed it should be also fixed on previous versions on Weblate, but as this is something out of our scope, let's fix it here at least.

it's ok for me, and tomorrow I will try to fix the test

**Review by andreampiovesana — APPROVED** [review]
LGTM

**Comment by matteoopenf** [comment]
@andreampiovesana questo modulo non occorre per 16.0 ho smesso di migrarlo per quello ora la chiudo la pr

**Comment by matteoopenf** [comment]
inoltre i test fallivano non ha senso approvare una pr cosi

**Comment by pedrobaeza** [comment]
Please talk in this repository in English

**Pull request closed without merging**
