### PR TITLE
Credit control: improve the reports

### PR DESCRIPTION
**Pull request by guewen**
- include the fees in the due balance
- Remove hard-coded texts which can be chosen in the level's name and text
- Add more space between sections
- remove deprecated mako template

### CODE REVIEW

**Comment by yvaucher** [comment]
:+1:

**Comment by guewen** [comment]
Rebased

**Comment by adrienpeiffer** [comment]
:+1: (Code review)

**Comment by adrienpeiffer** [comment]
@guewen After functional tests, I noticed that the totals do not include fees. 

credit_control_fees

What do you think about this  ?

**Comment by adrienpeiffer** [comment]
See on #167

**Pull request merged**
