### PR TITLE
[13.0][ADD] account_move_template_enhanced

### PR DESCRIPTION
**Pull request by kittiu**
This module enhance the capability of module account_move_template with following features,

1. Optional Account for negative amount.

   When the Journal entry is created, and credit/debit is negative value, change debit/credit
   side and use the opt_account_id

2. Allow overwrite move line values with overwrite dict.

   Normally, the journal items created by the template will require user input on wizard.
   This feature allow passing the overwrite values with a dictionary.
   This is particularly useful when the wizard is called by code.

Sample of dictionary to overwrite move lines::

  {'L1': {'partner_id': 1, 'amount': 100, 'name': 'some label'},
   'L2': {'partner_id': 2, 'amount': 200, 'name': 'some label 2'}, }

### CODE REVIEW

**Comment by kittiu** [comment]
@alexis-via I would like to propose this enhancement.
WDYT? Can it be included in account_move_template or separated.

**Comment by kittiu** [comment]
Test added, ready for review.

**Comment by kittiu** [comment]
@ps-tubtim @newtratip 
Can you help in reviewing this?

**Review by newtratip — APPROVED** [review]

**Review by ps-tubtim — APPROVED** [review]
Code and Functional tests are good.

**Comment by HaraldPanten** [comment]
Hi @kittiu ,

As you asked before I think that this could be an [IMP] of account_move_template module. I reping @alexis-via and I ping @OCA/accounting-maintainers

**Comment by kittiu** [comment]
> Hi @kittiu ,
> 
> As you asked before I think that this could be an [IMP] of account_move_template module. I reping @alexis-via and I ping @OCA/accounting-maintainers

Great! Will do.

**Comment by kittiu** [comment]
Moved to https://github.com/OCA/account-financial-tools/pull/1094

**Pull request closed without merging**
