### PR TITLE
[8.0] port account_auto_fy_sequence to 8.0

### PR DESCRIPTION
**Pull request by sbidoul**
This is a merge of 7.0 into 8.0 + minor stuff for 8.0 compliance in 2fb15b9a9c6b5888f36eb21651ed3db70d1d44f0

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you confirm that Markdown files are correctly parse on Odoo? As far as I know, I think only RST files are parsed.

**Comment by sbidoul** [comment]
The README.md is recognized by Odoo and displayed as module description. 

It seems it is parsed as reStructuredText, though. 
For instance, using # as heading markers does not work.

**Comment by pedrobaeza** [comment]
I recommend then that you put it as `README.rst` to get a consistent display on Github and Odoo.

**Comment by sbidoul** [comment]
@pedrobaeza done

**Comment by pedrobaeza** [comment]
Thanks :+1:

**Comment by lmignon** [comment]
:+1: and thank you for keeping branches in sync at least from 7.0 to 8.0!

**Pull request merged**
