### PR TITLE
[9.0][MIG] Porting of account_cost_center to V9

### PR DESCRIPTION
**Pull request by astirpe**

### CODE REVIEW

**Comment by gurneyalex** [comment]
Is this not a duplicated feature from the operating units? (https://github.com/OCA/operating-unit)

**Comment by ThijsvOers** [comment]
Hi gurneyalex,
My name is Thijs van Oers and i am a colleague of Andrea (I work as a functional consultant for Onestein). 
The difference between a cost center and the analytics around the operating units is in my opinion that the cost center refers to departments within the company that only cost money to operate, where the operating units are all about maximizing profit. The cost center module is used for example to track the cost of marketing. 
Although the operating unit module is very interesting (I just work with Odoo software for a couple of months and are exploring all the Odoo modules), i think this module is for many of our customers 'a bridge too far'.

**Comment by astirpe** [comment]
CC @jbeficent

**Comment by pmartineznetquest** [comment]
Hi all!

In my opinion it is not in conflict with the Operating Units. In contrast, these 2 modules working together provide 2 different views that mantain isolated what @ThijsvOers has commented above: the department view (Cost Center View) dedicated to Departments and their cost within the company and the Operating Units, which is a bigger and more complex concept and focused on the parameter of profit (not only Cost). They have different objectives but can live together. 

This simple module is very useful in a wide number of scenarios and simplifies a lot of work to finance staff. 

Cheers, 

Pere

**Comment by astirpe** [comment]
This PR was opened one year ago, it seems the approval process is taking a long time, if we consider that this is only a simple porting of the module already merged for version 8.0.

@ThijsvOers @pmartineznetquest thank you for the positive reviews! I also noticed that this module is used by many companies. In order to speed up the process, you may want to click the `Review changes` button in [this page](https://github.com/OCA/account-financial-tools/pull/442/files), select `Approve` and then `Submit review`.

**Review by ThijsvOers — APPROVED** [review]
tested and approved

**Review by pmartineznetquest — APPROVED** [review]

**Review by pmartineznetquest — APPROVED** [review]

**Comment by astirpe** [comment]
Rebased and squashed.

**Comment by astirpe** [comment]
Once this one is merged, I will open the PR for the porting to 10.0.

**Review by yung-wang — APPROVED** [review]
Tested on runbot. The cost center can be entered in the invoices and you see the lines in de pivot analysis. Please merge

**Comment by astirpe** [comment]
Merge?

**Comment by pedrobaeza** [comment]
Please squash together adjacent "OCA Transbot.." commits using https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

**Comment by astirpe** [comment]
@pedrobaeza done. Thanks!

**Pull request merged**
