### PR TITLE
[13.0][FIX] account_asset_management: use onchange_helper rather than odoo test Form

### PR DESCRIPTION
**Pull request by vincent-hatakeyama**
The test Form is not meant to be used in non test code ; this change uses onchange_helper to handle the issue that caused the use of Form.

### CODE REVIEW

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
It can be perfectly used with no drawbacks, and changing dependencies of a stable module and more in such old versions is not acceptable.

**Comment by vincent-hatakeyama** [comment]
The classes are in odoo.tests, this is a strong indication they are meant to be used in tests only. Using the module to do the onchange seems faster and more efficient than using Form. Is there a review on the performance impact on using Form rather than onchange_helper?

Concerning adding the dependency on onchange_helper, I don’t see your point. Do you think it would be better to copy/paste the code from onchange_helper rather than adding the dependency?

**Comment by luc-demeyer** [comment]
@vincent-hatakeyama 
I also don't like the use of odoo.tests code outside the unit tests but if Pedro says that it has no drawbacks than he is probrably right.
But I also agree with @pedrobaeza that we should avoid adding a dependency on a stable module.
What about replacing the play_onchange by the regular onchange methods in the account.move,post() method ?

**Comment by pedrobaeza** [comment]
The first question is: which problem do you have right now with current code?

**Pull request closed without merging**
