### PR TITLE
[12.0][FIX] account_move_fiscal_month: error when creating account.move

### PR DESCRIPTION
**Pull request by Olageibol**
PR to fix error when trying to create a new account move. The company isn't defined on create.

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
I could reproduce the error with the current code. I tested and now that error is not happening anymore. :+1:

**Review by andreschenkels — APPROVED** [review]
LGTM 
This error is realy anoying so please merge this bugfix

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Pull request merged**
