### PR TITLE
Add initial CoinMarketCap currency update service.

### PR DESCRIPTION
**Pull request by rossigee**
Offering this up for anyone else that may find it useful/interesting.

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
Thanks @rossigee. You might be interested in 
https://github.com/OCA/account-financial-tools/pull/619
https://github.com/Eficent/cryptocurrency

Is there a reason for you to support only 'BTC', 'ETH', 'LTC'? CoinMarketCap seems to support a very large number of additional cryptocurrencies.

**Comment by rossigee** [comment]
Thanks for the link @jbeficent - that's some very interesting/useful code there. I'm currently only running 9.0 and 10.0 instances, and struggling to get them upgraded to 11.0 (for now), so I'll have to play around with that in a test environment later, but I like that you've extended 'res.currency', which is what I was struggling to get my newbie head around for the decimal places issue I reported here:

https://github.com/odoo/odoo/issues/19668

Re: only adding three currencies. No real reason. It was just enough to get it to basically work and start fetching rates. It could/should probably be extended to retrieve the list of currencies dynamically from the API.

**Comment by JordiBForgeFlow** [comment]
@rossigee Certainly the decimal accuracy is an issue. And perhaps what is needed is to specify the inverted rate using https://github.com/OCA/account-financial-tools/pull/627

**Comment by JordiBForgeFlow** [comment]
@rossigee FYI we're going to pick up your work and continue it in order to fetch all possible currencies or those defined in config + use inverted rates where needed. We will publish in the new OCA repo https://github.com/OCA/currency

**Comment by rossigee** [comment]
@jbeficent - thank you

**Comment by JordiBForgeFlow** [comment]
Replaced by https://github.com/OCA/currency/pull/7

**Pull request closed without merging**
