### PR TITLE
Migrate account_reversal

### PR DESCRIPTION
**Pull request by guewen**
Migrate account_reversal to version 8.0 (make it works, no refactoring or new api)

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by tafaRU** [comment]
The migration LGTM
@guewen @pedrobaeza, out of curiosity, is it ok migrate a module without using the new API? Are there some guidelines about it? Thank you in advance and sorry to bother you with this.

**Comment by pedrobaeza** [comment]
Hi, @tafaRU, we haven't got written rules on OCA (our fault) about this, because we are overloaded, but the main principle is: have it working on v8 as soon as possible. As old API is totally compatible with v8, there is no obligation to migrate to new API any v8 OCA module, but it is welcome if you do IT, and this would easy the future migration to v9 (where old API is going to be removed). Some people is doing: first iteration with module migrated with old API with minimal changes to make it work, and then, a second iteration with the migration to new API.

Regards.

**Comment by tafaRU** [comment]
@pedrobaeza thanks a lot for your explanation, complete and useful as usual!!
So, goes my :+1: to this PR.

**Comment by guewen** [comment]
@tafaRU odoo does not use the new API so we can't enforce the community modules to use it.
Personally I use the new API at least on the models that are migrated in their base module (account.invoice), and if I'm in a good mood (and according to the time I can spend) I may port a whole module to the new API.

**Comment by tafaRU** [comment]
>  and if I'm in a good mood (and according to the time I can spend) I may port a whole module to the new API.

@guewen it seems to me a good practise, i totally agree :smile: Thanks!!

**Comment by sbidoul** [comment]
:+1: (code review)

**Comment by rvalyi** [comment]
:+1:  LGTM

**Pull request merged**
