### PR TITLE
[12.0] ADD refactored account_fiscal_year

### PR DESCRIPTION
**Pull request by eLBati**
See https://github.com/OCA/account-financial-tools/pull/706#issuecomment-428918963

### CODE REVIEW

**Comment by SimoRubi** [comment]
@eLBati check the :x: bots

**Comment by eLBati** [comment]
@SimoRubi thanks, green

**Comment by mrcast** [comment]
@eLBati 
Functional test ok form me, 
only typing error in the readme 
"Accounting > Configration > Accounting > Fiscal Years" 
instead of 
"Invoicing > Configuration > Accounting > Fiscal Years"

**Comment by eLBati** [comment]
@mrcast thanks, fixed

**Comment by eLBati** [comment]
@damdam-s @lmignon what do you think?

**Comment by damdam-s** [comment]
@eLBati LGTM if only menus are missing on CE edition

**Review by mrcast — APPROVED** [review]
ok

**Comment by eLBati** [comment]
beta module, 1.5 approvals, merge

**Comment by MiquelRForgeFlow** [comment]
@eLBati you should have maintained commit history, to be able to see the changes from v11. When migrating now from v11, we detect issues. This module maybe requires migration scripts, and without commit history, it's more difficult to do it.

**Comment by eLBati** [comment]
@mreficent the module added by this PR is a completely new one, that's why no history was included.

If you need to see the differences from v11, you can run `git diff 11.0..12.0 account_fiscal_year`.
Result at https://gist.github.com/eLBati/4d4d0fe29f83f49ab713cdb5d638bbc1

**Comment by MiquelRForgeFlow** [comment]
Well, if it's a new one, maybe the module should have had a different name. If not, when you migrate, it's treated like a continuation of the same module.

**Pull request merged**
