### PR TITLE
[12.0][FIX] account_asset_management: Asset deletion view failed

### PR DESCRIPTION
**Pull request by syci**
In the **account_asset_management.account_asset_remove_view_form** view, there is a fault in the **sale_value** field.

When we choose a value for that field the **account_sale_id** field that is required is activated, but if we change the voucher creation policy in the **posting_regime** field to residual value, it does not set the sales value back to zero, we have to do it manually for the onchange to hide the **account_sale_id** again.

It should work by hiding the **sale_value** field when the **posting_regime** to residual value option is selected.

image

### CODE REVIEW

**Comment by syci** [comment]
I think we can take the "PR" for good, as travis CI failures are not very relevant.

**Comment by rafaelbn** [comment]
@EmilioPascual ping

**Comment by rafaelbn** [comment]
@syci are you still using this PR?

**Comment by rafaelbn** [comment]
Please @syci could you rebase this PR? Thank you!

**Comment by rafaelbn** [comment]
@rlizana could you please take a look?

**Pull request closed without merging**
