### PR TITLE
[13.0][MIG] migration of account_fiscal_position_vat_check

### PR DESCRIPTION
**Pull request by benwillig**

### CODE REVIEW

**Comment by albariera** [comment]
I am sorry, I did not see that you already did the migration. I have also done it and added some tests. What do you want to do? You can find mine at PR #1189

**Comment by rafaelbn** [comment]
Hello @benwillig any news on this?

**Comment by benwillig** [comment]
@rafaelbn I did this quite a long time ago but I think it was a straightforward migration. So I guess you can merge the duplicate and close mine.

**Comment by rafaelbn** [comment]
Thank you for answering @benwillig . Closing in favor of https://github.com/OCA/account-financial-tools/pull/1189

**Pull request closed without merging**
