### PR TITLE
[14.0][FIX] account_asset_management, fix multi currency problem.

### PR DESCRIPTION
**Pull request by kittiu**
Currently, if you create asset from Vendor Bill @ 500 EUR, you still end up with Asset @ 500 USD.

### CODE REVIEW

**Review by ps-tubtim — APPROVED** [review]

**Comment by Saran440** [comment]
@kittiu please fix conflicts

**Comment by kittiu** [comment]
@MiquelRForgeFlow can you help review this change please? it just add up to your latest changes.

**Comment by MiquelRForgeFlow** [comment]
Should this fix be backported to v13?

**Review by joao-p-marques — APPROVED** [review]
Functional review and looks good :+1: 

@pedrobaeza can you check this please?

**Review by HaraldPanten — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Is this applicable to other branches?

/ocabot merge patch

**Comment by MiquelRForgeFlow** [comment]
@kittiu can you check for v13?

**Comment by kittiu** [comment]
> @kittiu can you check for v13?

Yes

**Comment by kittiu** [comment]
@MiquelRForgeFlow looks like V13 already correct.
https://github.com/OCA/account-financial-tools/blob/13.0/account_asset_management/models/account_move.py#L77

**Comment by MiquelRForgeFlow** [comment]
:+1:

**Pull request merged**
