### PR TITLE
[15.0][MIG] account move line sale info to 15

### PR DESCRIPTION
**Pull request by JoanMForgeFlow**
Migration of the module account_move_line_sale_info, to version 15, depends on stock_account_prepare_anglo_saxon_out_lines_hook, that has not yet been migrated to version 15.
@AaronHForgeFlow 
@bernatpforgeflow

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
Functional test + code review :+1:

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by pedrobaeza** [comment]
FYI, you can put both commands in one comment.

**Pull request merged**
