### PR TITLE
[8.0][ADD] base_vat_optional_vies

### PR DESCRIPTION
**Pull request by sergio-teruel**
This PR fixes this https://github.com/OCA/account-financial-tools/pull/329. @pedrobaeza please can you close it??
cc @tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Check Travis

**Comment by sergio-teruel** [comment]
@pedrobaeza travis fails it's due to account_renumber module.

**Comment by pedrobaeza** [comment]
Travis is still red

**Comment by pedrobaeza** [comment]
Closing as this is now migrated to v10

**Pull request closed without merging**
