### PR TITLE
[16.0][FIX] account_invoice_constraint_chronology - fix unit test

### PR DESCRIPTION
**Pull request by luc-demeyer**

### CODE REVIEW

**Review by pedrobaeza — COMMENTED** [review]
I think a better option is to use the `freeze_time` decorator.

**Comment by luc-demeyer** [comment]
@pedrobaeza 
I changed the PR to use freeze_time (indeed less line of code to get the same result).
The pipeline remains red, now because of a conflict with the demo data generated by the Odoo account module,
cf. /account/demo/account_demo.py

Before I start to work on this one, any suggestion from your end ?
I could e.g. put all the invoices created by the account module to draft but maybe you have another magic trick to disable these conflicting demo data invoices.

**Comment by pedrobaeza** [comment]
In fact, the real error is:

```
2024-07-01 00:00:00,000 926 ERROR odoo odoo.addons.account_invoice_constraint_chronology.tests.test_account_invoice_constraint_chronology: FAIL: TestAccountInvoiceConstraintChronology.test_modify_invoice_date_validated_past_invoice
odoo.exceptions.UserError: Chronology conflict: Invoice SALE/2024/00004 cannot be before invoice BILL/2024/12/0001.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/__w/account-financial-tools/account-financial-tools/account_invoice_constraint_chronology/tests/test_account_invoice_constraint_chronology.py", line 211, in test_modify_invoice_date_validated_past_invoice
    with self.assertRaisesRegex(
AssertionError: "Chronology conflict: Invoice SALE/2024/00004 cannot be before invoice SALE/2024/00003." does not match "Chronology conflict: Invoice SALE/2024/00004 cannot be before invoice BILL/2024/12/0001."
 
2024-07-01 00:00:00,000 926 INFO odoo odoo.addons.account_invoice_constraint_chronology.tests.test_account_invoice_constraint_chronology: Starting TestAccountInvoiceConstraintChronology.test_modify_validated_past_invoice 
```

**Comment by luc-demeyer** [comment]
@pedrobaeza 

The first error is fixed via the freeze_time.

The second error is the conflict with the account module demo data resulting in this:
Chronology conflict: Invoice SALE/2024/00004 cannot be before invoice BILL/2024/12/0001.
The BILL/2024/12/0001 entry is created via /account/demo/account_demo.py.
Hence to fix the pipeline we need to fix this demo data conflict, hence my suggestion to fix it by e.g. putting those entries to draft in the failing unit test.

**Comment by pedrobaeza** [comment]
OK then. The workaround seems reasonable.

**Review by pedrobaeza — APPROVED** [review]
Fast tracking to fix the branch 

/ocabot merge patch

**Pull request merged**
