### PR TITLE
[12.0][ADD] Module to constraint date invoice not to be prior to account move date

### PR DESCRIPTION
**Pull request by sergiocorato**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Isn't this the same: https://github.com/OCA/account-financial-tools/tree/12.0/account_invoice_constraint_chronology ?

**Comment by sergiocorato** [comment]
No, this one check the dates on the same invoice

Il ven 20 set 2019, 15:40 Pedro M. Baeza <notifications@github.com> ha
scritto:

**Comment by pedrobaeza** [comment]
OK, but isn't logical to put that new check inside existing module?

**Comment by sergiocorato** [comment]
> OK, but isn't logical to put that new check inside existing module?
ok, I put it there

**Comment by sergiocorato** [comment]
superseeded by #885

**Pull request closed without merging**
