### PR TITLE
[MIG] port account_move_line_no_default_search to 8.0

### PR DESCRIPTION
**Pull request by sbidoul**

### CODE REVIEW

**Comment by fclementic2c** [comment]
Why not using account_move_line_search_extension instead ? (there 2 important extra search fields partner & period added)

**Comment by pedrobaeza** [comment]
I think this is not the same, because this only defaults current combo boxes to empty, so that there's no filter pre-activated.

**Comment by eLBati** [comment]
:+1:

**Comment by fclementic2c** [comment]
account_move_line_search_extension = defaults current combo boxes to empty + extra search fields partner & period added...

**Comment by pedrobaeza** [comment]
But this is done in another menu entry, doesn't it?

**Comment by sbidoul** [comment]
@fclementic2c @pedrobaeza as far as I can tell, account_move_line_search_extension replaces the Journal Items menu.

account_move_line_search_extension seems to provide a superset of the features of  account_move_line_no_default_search. 

So in the name of consistency, OCA should abandon account_move_line_no_default_search.

**Comment by sbidoul** [comment]
I had a deeper look, and I finally believe this one is useful in itself. As @pedrobaeza mentioned  account_move_line_search_extension is anoter menu entry. Awaiting reviews here.

**Comment by pedrobaeza** [comment]
Please move `icon.png` from /static/src/img to the new path /static/description/.

The rest LGTM (test review).

**Comment by sbidoul** [comment]
@pedrobaeza done

**Comment by pedrobaeza** [comment]
Hi, @sbidoul,

Why are you removing images in the manifest?

**Comment by sbidoul** [comment]
@pedrobaeza 

'images': ['static/src/img/move_line_search_view.png'] was pointing to a non existing image

The image reference in description was not displaying properly on apps.odoo.com.

**Comment by pedrobaeza** [comment]
OK, but still we can use it for local view if we want. BTW, I don't block this PR for this :+1:

**Comment by laetitia-gangloff** [comment]
:+1:

**Pull request merged**
