### PR TITLE
[14.0][IMP] account_loan: add multi-company ir_rule for 'account_loan_line'

### PR DESCRIPTION
**Pull request by toita86**

### CODE REVIEW

**Comment by toita86** [comment]
It's a back porting of this IMP: https://github.com/OCA/account-financial-tools/pull/1816

**Comment by francesco-ooops** [comment]
@etobella good for you?

**Comment by francesco-ooops** [comment]
@toita86 please respect commit authorship :)

**Comment by toita86** [comment]
> @toita86 please respect commit authorship :)

My bad, just fixed.

**Review by francesco-ooops — APPROVED** [review]
no problem, LGTM!

@etobella good for you?

**Review by PicchiSeba — APPROVED** [review]
Code Review: LGTM

**Review by etobella — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
