### PR TITLE
[13.0][BKP][ADD] account_journal_restrict_mode

### PR DESCRIPTION
**Pull request by JordiMForgeFlow**

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
Code review LGTM.

Why the field restrict_mode_hash_table it not readonly in v16.0?

**Comment by JordiMForgeFlow** [comment]
> Code review LGTM.
> 
> Why the field restrict_mode_hash_table it not readonly in v16.0?

It was added as an improvement in the V17 migration (https://github.com/OCA/account-financial-tools/pull/1886). We should backport it, although the constrain already makes sure that is never modified :)

**Review by GuillemCForgeFlow — APPROVED** [review]
LGTM code review 👍🏿

**Pull request merged**
