### PR TITLE
8.0 asset modules - rebased

### PR DESCRIPTION
**Pull request by lepistone**
This supersedes #52. It is a rebase version, now that the asset modules are in 7.0 and we merged 7.0 to 8.0.

I made this rebase with 
`git rebase -X ours origin/8.0`

Note that the module has been already approved in #52. If the rebase seems correct, I think we can merge.

### CODE REVIEW

**Comment by sbidoul** [comment]
Why is the diff so big? I would expect to see a small diff with only the changes to migrate to 8.0 in this PR.

Would it help to do the git mv out of unported first?

**Comment by lepistone** [comment]
@sbidoul `git mv` is a convenience command that does the same as `rm` and `add`. (this is different from `bzr mv` that actually stores information about the move).

Git tries to figure out the move when you log, but if the files differ too much, it will not recognize them as the same file.

It might be that the code differs a lot. I don't know the modules at all, I'm just giving a hand with bureaucracy.

IMO if someone can check that my rebase does have the same code as #52, there's not much more we can do, and we can merge.

**Comment by lepistone** [comment]
Ah wait @sbidoul, you are right... in my rebase, the v7 modules are still in `__unported__`. I'm doing it again. Sorry for the unnecessary lecture about `git mv` :smiley_cat:

**Comment by lepistone** [comment]
Ok, I did it again, this time with a commit moving the modules out of `__unported__` at the beginning.

Now the commit `synch asset mgt with recent V7 changes` is almost empty, and I find that encouraging. What do you think?

**Comment by sbidoul** [comment]
@lepistone Looks much better indeed, thanks! 

You'll need to set installable = True, though.

**Comment by lepistone** [comment]
done.

**Comment by sbidoul** [comment]
Thanks. :+1: 

I compared the code, ran the test suite and made a quick manual sanity check.

**Comment by rdeheele** [comment]
:+1:

**Comment by lepistone** [comment]
:tada:

**Pull request merged**
