### PR TITLE
[14.0][MIG] account move fiscal year 

### PR DESCRIPTION
**Pull request by xavier-bouquiaux**

### CODE REVIEW

**Review by Cedric-Pigeon — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]
Code review. LGTM

**Comment by Cedric-Pigeon** [comment]
@OCA/accounting-maintainers can we move forward by merging ?

**Comment by rafaelbn** [comment]
/ocabot merge patch

I do patch because @rousseldenis like more 😄

**Pull request merged**
