### PR TITLE
[14.0][MIG] account_invoice_constraint_chronology

### PR DESCRIPTION
**Pull request by alexey-pelykh**
Sort-of depends on #1150

### CODE REVIEW

**Comment by ghost** [comment]
@alexey-pelykh With the changes Odoo has made to the invoice sequences in V14 there is a possibility of a numbering error.
I attach a video of the error and how it can be functionally solved. But it would be nice if you could prevent this error from occurring.
https://drive.google.com/file/d/1zRrtskpkZQ6WgPrN7bS7uEecgGxhylCa/view

**Comment by tafaRU** [comment]
@alexey-pelykh thanks for the PR!
I see last commit message is `wip`, will you keep working on this?

**Comment by alexey-pelykh** [comment]
@tafaRU to be exact, a functional testing of the change done in "wip" commit is due that handles the case described by @gelo-landoo

**Comment by tafaRU** [comment]
Ok @alexey-pelykh, so the PR is already ready to be reviewed, right? When will you plan to squash the last commit with the migration one?

**Comment by alexey-pelykh** [comment]
@tafaRU as soon as someone will confirm functional correctness of the newly-introduced behavior. W/o "wip" commit it's a as-is v13 migration, "wip" commit only addresses the v14 specifics that I'm not very familiar with.

**Comment by stevech091** [comment]
hi @alexey-pelykh , I have done this use case :
1) create an invoice with yesterday date and validate it
2) create an invoice with today date and validate it
3) I have reset to draft the first one but when I try to validate it the system give me this error message 
"Chronology conflict: An invoice with a higher number INV/2021/05/...  exists."
So this not correct because we don't create a new invoice but validate an exist one.
Thanks

**Comment by alexey-pelykh** [comment]
@stevech091 so just to ensure we're on the same page: in your case you'd expect the validation to happen w/o error because invoice already has a number assigned that's smaller than existing-validated invoice?

**Comment by stevech091** [comment]
@alexey-pelykh 
Yes, I expect the invoice will be validated again because it already has a number and the date has not changed.
thanks

**Comment by alexey-pelykh** [comment]
@stevech091 but that's exactly what this module is supposed to lock:
```
It prevents the validation of invoices when:
* there are validated invoices with a later date
```
There's no pre-condition that "unless it has been already validated"

**Comment by alexey-pelykh** [comment]
@gelo-landoo would it be possible for you to check the extra behaviour that addresses your bug report?

**Comment by stevech091** [comment]
@alexey-pelykh 
But the precondition "it has been already validated " is necessary also connect to the not change of invoice date.

**Comment by alexey-pelykh** [comment]
@stevech091 does it allow your use-case on v12? Since if it's not, that's something out of migration scope. Revalidation in v12 as far as I can see also has to follow the same rules - there has to be no newer invoices

**Comment by ghost** [comment]
@alexey-pelykh Hello,
These days I have a lot of work. I'll try to take a moment to see if I can prove it.

**Review by petrus-v — APPROVED** [review]
LGTM Functionnal test and code review

**Review by SimoneVagile — APPROVED** [review]

**Pull request merged**
