### PR TITLE
[14.0][FIX] account_asset_management: Avoid the error when clicking on "Delete" button if there is a residual value and all the depreciation lines are posted

### PR DESCRIPTION
**Pull request by victoralmau**
FWP from 13.0: https://github.com/OCA/account-financial-tools/pull/1282

Avoid the error when clicking on `Delete` button if there is a residual value and all the depreciation lines are posted.

Please @pedrobaeza and @joao-p-marques can you review it?

@Tecnativa TT32861

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Travis is red

**Comment by victoralmau** [comment]
> Travis is red

Related to `base_vat_optional_vies` https://github.com/OCA/account-financial-tools/pull/1297

**Review by joao-p-marques — APPROVED** [review]
Apart from the test errors, LGTM 👍

**Comment by victoralmau** [comment]
Now this is ready to merge because Travis is green.

**Pull request merged**
