### PR TITLE
[13.0][IMP] account_move_line_sale_info optional fields in tree view

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
Tree view for journal items is growing too much, also little fix in filters

cc @ForgeFlow

### CODE REVIEW

**Review by JordiMForgeFlow — APPROVED** [review]
LGTM 👍🏼 , thanks for the fix in the filters, much more pretty now :)

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Review by etobella — APPROVED** [review]
:+1:

**Review by MiquelRForgeFlow — APPROVED** [review]

**Pull request merged**
