### PR TITLE
7.0 account chart update backport

### PR DESCRIPTION
**Pull request by pedrobaeza**
Backport changes from 8.0 and adapt it to v7

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please someone review this

**Comment by pedrobaeza** [comment]
I have also backport the hooks, so please review. cc: @sbidoul

**Comment by sbidoul** [comment]
:+1: (code review, no test)

**Comment by rafaelbn** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Runbot warning unrelated. I proceed with the merge to unlock this

**Pull request merged**
