### PR TITLE
[12.0][FIX] account_spread_cost_revenue: convert total amount to spread currency

### PR DESCRIPTION
**Pull request by espo-tony**

### CODE REVIEW

**Comment by astirpe** [comment]
@casvissers here you are

**Review by CasVissers-360ERP — APPROVED** [review]
👍

**Comment by CasVissers-360ERP** [comment]
@kittiu

**Comment by kittiu** [comment]
@espo-tony any guide what this FIX is all about ? ;)

**Comment by CasVissers-360ERP** [comment]
@kittiu 
Base currency = USD
Invoice currency = EUR

Before fix:
Invoice = 10.000 EUR -> spread = 10.000 USD

After fix:
Invoice = 10.000 EUR -> spread = 15.000 USD

**Comment by espo-tony** [comment]
If the invoice is in a currency (let's say EUR) and the spread board is expressed in a different currency (let's say USD, and let's say conversion rate is 1EUR = 1.2USD), I expect the total amount to be converted from a currency to the other.

For example: Invoice line for 10.000EUR I'd expect it to generate a number of spread lines for a total of 12.000USD; without this change, it will instead generate spread lines for a total of 10.000USD.

**Review by kittiu — APPROVED** [review]

**Review by astirpe — APPROVED** [review]
/ocabot merge patch

**Review by marcelsavegnago — APPROVED** [review]

**Pull request merged**
