### PR TITLE
[16.0][FIX] account_invoice_constraint_chronology: maintain numbering consistency when changing invoice dates

### PR DESCRIPTION
**Pull request by RodrigoBM**
INV5 YYYYMM20 posted
INV4 YYYYMM15 posted
INV3 YYYYMM10 posted
INV2 YYYYMM05 posted
INV1 YYYYMM01 posted
if we pass INV3 to draft and change the date to YYYYYMM15 or YYYYYMM05 it should be able to validate, but if we change the date higher than YYYYYMM15 or lower than YYYYYMM05 it should not be able to validate.

### CODE REVIEW

**Comment by liebana** [comment]
Functional review, LGTM

**Review by liebana — APPROVED** [review]

**Review by JavierIniesta — APPROVED** [review]
Cde review. LGTM

**Comment by rafaelbn** [comment]
In fact, testing, the module doesn't work as it allows to post with previous and posterior dates crossing date and sequence. I will review again. Please set PR in order to test it in runbot! Now is WIP Thank you @RodrigoBM

**Review by rafaelbn — CHANGES_REQUESTED** [review]
Need to review in runbot, my test in local fails

**Comment by liebana** [comment]
@rafaelbn You have not checked the proper box on the journal configuration.


https://github.com/OCA/account-financial-tools/assets/7783296/7e4e860e-4e6e-4cf2-b533-a69ed106f688

**Comment by RodrigoBM** [comment]
What problems do @rafaelbn  have?

**Comment by SoniaViciana** [comment]
LGTM.

Note: This FIX does not consider invoices in canceled status. It is the only case in which there could be inconsistencies between date and number:

image

**Review by SoniaViciana — APPROVED** [review]

**Review by fcvalgar — APPROVED** [review]
Functional review
LGTM, thak you @RodrigoBM 
ping @rafaelbn 

Captura desde 2023-06-21 13-13-19

Captura desde 2023-06-21 13-12-58

Captura desde 2023-06-21 13-12-48

**Comment by rafaelbn** [comment]
> @rafaelbn You have not checked the proper box on the journal configuration.

@liebana ! too many years using this module 😄 I know.


> Need to review in runbot, my test in local fails

@RodrigoBM the problem I get is that is impossible to test in runbot 😢 

https://www.loom.com/share/147da3dcc813474fbdc4679f4018ba76?sid=32a6a589-0bc7-428c-bd18-065280386e8f

I reproduce the error you say in my local but not in runbot...

Reopened: https://github.com/OCA/account-financial-tools/issues/1648

@RodrigoBM you can reproduce the error  I get un runbot also in this PR

http://oca-account-financial-tools-16-0-pr1666-cc131fe08193.runboat.odoo-community.org/web#id=23&cids=1&menu_id=120&action=241&active_id=1&model=account.move&view_type=form

Press "confirm" and...

Validation Error

```
The operation cannot be completed: new row for relation "account_move" violates check constraint "account_move_name_state_diagonal"
DETAIL:  Failing row contains (23, 0, null, 1, 1, null, null, null, null, null, null, 4, 10, 10, 10, null, null, 2, null, 2, null, null, 2, 2, , null, /, null, posted, out_invoice, no, null, null, null, not_paid, null, Deco Addict, null, 2023-06-22, null, 2023-06-22, 2023-07-22, null, 47.00, 7.05, 54.05, 54.05, 47.00, 7.05, 54.05, 54.05, 54.05, 0.00, f, f, f, t, f, 2023-06-22 19:25:07.749361, 2023-06-22 19:25:46.531688, null, 2023/0000000020, null, null, null).
```

**This error is nor related to this PR obviously**

**Review by rafaelbn — APPROVED** [review]
👍🏼 Optimistic as I cannot test it un runbot

**Comment by RodrigoBM** [comment]
I will check this error, but it is not related to the chronology, as it still cannot be confirmed if you have the chronology option disabled.

@rafaelbn

**Pull request merged**
