### PR TITLE
[16.0][MIG] account_asset_transfer

### PR DESCRIPTION
**Pull request by Saran440**
Refactor analytic in asset transfer

### CODE REVIEW

**Comment by kittiu** [comment]
@Saran440 please fix pre-commit, so it can be merged. Thanks!

**Comment by Saran440** [comment]
@kittiu Fixed. Can you check please.

**Review by ps-tubtim — APPROVED** [review]
Functional Test: Ok

**Review by kittiu — APPROVED** [review]

**Pull request merged**
