### PR TITLE
[17.0][MIG] account_usability: Migration to 17.0

### PR DESCRIPTION
**Pull request by hussain**
Migration of `account_usability` to 17.0

https://github.com/odoo/odoo/commit/512574861691f425ec6a17f20fe4b586bb88a299 all templates are removed (chart, account, fiscal position, tax).

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please squash the 2 latest commits with the same commit message together.

/ocabot migration account_usability

**Comment by hussain** [comment]
Thanks Pedro.

Squashed.

**Review by smcqueen81 — APPROVED** [review]
Functional Ok

**Review by celm1990 — APPROVED** [review]

**Review by alexis-via — APPROVED** [review]

**Pull request merged**
