### PR TITLE
13.0_account_financial_tools [fix] acl for group billing

### PR DESCRIPTION
**Pull request by vanderperre**

### CODE REVIEW

**Comment by astirpe** [comment]
Isn't this PR the same as https://github.com/OCA/account-financial-tools/pull/1497?

**Comment by vanderperre** [comment]
@astirpe ya it is the same. 
do you want that i close this one ... ?

**Comment by astirpe** [comment]
Yes, maybe closing this one is better, before someone starts to comment here. The other PR has already comments, so let's continue there, is that ok?

**Comment by vanderperre** [comment]
ok i close it

**Pull request closed without merging**
