### PR TITLE
[10.0][FIX] account_asset_management: fix stack while trying to log an error

### PR DESCRIPTION
**Pull request by Cedric-Pigeon**
This PR intends to solve this stack trace while computing assets
image

### CODE REVIEW

**Comment by Cedric-Pigeon** [comment]
@luc-demeyer @fclementic2c I need your review please.

**Review by bodedra — APPROVED** [review]

**Comment by luc-demeyer** [comment]
@Cedric-Pigeon 
The fix should rather be:

                asset = depreciation.asset_id
                asset_ref = asset.code and '%s (ref: %s)' \
                    % (asset.name, asset.code) or asset.name

**Comment by Cedric-Pigeon** [comment]
@luc-demeyer Thanks, I just fixed.

**Review by luc-demeyer — APPROVED** [review]

**Comment by luc-demeyer** [comment]
failed unit tests but unrelated to this module hence we can merge this one.

**Comment by luc-demeyer** [comment]
Two approvals.
Travis red on unrelated issue in other module.
Can someone merge this one ?

**Comment by pedrobaeza** [comment]
Is this happening in v11 also?

**Comment by luc-demeyer** [comment]
forward port of this patch to 11.0, cf. https://github.com/OCA/account-financial-tools/pull/782

**Pull request merged**
