### PR TITLE
[MIG][14.0] account_loan

### PR DESCRIPTION
**Pull request by AntoniRomera**

### CODE REVIEW

**Review by FernandoRomera — APPROVED** [review]

**Review by MRomeera — APPROVED** [review]

**Review by olgamarcocb — APPROVED** [review]
:+1: LGTM

**Comment by AntoniRomera** [comment]
@OCA/accounting-maintainers Anyone can merge?

**Review by etobella — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]
Code review

**Pull request merged**
