### PR TITLE
[ADD] Allow to reverse entries in batch

### PR DESCRIPTION
**Pull request by benwillig**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
2 things:

* As the module name is a technical one, isn't better to call it account_reversal_queue or similar?
* OCA/queue was created to host all the modules for queue modules. Shouldn't be hosted there?

**Comment by benwillig** [comment]
I wanted to be coherent with ```account_move_batch_validate``` which also uses ```queue_job``` module. About the repo to use, I'm not sure we should move this kind of module in the ```queue``` repository because then, there would be tons of module being in this repo only because they depends on ```queue_job```.

**Comment by pedrobaeza** [comment]
That name was selected when there wasn't even `queue_job` module, but I think we should rename it to follow that approach.

The same is for the hosting: having all of there in one place we will be able to know which things work with queue_job instead of having to explore each of the repos.

@guewen @lmignon what do you think on this?

**Comment by benwillig** [comment]
Renamed to ```account_reversal_queue```.

**Comment by sbidoul** [comment]
I'm neutral on the renaming. `base_import_async` is another example btw.

Regarding hosting, I'm in favor of keeping it close to account_move_reversal (ie here). Maintainers of such a module are more likely to  work around here, whereas OCA/queue maintainers focus on the core module only and cannot afford to maintain all modules that depend on it.

**Comment by pedrobaeza** [comment]
OK, let's keep it here and thanks for the renaming.

**Pull request closed without merging**
