### PR TITLE
[16.0][ADD] account_move_post_date_user

### PR DESCRIPTION
**Pull request by JordiMForgeFlow**
Track journal entry posting date and user

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
Functional review on runboat.

New fields not added to any view, is that on purpose?

**Review by GuillemCForgeFlow — APPROVED** [review]
LGTM 👍🏽

**Comment by JordiMForgeFlow** [comment]
> Functional review on runboat.
> 
> New fields not added to any view, is that on purpose?

Better to show them, I have added them in the view. Thank you!

**Review by AaronHForgeFlow — COMMENTED** [review]
LGTM. Why not making the state field with tracking=True?

**Comment by AaronHForgeFlow** [comment]
Forget my last comment, the field is already tracked.

I think this is fine for reporting purposes.

**Review by AaronHForgeFlow — APPROVED** [review]
Code LG!

**Review by AaronHForgeFlow — APPROVED** [review]
Functional review as well

**Review by luisDIXMIT — APPROVED** [review]
LGTM :+1: 
@etobella

**Review by etobella — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
