### PR TITLE
New Currency Rate Update Source Turkish National Bank

### PR DESCRIPTION
**Pull request by aaltinisik**
Exchange rate source Turkish National Bank added
added terms into Turkish translation

[Review on Reviewable](https://reviewable.io/reviews/oca/account-financial-tools/307)

### CODE REVIEW

**Comment by pedrobaeza** [comment]
As stated in other PRs, I think this is the moment to start to add providers as new modules, instead of enlarge this already bloated module even more. Can you please rebuild your PR to be the first one with this approach?

**Comment by aaltinisik** [comment]
sorry Pedro, not that experienced. Please help again about pep8 error. how to split this line for pep8
xpath_curr_rate = '/Tarih_Date/Currency[@Kod="%s"]/ForexBuying/text()' % (curr.upper())

**Comment by pedrobaeza** [comment]
```
xpath_curr_rate = ('/Tarih_Date/Currency[@Kod="%s"]/'
                   'ForexBuying/text()' % curr.upper())
```

**Comment by aaltinisik** [comment]
Tried to solve lint check errors however, errors were already in the module so out of scope of this PR.

**Comment by aaltinisik** [comment]
Dear Pedro,

I understand your point of view, however this function is a must for us and even if it is bloated we need to use and I would like to share.  If anyone will write a new module structure and do it nicely, I will try my best to add my source to that new structure also.  However until then please let my first PR to the OCA merge and other users in my territory use this. 

this just kill my ambition to work for new contributions.

**Comment by pedrobaeza** [comment]
It's not my goal to discourage you in your contributions. I was only expressing the feeling I have with this module, being continually fed with more and more sources, all in the same monolithic module. Anyway, I'm not able to work on that refactoring due to time constrains and because this module is not one of my focus in my customer base. 

But if the rest of the possible reviewers agree, I don't have problem to accept one source more before the refactoring, so reviews are welcome.

**Pull request closed without merging**
