### PR TITLE
[17.0][MIG] account_move_line_sale_info

### PR DESCRIPTION
**Pull request by astirpe**
Depends on https://github.com/OCA/stock-logistics-warehouse/pull/1967

### CODE REVIEW

**Review by CasVissers-360ERP — APPROVED** [review]
Functional review

**Review by StefanRijnhart — APPROVED** [review]
You might want to review my superseding PR for account_move_line_stock_info at https://github.com/OCA/stock-logistics-warehouse/pull/2160

**Review by sebalix — APPROVED** [review]

**Comment by StefanRijnhart** [comment]
@astirpe with the merge of https://github.com/OCA/stock-logistics-warehouse/pull/2160 you can remove the test dependency.

**Comment by astirpe** [comment]
@StefanRijnhart done, thanks!

**Pull request merged**
