### PR TITLE
[13.0][add][account_move_print]

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
This module adds the option to print Journal Entries.

#. Go to the *Accounting module* and click on *Accounting > Journal Entries*.
#. Create or pick one of them.
#. Inside the *print button* you will see a new option called "Journal Entries".
#. You now have your Journal Entry ready to print.

image

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
cc @DavidBForgeFlow @JordiMForgeFlow @AdriaGForgeFlow @AaronHForgeFlow

**Review by HaraldPanten — APPROVED** [review]
Functional review

**Comment by JordiMForgeFlow** [comment]
Functional and code review 👍🏼 Perhaps would be nice to also print the total debit and credit in the last table line?

**Review by ps-tubtim — APPROVED** [review]
Code and Functional Test LGTM.

**Review by AdriaGForgeFlow — APPROVED** [review]

**Comment by JordiBForgeFlow** [comment]
@JordiMForgeFlow nice catch. Fixed that.

image

**Review by JordiMForgeFlow — APPROVED** [review]

**Pull request merged**
