### PR TITLE
[IMP] account_credit_control: add account_followup missing features

### PR DESCRIPTION
**Pull request by cubells**
[WIP] Absolutely.

New features
- Add account_followup fields
- Update translations
- Relocate account credit control because if not, only advisers can see credit control information.
- Add menu with manual followup partners.

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
@rafaelbn please review

**Review by luismontalba — APPROVED** [review]
Tested on runbot

**Comment by kenvac** [comment]
@cubells wouldn't it be wise to isolate fields in separate module?

**Comment by pedrobaeza** [comment]
@kenvac why? These fields are needed for credit control.

**Comment by kenvac** [comment]
@pedrobaeza just a thought. I had a look at the code and makes more sense to keep within module

**Comment by pedrobaeza** [comment]
Mergin then after more than 5 days and 2 approvals.

**Pull request merged**
