### PR TITLE
asset management: silence warning

### PR DESCRIPTION
**Pull request by lepistone**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
To give green branches...

:+1:

**Comment by dcorio** [comment]
:+1:

**Comment by sbidoul** [comment]
I'm personally :-1: with silencing import warnings. When a real error will occur it will be hard to debug.

If `warn` really causes unsolvable issues, then it should be `info`, but the message should stay.

Plus, in this case the try/except is not at the correct place, but that's the topic for another PR.

**Comment by luc-demeyer** [comment]
I agree with Stephan's point of view.

**Comment by lepistone** [comment]
@sbidoul what would be the correct place?

The message is always wrong because it is shown only when the module is not installed.

Weirdly enough, a workaround would be removing the module icon in the `static` folder: see https://github.com/odoo/odoo/blob/8.0/openerp/http.py#L1292-L1320

**Comment by dcorio** [comment]
i think i'm missing something...
this PR is all about that try/except. isn't it?
just can't understand what the icon has to do with it :)

**Comment by sbidoul** [comment]
@dcorio adding the icon required the creation of a `static` directory in the module. This means the module becomes autoloaded by the http server even if not installed. This in turns triggers import errors for dependencies that are not installed (and not necessary when the module is not used).

See https://github.com/odoo/odoo/issues/7507 for a discussion.

**Comment by sbidoul** [comment]
@lepistone 

> what would be the correct place?

I would put the try/except closer to the dependency import, such as.
https://github.com/OCA/account-financial-tools/blob/8.0/account_asset_management_xls/report/account_asset_report_xls.py#L27

**Comment by lepistone** [comment]
@sbidoul I tried, but this way the interpreter keeps reading the file and will crash when the module is undefined.

**Comment by sbidoul** [comment]
@lepistone 

> Weirdly enough, a workaround would be removing the module icon in the static folder: see https://github.com/odoo/odoo/blob/8.0/openerp/http.py#L1292-L1320

You may want to experiment with odoo/odoo#8591. If it works (which needs more testing to prove) it's worth pushing Odoo to merge it.

**Pull request closed without merging**
