### PR TITLE
[FIX] base_vat_optional_vies: Remove contraints on dotted names

### PR DESCRIPTION
**Pull request by Tardo**
This fixes https://github.com/OCA/account-financial-tools/pull/840#pullrequestreview-267729545

Cc @tecnativa

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@sbidoul check this problem with pinned docutils version.

**Comment by sbidoul** [comment]
:angry:

**Comment by pedrobaeza** [comment]
Thanks

**Pull request closed without merging**
